export const PRODUCT = {

constituents: {
  packages: ['nonprofitcloud'],
  name: "Constituents",
  icon: "\u{1F465}",
  color: "#f59e0b",
  description: "The foundation of Nonprofit Cloud's data model. Constituents represent every individual and organization your nonprofit interacts with: donors, volunteers, board members, program participants, and partner organizations. Individuals are modeled as Person Accounts, while organizations use standard Business Accounts. The Contact Profile object extends constituent records with fundraising-specific attributes like recurring donor type.",
  components: [
    {id:"person-accounts",name:"Person Accounts",icon:"\u{1F9D1}",desc:"Represents individual constituents such as donors, volunteers, and program participants. Person Accounts combine Account and Contact into a single record, providing a unified view of each person's activities, gifts, relationships, and program participation.",tags:["Account","Contact","ContactProfile"],connections:[{planet:"households",desc:"Individuals are linked to households via Party Relationship Groups"},{planet:"relationships",desc:"People form relationships with other constituents"},{planet:"contact_points",desc:"Person accounts have addresses, emails, and phone numbers"}]},
    {id:"business-accounts",name:"Business Accounts",icon:"\u{1F3E2}",desc:"Represents organizations such as foundations, corporate donors, matching gift employers, and partner agencies. Business Accounts support hierarchies for multi-office organizations, enabling roll-up reporting across an entire corporate structure.",tags:["Account"],connections:[{planet:"relationships",desc:"Organizations form relationships with other organizations and individuals"},{planet:"fundraising",desc:"Organizations can be donors and grant sources"}]},
    {id:"contact-profiles",name:"Contact Profiles",icon:"\u{1F4C7}",desc:"Extends constituent records with fundraising-specific attributes. The Contact Profile tracks whether someone is a recurring donor, their donor classification, and other profile data that fundraising automation uses to personalize engagement strategies.",tags:["ContactProfile"],connections:[{planet:"gift_commitments",desc:"Contact profiles track recurring donor status"},{planet:"fundraising",desc:"Donor profiles inform cultivation strategies"}]},
    {id:"account-hierarchies",name:"Account Hierarchies",icon:"\u{1F3D7}",desc:"Models parent-child relationships between organizations for multi-office or affiliated structures. Corporate hierarchies enable roll-up of donation totals, volunteer hours, and engagement metrics across an entire organizational family. Useful for tracking foundation affiliates and corporate giving programs.",tags:["Account"],connections:[{planet:"relationships",desc:"Hierarchies complement relationship records between organizations"}]}
  ],
  dataFlow:["Admin enables Person Accounts and configures account record types","Individual constituents are created as Person Accounts with Contact Profile","Organizations are created as Business Accounts with optional hierarchy","Constituent records accumulate activities, gifts, and program participation over time","Fundraising and program staff access a unified 360-degree constituent view"],
  connections:[{planet:"households",desc:"Individuals belong to households"},{planet:"relationships",desc:"Constituents have relationships"},{planet:"contact_points",desc:"Accounts have contact information"},{planet:"fundraising",desc:"Donors are constituents"},{planet:"gift_transactions",desc:"Gift transactions belong to donors"},{planet:"gift_entry",desc:"Donors matched during gift entry"},{planet:"soft_credits",desc:"Soft credits attributed to constituents"},{planet:"programs",desc:"Program participants are constituents"},{planet:"case_management",desc:"Case subjects are constituents"},{planet:"volunteers",desc:"Volunteers are constituents"},{planet:"grantmaking",desc:"Grant applicants are constituents"},{planet:"security",desc:"Constituent data access is secured"},{planet:"setup",desc:"Account model configured in setup"}]
},

households: {
  packages: ['nonprofitcloud'],
  name: "Households & Groups",
  icon: "\u{1F3E0}",
  color: "#10b981",
  description: "Models households and other group affiliations using Party Relationship Groups. Unlike NPSP's rigid Household Account model, Nonprofit Cloud uses a flexible, time-bound grouping system. A Party Relationship Group with Type 'Household' links individuals via Account Contact Relationships with roles like Head of Household, Member, or Dependent. Groups can overlap, meaning one person can belong to multiple households or affinity groups.",
  components: [
    {id:"party-relationship-groups",name:"Party Relationship Groups",icon:"\u{1F46A}",desc:"The container object for modeling households and other group types. Each group has a Type field (Household, Affinity Group, etc.), a name, and optional start/end dates. Groups are Business Accounts linked to members through Account Contact Relationships, replacing NPSP's dedicated Household Account object with a more flexible and standard approach.",tags:["PartyRelationshipGroup"],connections:[{planet:"constituents",desc:"Groups contain individual constituents as members"},{planet:"relationships",desc:"Group members have inter-relationships"}]},
    {id:"household-membership",name:"Household Membership",icon:"\u{1F511}",desc:"Account Contact Relationships link individuals to their household group with specific roles. Each membership record captures the person's role in the household (Head of Household, Spouse, Dependent, etc.), whether the relationship is active, and effective date ranges. This enables time-bound membership tracking as household composition changes.",tags:["AccountContactRelationship"],connections:[{planet:"constituents",desc:"Members are Person Account constituents"},{planet:"relationships",desc:"Membership roles complement interpersonal relationships"}]},
    {id:"household-addressing",name:"Household Addressing",icon:"\u{1F4EC}",desc:"Manages shared contact information for household members. When multiple individuals share a household, their mailing preferences and address information coordinate through the household group. Primary contact designation and salutation preferences help generate accurate household-level communications.",tags:["PartyRelationshipGroup"],connections:[{planet:"contact_points",desc:"Household members share contact point addresses"},{planet:"campaigns",desc:"Household addressing supports campaign mailings"}]}
  ],
  dataFlow:["Admin creates a Party Relationship Group with Type Household","Individual Person Accounts are linked as members via Account Contact Relationships","Each member receives a role such as Head of Household, Spouse, or Dependent","Membership dates track household composition changes over time","Household-level reporting aggregates donations and activities across all members"],
  connections:[{planet:"constituents",desc:"Individuals belong to households"},{planet:"relationships",desc:"Household members have inter-relationships"},{planet:"contact_points",desc:"Households share contact information"},{planet:"campaigns",desc:"Household addressing for campaign mailings"}]
},

relationships: {

  packages: ['nonprofitcloud'],
  name: "Relationships",
  icon: "\u{1F91D}",
  color: "#8b5cf6",
  description: "Tracks the connections between constituents at every level: individual-to-individual, individual-to-organization, and organization-to-organization. Contact Contact Relationships model personal connections like spouse, parent-child, or colleague. Account Account Relationships model organizational ties like affiliations and partnerships. Party Role Relationships define the configurable relationship types available in the system.",
  components: [
    {id:"contact-contact-relationships",name:"Contact Contact Relationships",icon:"\u{1F46B}",desc:"Models direct relationships between individuals. Each record captures two contacts, their reciprocal roles (e.g., Spouse/Spouse, Parent/Child, Mentor/Mentee), and an active status. Relationship records appear on both contacts' related lists, giving fundraisers and program staff visibility into personal networks that influence giving and participation.",tags:["ContactContactRelationship"],connections:[{planet:"constituents",desc:"Links individual Person Account records"},{planet:"soft_credits",desc:"Relationships inform soft credit attribution for gifts"}]},
    {id:"account-contact-relationships",name:"Account Contact Relationships",icon:"\u{1F4BC}",desc:"Links individuals to organizations with specific roles. Beyond household membership, ACRs track employment, board membership, volunteer affiliation, and program enrollment connections. Each record includes a role, active status, and dates, enabling comprehensive tracking of how people are connected to organizations.",tags:["AccountContactRelationship"],connections:[{planet:"constituents",desc:"Links individuals to organizations"},{planet:"households",desc:"ACRs link household members to household groups"}]},
    {id:"account-account-relationships",name:"Account Account Relationships",icon:"\u{1F3E2}",desc:"Models relationships between organizations, such as corporate affiliations, foundation-grantee relationships, partner agency connections, and vendor relationships. Each record captures two accounts, a relationship type, and directional roles. Useful for understanding organizational networks in grantmaking and institutional fundraising.",tags:["AccountAccountRelationship"],connections:[{planet:"constituents",desc:"Links organization accounts together"},{planet:"grantmaking",desc:"Organization relationships inform grantmaking"}]},
    {id:"party-role-relationships",name:"Party Role Relationships",icon:"\u{1F3F7}",desc:"Metadata that defines the available relationship types and their reciprocal labels. Admins configure which relationship roles are available for Contact Contact Relationships and Account Account Relationships. Each party role relationship specifies the forward label, reciprocal label, and which object types it applies to.",tags:["PartyRoleRelationship"],connections:[{planet:"setup",desc:"Relationship types are configured by admins in setup"}]}
  ],
  dataFlow:["Admin configures available relationship types via Party Role Relationships","Staff creates relationship records between constituents as connections are discovered","Each relationship specifies roles for both parties and an active status","Relationship data surfaces on constituent records for a 360-degree view","Fundraisers and program staff use relationship networks to inform strategy"],
  connections:[{planet:"constituents",desc:"Relationships connect constituents"},{planet:"households",desc:"Household members have relationships"},{planet:"soft_credits",desc:"Relationships inform soft credit decisions"},{planet:"grantmaking",desc:"Organization relationships inform grants"},{planet:"setup",desc:"Relationship types configured in setup"}]
},

contact_points: {
  packages: ['nonprofitcloud'],
  name: "Contact Information",
  icon: "\u{1F4DE}",
  color: "#06b6d4",
  description: "Manages addresses, email addresses, and phone numbers using Salesforce's polymorphic Contact Point objects. Each contact point links to an Account (individual or organization) and supports multiple records per person with a primary designation. This replaces NPSP's Address object with standardized, GDPR-compliant objects that work across Salesforce Industries products.",
  components: [
    {id:"contact-point-addresses",name:"Contact Point Addresses",icon:"\u{1F4CD}",desc:"Stores physical mailing and location addresses for constituents. Each address record includes street, city, state, postal code, country, and an address type (Home, Work, Vacation, Other). The IsPrimary flag designates the preferred mailing address. Multiple addresses per person enable seasonal and multi-location tracking.",tags:["ContactPointAddress"],connections:[{planet:"constituents",desc:"Addresses belong to constituent accounts"},{planet:"campaigns",desc:"Addresses used for direct mail campaigns"},{planet:"households",desc:"Household members may share addresses"}]},
    {id:"contact-point-emails",name:"Contact Point Emails",icon:"\u{1F4E7}",desc:"Stores email addresses for constituents with support for multiple records per person. Each record captures the email address, a type classification (Personal, Work, Other), and a primary designation. Email contact points integrate with campaign communications and acknowledgment workflows.",tags:["ContactPointEmail"],connections:[{planet:"constituents",desc:"Emails belong to constituent accounts"},{planet:"campaigns",desc:"Email addresses used for outreach"}]},
    {id:"contact-point-phones",name:"Contact Point Phones",icon:"\u{260E}",desc:"Stores phone numbers for constituents with support for multiple records per person. Each record captures the telephone number, a type classification (Home, Mobile, Work, Fax), and a primary designation. Phone contact points support donor outreach and volunteer coordination workflows.",tags:["ContactPointPhone"],connections:[{planet:"constituents",desc:"Phone numbers belong to constituent accounts"}]}
  ],
  dataFlow:["Admin configures contact point fields and page layouts","Staff creates contact point records when gathering constituent information","Each contact point is linked to the constituent's account record","Primary designation is set for the preferred contact method per type","Contact points drive campaign targeting and communication workflows"],
  connections:[{planet:"constituents",desc:"Contact information belongs to accounts"},{planet:"households",desc:"Household members share contact information"},{planet:"campaigns",desc:"Contact points used for campaign outreach"}]
},

fundraising: {
  packages: ['nonprofitcloud'],
  name: "Fundraising Pipeline",
  icon: "\u{1F4B0}",
  color: "#ef4444",
  description: "Manages the cultivation and solicitation pipeline for major gifts, grants, and significant donor relationships. Opportunities represent open asks that move through customizable stages from Prospecting to Closed Won. Opportunity Contact Roles link multiple constituents to each opportunity with roles like Primary Donor, Influencer, or Decision Maker. This domain covers the front end of fundraising before gifts are formalized into commitments.",
  components: [
    {id:"opportunities",name:"Opportunities",icon:"\u{1F3AF}",desc:"Tracks major gift solicitations, grant proposals, and significant fundraising asks. Each opportunity moves through configurable stages with probability percentages, expected amounts, and close dates. Opportunities link to campaigns, accounts, and contacts, providing the cultivation pipeline view that development officers use to plan their outreach and track progress toward fundraising goals.",tags:["Opportunity"],connections:[{planet:"gift_commitments",desc:"Won opportunities become gift commitments"},{planet:"campaigns",desc:"Opportunities are sourced from campaigns"},{planet:"designations",desc:"Opportunities can have default gift designations"}]},
    {id:"opportunity-contact-roles",name:"Opportunity Contact Roles",icon:"\u{1F464}",desc:"Associates multiple constituents with an opportunity and defines each person's role in the solicitation. Roles include Primary Donor, Influencer, Decision Maker, Soft Credit Recipient, and custom roles. Contact Roles give fundraisers visibility into the network of people involved in a major gift and help track who contributed to winning the opportunity.",tags:["OpportunityContactRole"],connections:[{planet:"constituents",desc:"Contact roles reference person accounts"},{planet:"soft_credits",desc:"Contact roles inform soft credit attribution"}]},
    {id:"sales-processes",name:"Sales Processes",icon:"\u{1F4C8}",desc:"Defines the stage sequences that opportunities follow from identification to close. Different fundraising types can have different processes: major gifts may move through Identification, Cultivation, Solicitation, Negotiation, and Stewardship, while grants follow Prospecting, Proposal, Review, and Award stages. Each process maps to a record type on the Opportunity object.",tags:["Opportunity"],connections:[{planet:"setup",desc:"Sales processes are configured by admins"},{planet:"action_plans",desc:"Stage transitions can trigger action plans"}]},
    {id:"fundraising-analytics",name:"Fundraising Analytics",icon:"\u{1F4CA}",desc:"Provides high-level visibility into fundraising performance through dashboards and reports. Fundraising Strategy app gives executives a comprehensive view of pipeline health, gift totals, campaign ROI, and donor retention metrics. Data Processing Engine powers automated rollup calculations for designation totals and campaign performance.",tags:["Opportunity"],connections:[{planet:"campaigns",desc:"Analytics track campaign effectiveness"},{planet:"designations",desc:"Analytics show designation-level totals"}]}
  ],
  dataFlow:["Fundraiser identifies a prospective donor or grant opportunity","Opportunity record is created with expected amount and close date","Development officer cultivates the relationship through meetings and proposals","Opportunity moves through pipeline stages toward close","Won opportunity converts to a gift commitment or direct gift transaction"],
  connections:[{planet:"constituents",desc:"Donors are constituents"},{planet:"gift_commitments",desc:"Opportunities become commitments"},{planet:"gift_transactions",desc:"Opportunities produce transactions"},{planet:"campaigns",desc:"Campaigns source fundraising"},{planet:"designations",desc:"Opportunities have default designations"},{planet:"soft_credits",desc:"Opportunity contact roles drive soft credits"},{planet:"agentforce",desc:"AI generates gift proposals"},{planet:"action_plans",desc:"Action plans drive cultivation steps"},{planet:"setup",desc:"Fundraising settings in setup"},{planet:"grantmaking",desc:"Grants use the fundraising pipeline"}]
},

gift_commitments: {
  packages: ['nonprofitcloud'],
  name: "Gift Commitments",
  icon: "\u{1F4DD}",
  color: "#f97316",
  description: "Manages pledges, recurring donations, and multi-payment gift agreements. A Gift Commitment represents a donor's promise to give, while Gift Commitment Schedules define the installment frequency, amounts, and date ranges. Commitments support lifecycle operations including upgrades, downgrades, pauses, and resumptions, with the Change Attribution Log tracking every modification for accountability.",
  components: [
    {id:"commitment-records",name:"Commitment Records",icon:"\u{1F4DC}",desc:"The core object tracking a donor's commitment to give. Each record captures the commitment type (Recurring or Custom), status (Draft, Active, Paused, Lapsed, Failing, Closed), total amount, and links to the donor account, campaign, and opportunity. Automated processing flows update commitment status based on transaction payment patterns.",tags:["GiftCommitment"],connections:[{planet:"fundraising",desc:"Commitments originate from fundraising opportunities"},{planet:"gift_transactions",desc:"Commitments generate scheduled transactions"},{planet:"designations",desc:"Commitments inherit default designations"}]},
    {id:"commitment-schedules",name:"Commitment Schedules",icon:"\u{1F4C5}",desc:"Defines the installment pattern for a commitment: frequency (monthly, quarterly, annually), interval, day of month, effective start and end dates, and amount per installment. A single commitment can have multiple schedules to handle upgrades, payment method changes, and pause periods. Schedule processing automatically creates gift transactions for each upcoming installment.",tags:["GiftCommitmentSchedule"],connections:[{planet:"gift_transactions",desc:"Schedules trigger gift transaction creation"},{planet:"gift_entry",desc:"Gift entry can create new commitment schedules"}]},
    {id:"commitment-lifecycle",name:"Commitment Lifecycle",icon:"\u{1F504}",desc:"Manages the full lifecycle of recurring and pledged gifts. Donors can upgrade or downgrade commitment amounts, pause and resume schedules, change payment methods, and update effective dates. Each change triggers automated processing that adjusts future transactions and updates commitment status accordingly.",tags:["GiftCommitment","GiftCommitmentSchedule"],connections:[{planet:"gift_transactions",desc:"Lifecycle changes affect future transactions"},{planet:"campaigns",desc:"Upgrades can be attributed to campaigns"}]},
    {id:"change-attribution-log",name:"Change Attribution Log",icon:"\u{1F4D3}",desc:"Records every modification to a gift commitment for audit and attribution purposes. When a commitment is upgraded, downgraded, or otherwise changed, the log captures the change details, per-day amount impact, and the campaign or outreach source code that influenced the change. This enables accurate ROI calculation for campaigns that drive commitment upgrades.",tags:["GiftCommitmentChangeAttributionLog"],connections:[{planet:"campaigns",desc:"Changes are attributed to campaigns that influenced them"}]}
  ],
  dataFlow:["Donor agrees to a pledge or recurring gift commitment","Gift Commitment record is created with initial schedule","Automated processing creates gift transactions per the schedule","Donor requests changes which are tracked in the Change Attribution Log","Commitment status updates automatically based on payment patterns"],
  connections:[{planet:"fundraising",desc:"Opportunities become commitments"},{planet:"gift_transactions",desc:"Commitments generate transactions"},{planet:"gift_entry",desc:"Gift entry creates commitments"},{planet:"designations",desc:"Commitments allocated to designations"},{planet:"campaigns",desc:"Commitments attributed to campaigns"}]
},

gift_transactions: {
  packages: ['nonprofitcloud'],
  name: "Gift Transactions",
  icon: "\u{1F4B3}",
  color: "#ec4899",
  description: "Tracks every received gift and payment as a discrete transaction record. Gift Transactions represent one-time donations, installment payments against commitments, in-kind gifts, and matching gifts. Each transaction captures the amount, payment method, gift vehicle, received date, status, and acknowledgment tracking. Refund processing creates linked refund records to maintain a complete transaction history.",
  components: [
    {id:"transaction-records",name:"Transaction Records",icon:"\u{1F9FE}",desc:"The core object for tracking received gifts. Each transaction has a status lifecycle (Unpaid, Pending, Paid, Failed, Canceled, Refunded, Written Off), gift received date, amount, and payment method. Transactions link to the donor account, campaign, commitment, and outreach source code. The Gift Vehicle field distinguishes cash, check, credit card, stock, wire transfer, and in-kind gifts.",tags:["GiftTransaction"],connections:[{planet:"gift_commitments",desc:"Transactions fulfill commitment installments"},{planet:"designations",desc:"Transactions are allocated to designations"},{planet:"soft_credits",desc:"Transactions can have soft credit recipients"},{planet:"campaigns",desc:"Transactions attributed to campaigns"}]},
    {id:"payment-instruments",name:"Payment Instruments",icon:"\u{1F4B1}",desc:"Stores donor payment method information such as credit card last four digits, expiration dates, and ACH details. Payment Instrument records are linked to gift commitment schedules and enable tracking of which payment method is used for recurring donations. When donors change payment methods, new instrument records are created.",tags:["PaymentInstrument"],connections:[{planet:"gift_commitments",desc:"Payment instruments link to commitment schedules"}]},
    {id:"refund-processing",name:"Refund Processing",icon:"\u{1F501}",desc:"Creates refund records for full or partial gift returns. When a refund is issued, the original transaction status updates to reflect the refund, and a new linked refund record captures the returned amount and reason. Refund processing ensures complete transaction history for accounting and audit purposes.",tags:["GiftTransaction"],connections:[{planet:"designations",desc:"Refunds adjust designation allocation amounts"}]},
    {id:"acknowledgments",name:"Acknowledgments",icon:"\u{2709}",desc:"Tracks the acknowledgment status and date for gift transactions. After a gift is received and processed, the acknowledgment workflow ensures donors receive timely thank-you communications. Custom acknowledgment templates can be configured for different gift types, amounts, and donor segments.",tags:["GiftTransaction"],connections:[{planet:"constituents",desc:"Acknowledgments sent to donor accounts"},{planet:"campaigns",desc:"Campaign-specific acknowledgment templates"}]}
  ],
  dataFlow:["Gift is received via one-time payment, commitment installment, or batch entry","Gift Transaction record is created with amount, payment method, and donor","Transaction status progresses from Unpaid through Paid or Failed","Designation allocations and soft credits are applied to the transaction","Acknowledgment is tracked and sent to the donor"],
  connections:[{planet:"gift_commitments",desc:"Transactions fulfill commitments"},{planet:"gift_entry",desc:"Gift entry creates transactions"},{planet:"designations",desc:"Transactions linked to designations"},{planet:"soft_credits",desc:"Transactions have soft credits"},{planet:"campaigns",desc:"Transactions attributed to campaigns"},{planet:"constituents",desc:"Donors are constituent accounts"},{planet:"fundraising",desc:"Pipeline leads to transactions"}]
},

gift_entry: {
  packages: ['nonprofitcloud'],
  name: "Gift Entry & Processing",
  icon: "\u{1F4DD}",
  color: "#d946ef",
  description: "Provides efficient interfaces for recording and processing donations. The Gift Entry Window handles individual gifts with soft credits and designations in a single form. The Gift Entry Grid enables rapid batch entry of up to 200 gifts in a tabular format. Gift Batches group entries for bulk processing with validation, dry runs, and error handling. CSV Data Management supports importing large volumes of donation data.",
  components: [
    {id:"gift-entry-window",name:"Gift Entry Window",icon:"\u{1F5BC}",desc:"A single-form interface for creating individual gifts. Fundraising operations staff can enter a standalone gift, create a new gift commitment with its first transaction, or record a payment against an existing commitment. The form captures donor, amount, payment method, designations, and soft credits in one streamlined workflow.",tags:["GiftEntry"],connections:[{planet:"gift_transactions",desc:"Gift entry creates gift transaction records"},{planet:"gift_commitments",desc:"Gift entry can create new commitments"},{planet:"designations",desc:"Designations applied during entry"}]},
    {id:"gift-entry-grid",name:"Gift Entry Grid",icon:"\u{1F4CA}",desc:"A tabular data entry interface for rapidly creating multiple gifts. Supports up to 200 rows per session with configurable columns mapped to Gift Transaction, Account, Gift Commitment, and Gift Commitment Schedule fields. Custom templates control which fields appear and their display order for targeted entry experiences.",tags:["GiftEntry","GiftBatchTemplate"],connections:[{planet:"gift_transactions",desc:"Grid creates multiple gift transactions"},{planet:"constituents",desc:"Donors looked up or created during entry"}]},
    {id:"gift-batches",name:"Gift Batches",icon:"\u{1F4E6}",desc:"Groups gift entries for bulk processing. Each batch has an associated template, expected gift count, and estimated value for validation. Batch processing supports dry runs to test for errors before committing, and partially processed batches identify which entries failed. Gift Processing Status and Result fields provide per-entry feedback.",tags:["GiftBatch","GiftBatchTemplate"],connections:[{planet:"gift_transactions",desc:"Batch processing creates transactions in bulk"}]},
    {id:"csv-import",name:"CSV Data Import",icon:"\u{1F4C4}",desc:"Enables importing large volumes of donation data from external systems using CSV Data Management for Industries. Import files map to Gift Entry fields and are associated with a Gift Batch for processing. This supports annual fund drives, event registrations, and migration scenarios where hundreds or thousands of gifts need to be loaded efficiently.",tags:["GiftBatch","GiftEntry"],connections:[{planet:"gift_transactions",desc:"Imported entries become gift transactions after processing"}]}
  ],
  dataFlow:["Staff selects entry method: single gift window, grid, or CSV import","Donor information is entered or looked up from existing accounts","Gift details are captured: amount, payment method, commitment, designations","For batches, entries are validated with dry run before processing","Processing creates gift transactions and updates related records"],
  connections:[{planet:"gift_transactions",desc:"Gift entry creates transactions"},{planet:"gift_commitments",desc:"Gift entry creates and matches commitments"},{planet:"constituents",desc:"Donors entered or matched during gift entry"},{planet:"designations",desc:"Designations applied during entry"},{planet:"campaigns",desc:"Campaign and source code set during entry"},{planet:"agentforce",desc:"AI assists gift data entry"}]
},

designations: {
  packages: ['nonprofitcloud'],
  name: "Gift Designations",
  icon: "\u{1F3F7}",
  color: "#14b8a6",
  description: "Controls how donation amounts are allocated to specific funds and purposes. Gift Designations represent named funding buckets (e.g., General Fund, Scholarship Fund, Building Campaign) that donors can direct their gifts toward. Gift Transaction Designations link each payment to one or more designations with percentage-based allocation. A hierarchical inheritance system determines default designations from campaigns, commitments, opportunities, and the org-wide default.",
  components: [
    {id:"gift-designations",name:"Gift Designations",icon:"\u{1F4CB}",desc:"Named funding purposes that donors can direct their gifts toward. Each designation has an active status and can be set as the org-wide default for unrestricted gifts. Designation records accumulate rollup totals from linked gift transaction designations, providing real-time visibility into how much has been raised for each fund or purpose.",tags:["GiftDesignation"],connections:[{planet:"gift_transactions",desc:"Transactions are allocated to designations"},{planet:"campaigns",desc:"Campaigns can have default designations"},{planet:"fundraising",desc:"Opportunities link to designations"}]},
    {id:"transaction-designations",name:"Transaction Designations",icon:"\u{1F517}",desc:"Junction objects that link gift transactions to gift designations with a percentage or amount allocation. Each gift transaction can have up to 50 designation allocations. Transaction designations are the source of truth for updating gift designation rollup totals, enabling accurate impact reporting by fund.",tags:["GiftTransactionDesignation"],connections:[{planet:"gift_transactions",desc:"Each transaction can have multiple designation allocations"}]},
    {id:"default-designations",name:"Default Designations",icon:"\u{2B50}",desc:"Manages the inheritance hierarchy that automatically assigns designations to gifts. Default designations can be set at the campaign, commitment, opportunity, or org-wide level. When a gift is processed, the system checks each level in priority order and allocates unspecified amounts to the org-wide default designation. This ensures every dollar is tracked.",tags:["GiftDefaultDesignation"],connections:[{planet:"campaigns",desc:"Campaigns define default designations for sourced gifts"},{planet:"gift_commitments",desc:"Commitments inherit designations from opportunities and campaigns"},{planet:"gift_entry",desc:"Gift entry inherits default designations"}]},
    {id:"designation-reporting",name:"Designation Reporting",icon:"\u{1F4CA}",desc:"Provides rollup reporting and impact analysis by designation. Data Processing Engine calculates designation-level totals from transaction designation records. Reports show total raised, number of transactions, average gift size, and donor count for each designation, enabling fund managers to track progress toward campaign goals.",tags:["GiftDesignation"],connections:[{planet:"outcomes",desc:"Designation data supports impact and outcome reporting"}]}
  ],
  dataFlow:["Admin creates gift designations for each fund and purpose","One designation is set as the org-wide default for unrestricted gifts","Default designations are configured at campaign and commitment levels","During gift processing, amounts are allocated to designations via hierarchy","Rollup totals on designation records provide real-time fund balance visibility"],
  connections:[{planet:"gift_transactions",desc:"Transactions allocated to designations"},{planet:"gift_commitments",desc:"Commitments inherit designations"},{planet:"fundraising",desc:"Opportunities link to designations"},{planet:"campaigns",desc:"Campaigns have default designations"},{planet:"gift_entry",desc:"Gift entry applies designations"},{planet:"outcomes",desc:"Designation data feeds impact reporting"},{planet:"setup",desc:"DPE calculates designation rollups"}]
},

soft_credits: {
  packages: ['nonprofitcloud'],
  name: "Soft Credits",
  icon: "\u{1F31F}",
  color: "#a855f7",
  description: "Provides a unified attribution model for recognizing constituents who influenced or facilitated a gift without being the primary donor. Gift Soft Credit consolidates NPSP's multiple soft credit types (Partial Soft Credits, Account Soft Credits, Opportunity Contact Role credits) into a single, flexible object. Soft credits support individual, organizational, and partial attribution with customizable credit types.",
  components: [
    {id:"gift-soft-credits",name:"Gift Soft Credits",icon:"\u{2728}",desc:"Records attribution for constituents who influenced a donation. Each soft credit links to a gift transaction and a credited account (individual or organization) with a credit type such as Influence, Tribute, Solicitation, or Household Member. Partial amounts can be assigned when multiple people contributed to securing a gift. Soft credits drive donor recognition and stewardship reports.",tags:["GiftSoftCredit"],connections:[{planet:"gift_transactions",desc:"Soft credits are linked to gift transactions"},{planet:"constituents",desc:"Credits attributed to constituent accounts"},{planet:"relationships",desc:"Relationships inform soft credit decisions"}]},
    {id:"matching-gift-tracking",name:"Matching Gift Tracking",icon:"\u{1F91D}",desc:"Tracks employer matching programs where organizations match employee donations. The Matching Employer Transaction lookup on Gift Transaction links the original donation to the corporate match. This enables reporting on total giving impact including both direct and matched amounts.",tags:["GiftTransaction"],connections:[{planet:"gift_transactions",desc:"Matching transactions link to original gifts"},{planet:"constituents",desc:"Matching employers are organization accounts"}]},
    {id:"tribute-gifts",name:"Tribute & Memorial Gifts",icon:"\u{1F339}",desc:"Tracks gifts made in honor or memory of another person. Tribute honorees are recognized as soft credit recipients on the original donation. This supports donor acknowledgment workflows that notify both the donor and the honoree (or their family) about the tribute gift.",tags:["GiftSoftCredit"],connections:[{planet:"gift_transactions",desc:"Tribute gifts are recorded as transactions with soft credits"},{planet:"constituents",desc:"Honorees are constituent accounts"}]}
  ],
  dataFlow:["Gift is received and primary donor receives hard credit on the transaction","Staff identifies influencers, household members, or tribute honorees","Gift Soft Credit records are created linking credited constituents to the transaction","Matching gift transactions are linked to original donations via lookup","Soft credit totals roll up to constituent records for stewardship reporting"],
  connections:[{planet:"gift_transactions",desc:"Soft credits on transactions"},{planet:"constituents",desc:"Credits attributed to constituents"},{planet:"relationships",desc:"Relationships inform attribution"},{planet:"fundraising",desc:"Opportunity contact roles drive soft credits"}]
},

campaigns: {
  packages: ['nonprofitcloud'],
  name: "Campaigns & Outreach",
  icon: "\u{1F4E3}",
  color: "#3b82f6",
  description: "Manages fundraising campaigns and tracks donor outreach across channels. Nonprofit Cloud uses a flat campaign structure (no hierarchy rollups) with Outreach Source Codes providing granular tracking by channel, message, and audience. Campaigns attribute gifts, commitments, and opportunities to specific fundraising efforts, enabling ROI analysis and performance comparison across campaigns.",
  components: [
    {id:"campaign-management",name:"Campaign Management",icon:"\u{1F4CB}",desc:"Creates and manages fundraising campaigns with status tracking, budgets, expected revenue, and date ranges. Each campaign record serves as an attribution anchor for gift transactions, commitments, and opportunities. Campaign performance metrics aggregate from linked records, giving managers visibility into response rates and total raised.",tags:["Campaign"],connections:[{planet:"fundraising",desc:"Campaigns source fundraising opportunities"},{planet:"gift_transactions",desc:"Transactions attributed to campaigns"},{planet:"gift_commitments",desc:"Commitments linked to campaigns"}]},
    {id:"outreach-source-codes",name:"Outreach Source Codes",icon:"\u{1F4F1}",desc:"Child records of campaigns that provide granular tracking across channel, message, and audience combinations. Each source code captures which communication channel (email, direct mail, social, phone), which specific message or creative, and which audience segment was targeted. Gift transactions and commitments reference source codes for fine-grained attribution.",tags:["OutreachSourceCode"],connections:[{planet:"gift_transactions",desc:"Transactions attributed to specific source codes"},{planet:"gift_entry",desc:"Source codes set during gift entry"}]},
    {id:"campaign-attribution",name:"Campaign Attribution",icon:"\u{1F3AF}",desc:"Links donations and commitments back to the campaigns that generated them. Attribution flows from source codes to campaigns, enabling multi-level reporting. Campaign default designations automatically allocate gifts sourced from a campaign to the appropriate fund. Interest tags provide customer-defined categorization for campaign grouping and analysis.",tags:["Campaign","OutreachSourceCode"],connections:[{planet:"designations",desc:"Campaigns have default designations for sourced gifts"},{planet:"gift_commitments",desc:"Commitment changes attributed to campaigns"}]},
    {id:"campaign-performance",name:"Campaign Performance",icon:"\u{1F4C8}",desc:"Measures and reports on campaign effectiveness through metrics at both the campaign and source code levels. Performance data includes total raised, donor count, response rate, cost per dollar raised, and ROI. Source code-level analysis reveals which channels and messages drive the highest return, informing future campaign strategy.",tags:["Campaign"],connections:[{planet:"fundraising",desc:"Campaign data feeds fundraising strategy analytics"}]}
  ],
  dataFlow:["Admin creates campaign with budget, dates, and target audience","Outreach Source Codes are created for each channel, message, and audience combination","Communications go out with source code tracking identifiers","Donor responses are captured as gift entries with campaign and source code attribution","Performance metrics aggregate across campaigns for ROI reporting"],
  connections:[{planet:"fundraising",desc:"Campaigns source fundraising"},{planet:"gift_transactions",desc:"Transactions attributed to campaigns"},{planet:"gift_commitments",desc:"Commitments linked to campaigns"},{planet:"gift_entry",desc:"Source codes applied during entry"},{planet:"designations",desc:"Campaigns have default designations"},{planet:"households",desc:"Campaign mailings use household addressing"},{planet:"contact_points",desc:"Outreach uses contact information"},{planet:"action_plans",desc:"Campaigns trigger action plans"},{planet:"agentforce",desc:"AI provides campaign insights"},{planet:"setup",desc:"DPE aggregates campaign metrics"}]
},

programs: {
  packages: ['nonprofitcloud'],
  name: "Program Management",
  icon: "\u{1F4DA}",
  color: "#22c55e",
  description: "Tracks the services and programs your nonprofit delivers to constituents. Programs define structured offerings with benefits, schedules, and enrollment tracking. Benefit Types categorize services (training, counseling, distribution), while Benefit Disbursements track actual delivery of services to participants. Program Cohorts group enrollees for reporting and session management.",
  components: [
    {id:"program-records",name:"Programs",icon:"\u{1F3EB}",desc:"Defines the programs your organization offers. Each program record captures the name, summary, active status, and related benefits. Programs can represent educational initiatives, food distribution, housing assistance, job readiness, or any mission-driven service. Program-level reporting aggregates enrollment, attendance, and disbursement data.",tags:["Program"],connections:[{planet:"outcomes",desc:"Programs are measured by outcomes"},{planet:"case_management",desc:"Programs serve case participants"},{planet:"grantmaking",desc:"Grants fund programs"}]},
    {id:"benefits",name:"Benefits & Services",icon:"\u{1F381}",desc:"Defines the specific services or goods delivered by a program. Each benefit has a type (Coaching, Distribution, Training), unit of measure, and active status. Benefits link to schedules that define when and how often they are delivered. Benefit records accumulate disbursement data showing total service delivery volume.",tags:["Benefit","BenefitType","UnitOfMeasure"],connections:[{planet:"outcomes",desc:"Benefit delivery drives outcome measurement"}]},
    {id:"enrollment",name:"Program Enrollment",icon:"\u{1F4DD}",desc:"Tracks participant registration and status for each program. Enrollment records link constituents to programs with a status workflow (Applied, Enrolled, Completed, Withdrawn). Program Cohorts group enrollees for reporting, session management, and comparative analysis across participant groups.",tags:["ProgramEnrollment","ProgramCohort","ProgramCohortMember"],connections:[{planet:"constituents",desc:"Enrollees are constituent accounts"},{planet:"case_management",desc:"Case referrals lead to program enrollment"}]},
    {id:"benefit-disbursement",name:"Benefit Disbursement",icon:"\u{1F4E4}",desc:"Records the actual delivery of services and goods to participants. Each disbursement tracks the beneficiary, benefit, quantity delivered, date, and status. Ad hoc disbursements handle walk-in recipients not pre-enrolled. Attendance tracking on benefit sessions updates disbursement records for scheduled services.",tags:["BenefitDisbursement","BenefitSchedule","BenefitSession","BenefitAssignment"],connections:[{planet:"constituents",desc:"Disbursements go to participant accounts"},{planet:"outcomes",desc:"Disbursement data feeds outcome indicators"}]},
    {id:"goal-definitions",name:"Goal Definitions",icon:"\u{1F3C6}",desc:"Creates hierarchical goal structures that define desired outcomes for program participants. Top-level goals decompose into intermediate goals, creating a theory of change framework. Goals link to benefits and outcomes, enabling staff to track whether service delivery is translating into measurable impact.",tags:["GoalDefinition"],connections:[{planet:"outcomes",desc:"Goals connect to outcome definitions and indicators"},{planet:"case_management",desc:"Care plans reference goal definitions"}]}
  ],
  dataFlow:["Admin creates program with benefits, schedules, and goal definitions","Participants enroll in the program and are assigned to cohorts","Benefit sessions are scheduled and volunteers or staff deliver services","Disbursements are recorded tracking attendance and service delivery","Program data feeds outcome measurement and impact reporting"],
  connections:[{planet:"constituents",desc:"Participants are constituents"},{planet:"outcomes",desc:"Programs measured by outcomes"},{planet:"case_management",desc:"Programs serve case participants"},{planet:"grantmaking",desc:"Grants fund programs"},{planet:"volunteers",desc:"Volunteers support programs"},{planet:"action_plans",desc:"Action plans automate program steps"},{planet:"setup",desc:"Program settings in setup"},{planet:"agentforce",desc:"AI summarizes program benefits"}]
},

case_management: {
  packages: ['nonprofitcloud'],
  name: "Case Management",
  icon: "\u{1F4C2}",
  color: "#0ea5e9",
  description: "Equips case managers and social workers with tools for intake, assessment, and personalized care planning. Case Referral Intake handles inbound and outbound participant referrals, converting them to cases for follow-up. Care Plans provide structured, template-driven plans tailored to each participant's goals. Discovery Framework designs assessments, while Interaction Summaries capture detailed meeting notes.",
  components: [
    {id:"case-referral-intake",name:"Case Referral Intake",icon:"\u{1F4E5}",desc:"Processes inbound and outbound participant referrals using guided flows. Referrals can come from partner agencies, self-referral, or internal staff. The intake process captures participant information, presenting needs, and urgency, then converts referrals into cases for assessment and service assignment.",tags:["Case","CaseReferral"],connections:[{planet:"constituents",desc:"Referrals involve constituent records"},{planet:"programs",desc:"Referrals lead to program enrollment"}]},
    {id:"care-plans",name:"Care Plans",icon:"\u{1F4CB}",desc:"Creates personalized, goal-oriented plans for program participants. Care Plan Templates define standardized starting points with pre-configured benefits and goals. Case managers customize each plan to the participant's specific needs, adding or removing services, setting milestones, and tracking progress toward goals defined in the plan.",tags:["CarePlan","CarePlanTemplate","CarePlanTemplateBenefit","CarePlanTemplateGoal"],connections:[{planet:"programs",desc:"Care plans assign participants to program benefits"},{planet:"outcomes",desc:"Care plan goals link to outcome measurement"}]},
    {id:"assessments",name:"Assessments & Discovery",icon:"\u{1F50D}",desc:"Discovery Framework provides tools to design and administer structured assessments for program participants. Assessments evaluate needs during intake and throughout participation, generating scores and recommendations that inform care plan adjustments. Assessment results are stored as records linked to the participant's case.",tags:["AssessmentTask","DiscoveryFramework"],connections:[{planet:"constituents",desc:"Assessments are completed for participant accounts"}]},
    {id:"interaction-summaries",name:"Interaction Summaries",icon:"\u{1F4DD}",desc:"Captures detailed notes from meetings, conversations, and interactions with program participants, donors, caseworkers, and partners. Each summary includes the interaction type, date, participants, notes, and next steps. Confidentiality controls protect sensitive information. Notes are searchable and linked to the relevant account or case record.",tags:["InteractionSummary"],connections:[{planet:"constituents",desc:"Interaction notes linked to constituent accounts"},{planet:"agentforce",desc:"Einstein summarizes interaction notes"}]}
  ],
  dataFlow:["Referral is received and processed through intake flow","Case record is created and assessment is administered","Case manager creates a personalized care plan from a template","Participant receives services and progress is tracked via interaction summaries","Care plan goals are evaluated and adjusted based on assessment results"],
  connections:[{planet:"constituents",desc:"Cases involve constituents"},{planet:"programs",desc:"Cases lead to program enrollment"},{planet:"outcomes",desc:"Case outcomes tracked"},{planet:"agentforce",desc:"AI summarizes notes"},{planet:"action_plans",desc:"Action plans automate case steps"},{planet:"security",desc:"Case data requires access controls"},{planet:"setup",desc:"Case settings in setup"}]
},

outcomes: {
  packages: ['nonprofitcloud'],
  name: "Outcome Management",
  icon: "\u{1F4C8}",
  color: "#84cc16",
  description: "Defines, measures, and evaluates the impact of your programs using a structured theory of change framework. Outcome Definitions describe the intended results, Indicators specify how to measure progress, and Indicator Results capture actual data points over time. Outcome Management links to programs and benefits, enabling nonprofits to demonstrate impact to donors, boards, and grant funders.",
  components: [
    {id:"outcome-definitions",name:"Outcome Definitions",icon:"\u{1F3AF}",desc:"Describes the intended impact or change your programs aim to achieve. Each outcome definition articulates what success looks like, the target population, and the timeframe. Outcomes form a hierarchy that maps your theory of change from activities to outputs to ultimate impact goals.",tags:["OutcomeDefinition"],connections:[{planet:"programs",desc:"Outcomes link to the programs that drive them"},{planet:"grantmaking",desc:"Outcomes demonstrate impact to grant funders"}]},
    {id:"indicators",name:"Indicators",icon:"\u{1F4CF}",desc:"Defines the specific metrics used to measure progress toward outcomes. Each indicator specifies what to measure, the data collection method, frequency, and target values. Indicators can be quantitative (number of participants employed) or qualitative (participant satisfaction score), and they link to outcome definitions to create a complete measurement framework.",tags:["Indicator"],connections:[{planet:"programs",desc:"Indicators measure program activities and benefits"}]},
    {id:"indicator-results",name:"Indicator Results",icon:"\u{1F4CA}",desc:"Captures actual measurement data points for each indicator over time. Results record the measurement date, value, and collection context. Trending indicator results over time reveals whether programs are achieving their intended outcomes, and where adjustments are needed to improve effectiveness.",tags:["IndicatorResult"],connections:[{planet:"programs",desc:"Results are collected from program activities"}]},
    {id:"impact-reporting",name:"Impact Reporting",icon:"\u{1F4D1}",desc:"Generates reports and dashboards that demonstrate program effectiveness to stakeholders. Impact reports compile outcome data, indicator trends, and program metrics into narratives suitable for board presentations, donor stewardship, grant reporting, and regulatory compliance. Reports can be scoped by program, cohort, timeframe, or funding source.",tags:["OutcomeDefinition","Indicator"],connections:[{planet:"grantmaking",desc:"Impact reports support grant reporting requirements"},{planet:"designations",desc:"Designation-level impact reporting for donors"}]}
  ],
  dataFlow:["Admin defines outcome strategy with outcome definitions and indicators","Programs and benefits are linked to the outcomes they drive","Staff collects indicator data through assessments and program tracking","Indicator results are analyzed to evaluate program effectiveness","Impact reports are generated for donors, boards, and funders"],
  connections:[{planet:"programs",desc:"Programs measured by outcomes"},{planet:"case_management",desc:"Case outcomes tracked"},{planet:"grantmaking",desc:"Outcomes support grant reporting"},{planet:"designations",desc:"Impact reporting by designation"}]
},

volunteers: {
  packages: ['nonprofitcloud'],
  name: "Volunteer Management",
  icon: "\u{1F9D1}\u{200D}\u{1F91D}\u{200D}\u{1F9D1}",
  color: "#eab308",
  description: "Streamlines the end-to-end volunteer lifecycle from recruitment to hour tracking and reporting. Volunteer Initiatives define projects, Positions describe generic roles, and Job Positions customize those roles for specific initiatives with shifts, qualifications, and location requirements. Smart matching finds the most qualified volunteers based on competencies, availability, and location. Experience Cloud integration enables self-service volunteer portals.",
  components: [
    {id:"volunteer-initiatives",name:"Volunteer Initiatives",icon:"\u{1F3C1}",desc:"Defines volunteer projects and events with start/end dates, headcount goals, and total hours targets. Initiatives support parent-child hierarchies for large programs with sub-initiatives. Each initiative is staffed by job positions with specified shifts. Published initiatives appear on Experience Cloud volunteer portals for self-service signup.",tags:["VolunteerInitiative"],connections:[{planet:"programs",desc:"Volunteer initiatives support program delivery"},{planet:"action_plans",desc:"Action plans automate initiative setup tasks"}]},
    {id:"positions-job-positions",name:"Positions & Job Positions",icon:"\u{1F464}",desc:"Positions define generic volunteer roles (Tutor, Group Leader, Event Coordinator). Job Positions customize those roles for specific initiatives with shift schedules, location, qualifications, and approval requirements. A Position can be used across multiple initiatives, while each Job Position is specific to one initiative.",tags:["Position","JobPosition"],connections:[{planet:"programs",desc:"Positions align with program service delivery needs"}]},
    {id:"shifts-assignments",name:"Shifts & Assignments",icon:"\u{1F4C5}",desc:"Job Position Shifts define specific work periods with start/end times, recurrence schedules, and capacity limits. Job Position Assignments link volunteers to shifts with status tracking (Upcoming, In Progress, Completed). Shift management supports recurring schedules and tracks filled vs. open capacity.",tags:["JobPositionShift","JobPositionAssignment"],connections:[{planet:"constituents",desc:"Volunteers assigned to shifts are constituent accounts"}]},
    {id:"volunteer-matching",name:"Volunteer Matching",icon:"\u{1F50D}",desc:"Uses smart matching criteria to find the most qualified volunteers for open shifts. Matching considers person competencies, examination results, location availability, and schedule overlap. Volunteers who meet position qualifications and are available during shift times surface as recommended candidates.",tags:["PersonCompetency","PersonExamination","PersonLocationAvailability","Competency","Examination"],connections:[{planet:"constituents",desc:"Matching evaluates volunteer profiles"}]},
    {id:"volunteer-portal",name:"Volunteer Portal",icon:"\u{1F310}",desc:"An Experience Cloud site where volunteers can browse published initiatives, view position details, sign up for shifts, complete onboarding forms, upload documentation, and track their volunteer hours. Guest access enables prospective volunteers to explore opportunities before creating an account.",tags:["VolunteerInitiative"],connections:[{planet:"constituents",desc:"Portal creates or links to volunteer accounts"},{planet:"agentforce",desc:"AI agent assists volunteer portal users"}]}
  ],
  dataFlow:["Admin creates volunteer initiative with positions and job positions","Qualifications are defined and shifts are scheduled for each job position","Volunteer matching identifies candidates based on competencies and availability","Volunteers sign up through the portal or are assigned by staff","Hours are tracked through shift assignment status and reported on"],
  connections:[{planet:"constituents",desc:"Volunteers are constituents"},{planet:"programs",desc:"Volunteers support programs"},{planet:"action_plans",desc:"Action plans automate volunteer onboarding"},{planet:"agentforce",desc:"AI assists volunteer matching"},{planet:"setup",desc:"Volunteer settings in setup"}]
},

grantmaking: {
  packages: ['nonprofitcloud'],
  name: "Grantmaking",
  icon: "\u{1F4B5}",
  color: "#f43f5e",
  description: "Streamlines the grant management process for organizations that fund other nonprofits or community projects. Grantmaking provides tools to create funding opportunities, manage applications and reviews, approve budgets, and track grant disbursements. Experience Cloud portals enable grant seekers to discover opportunities, submit applications, and upload supporting documents. Works with Program Management and Outcome Management for impact tracking.",
  components: [
    {id:"funding-opportunities",name:"Funding Opportunities",icon:"\u{1F4E2}",desc:"Creates and publishes grant opportunities that applicants can discover and apply for. Each opportunity includes eligibility criteria, application deadlines, available funding amount, and required documentation. Published opportunities appear on Experience Cloud portals for external applicant access.",tags:["FundingOpportunity"],connections:[{planet:"programs",desc:"Funding opportunities support specific programs"},{planet:"outcomes",desc:"Grant opportunities specify outcome requirements"}]},
    {id:"grant-applications",name:"Grant Applications",icon:"\u{1F4DD}",desc:"Manages the full lifecycle of grant applications from submission through review to award or decline. Applications capture applicant information, proposed budget, project narrative, and supporting documents. Multi-stage review workflows route applications through internal evaluators with scoring and comments.",tags:["GrantApplication","ApplicationReview"],connections:[{planet:"constituents",desc:"Applicants are organization accounts"},{planet:"agentforce",desc:"AI generates board-ready summaries of applications"}]},
    {id:"grant-budgets",name:"Grant Budgets & Awards",icon:"\u{1F4B0}",desc:"Tracks proposed and approved budgets for grant applications, then manages award disbursements. Budget line items categorize spending by program activity, personnel, overhead, and direct costs. Award records track disbursement schedules and actual payments to grantees.",tags:["Budget","FundingAward"],connections:[{planet:"fundraising",desc:"Inbound grants use the fundraising pipeline"},{planet:"programs",desc:"Awards fund specific program activities"}]},
    {id:"grantee-portal",name:"Grantee Portal",icon:"\u{1F310}",desc:"An Experience Cloud site where grant seekers discover funding opportunities, submit applications, upload documentation, track application status, and report on funded activities. The portal streamlines communication between grantmakers and grantees throughout the grant lifecycle.",tags:["FundingOpportunity","GrantApplication"],connections:[{planet:"outcomes",desc:"Grantees report outcomes through the portal"}]}
  ],
  dataFlow:["Admin creates funding opportunities with eligibility criteria and deadlines","Applicants discover opportunities and submit applications through the portal","Internal reviewers evaluate applications and score proposals","Approved applications receive budget approval and funding awards","Grantees report on outcomes and impact of funded activities"],
  connections:[{planet:"fundraising",desc:"Inbound grants use the fundraising pipeline"},{planet:"programs",desc:"Grants fund programs"},{planet:"outcomes",desc:"Grants measured by outcomes"},{planet:"constituents",desc:"Applicants are organization accounts"},{planet:"agentforce",desc:"AI summarizes grant applications"},{planet:"relationships",desc:"Organization relationships inform grants"},{planet:"action_plans",desc:"Action plans support grant review workflows"}]
},

agentforce: {
  packages: ['nonprofitcloud'],
  name: "Agentforce & Einstein AI",
  icon: "\u{1F916}",
  color: "#6366f1",
  description: "Brings generative AI and conversational AI capabilities to Nonprofit Cloud. Einstein Copilot generates draft gift proposals for major donors using your Salesforce data. Einstein Generative AI produces summaries of program benefits, interaction notes, and grant applications for board review. Agentforce provides AI agents that streamline fundraising, volunteer management, and program operations workflows.",
  components: [
    {id:"gift-proposals",name:"AI Gift Proposals",icon:"\u{1F4DD}",desc:"Einstein Copilot generates personalized gift proposals for major donors by analyzing the donor's giving history, interests, and relationship with your organization. Major gift officers provide prompts and Einstein drafts compelling proposals that showcase impact and align with the donor's philanthropic priorities. This accelerates the cultivation process for high-net-worth donors.",tags:[],connections:[{planet:"fundraising",desc:"Gift proposals support major gift solicitations"},{planet:"constituents",desc:"Proposals personalized based on donor data"}]},
    {id:"ai-summaries",name:"Einstein Summaries",icon:"\u{1F4CB}",desc:"Generates AI-powered summaries across multiple Nonprofit Cloud areas. Summarize Program and Benefits condenses program details for stakeholder communications. Summarize Notes creates concise recaps from lengthy interaction summaries. Board Version of Grant Application produces streamlined grant summaries for board review. Each summary uses Einstein generative AI with your org's data.",tags:[],connections:[{planet:"programs",desc:"AI summarizes program benefits"},{planet:"case_management",desc:"AI summarizes interaction notes"},{planet:"grantmaking",desc:"AI creates board-ready grant summaries"}]},
    {id:"volunteer-agent",name:"Volunteer AI Agent",icon:"\u{1F9D1}\u{200D}\u{1F4BB}",desc:"An Agentforce agent that assists with volunteer management processes. The agent helps match volunteers to open positions based on qualifications, automates onboarding communications, and answers volunteer questions through the Experience Cloud portal. Beta feature that requires the Use Volunteer Agent permission set.",tags:[],connections:[{planet:"volunteers",desc:"AI agent assists volunteer operations"}]},
    {id:"fundraising-agent",name:"Fundraising AI Agent",icon:"\u{1F4B0}",desc:"Agentforce capabilities for fundraising operations including automated data entry assistance, donor communication drafting, and campaign performance insights. AI agents help fundraising staff work more efficiently by handling routine tasks and providing data-driven recommendations.",tags:[],connections:[{planet:"campaigns",desc:"AI provides campaign performance insights"},{planet:"gift_entry",desc:"AI assists with gift data entry"}]}
  ],
  dataFlow:["Admin enables Einstein Generative AI and assigns Copilot permission sets","Einstein Summary components are added to program, account, and grantmaking page layouts","Major gift officers request AI-generated gift proposals through Copilot","Staff uses Einstein summaries to quickly review programs, notes, and applications","Agentforce agents automate routine tasks and assist portal users"],
  connections:[{planet:"fundraising",desc:"AI generates gift proposals"},{planet:"programs",desc:"AI summarizes programs"},{planet:"case_management",desc:"AI summarizes notes"},{planet:"grantmaking",desc:"AI summarizes grants"},{planet:"volunteers",desc:"AI assists volunteer matching"},{planet:"campaigns",desc:"AI provides campaign insights"},{planet:"gift_entry",desc:"AI assists gift entry"}]
},

action_plans: {
  packages: ['nonprofitcloud'],
  name: "Action Plans",
  icon: "\u{2705}",
  color: "#fb923c",
  description: "Automates multi-step task sequences using template-driven action plans. Action Plans replace NPSP's Engagement Plans with the Salesforce platform's standard Action Plan feature. Templates define required tasks with assignees, due date offsets, and dependencies. Plans can be applied to volunteers, programs, fundraising opportunities, and cases, ensuring consistent process execution across the organization.",
  components: [
    {id:"action-plan-templates",name:"Action Plan Templates",icon:"\u{1F4CB}",desc:"Defines reusable sequences of tasks for common business processes. Each template specifies the task name, description, default assignee, priority, days until due, and task dependencies. Templates can be created for donor stewardship (thank-you call, follow-up meeting, proposal), volunteer onboarding (background check, training, orientation), or program enrollment steps.",tags:["ActionPlanTemplate","ActionPlanTemplateItem"],connections:[{planet:"programs",desc:"Templates automate program enrollment workflows"},{planet:"volunteers",desc:"Templates automate volunteer onboarding"},{planet:"fundraising",desc:"Templates drive cultivation step sequences"}]},
    {id:"action-plan-execution",name:"Action Plan Execution",icon:"\u{26A1}",desc:"Creates action plan instances from templates and manages task completion. When an action plan is applied to a record (opportunity, initiative, case), the system generates tasks with calculated due dates and assignments. Task dependencies ensure steps execute in the correct order. Completion tracking shows overall plan progress.",tags:["ActionPlan","ActionPlanItem"],connections:[{planet:"case_management",desc:"Action plans automate case management workflows"}]},
    {id:"stage-management",name:"Stage Management",icon:"\u{1F4CA}",desc:"Tracks lifecycle stages for key objects using a configurable stage framework. Stage Management can be applied to Volunteer Initiatives, Job Positions, Job Position Assignments, Job Position Shifts, Positions, and Application Forms. Each stage configuration defines the progression path and can trigger action plans at stage transitions.",tags:["StageDefinition"],connections:[{planet:"volunteers",desc:"Stages track volunteer initiative and assignment progress"},{planet:"grantmaking",desc:"Stages track application review progress"}]}
  ],
  dataFlow:["Admin creates action plan templates for common processes","Staff applies a template to a record (opportunity, case, initiative)","System generates tasks with calculated due dates and assignments","Tasks are completed in sequence following dependency rules","Stage transitions trigger additional action plans as needed"],
  connections:[{planet:"fundraising",desc:"Action plans drive cultivation"},{planet:"programs",desc:"Action plans automate program steps"},{planet:"case_management",desc:"Action plans automate case workflows"},{planet:"volunteers",desc:"Action plans automate volunteer tasks"},{planet:"campaigns",desc:"Campaign actions trigger plans"},{planet:"grantmaking",desc:"Action plans support grant review workflows"}]
},

security: {
  packages: ['nonprofitcloud'],
  name: "Security & Access",
  icon: "\u{1F512}",
  color: "#64748b",
  description: "Manages licensing, permissions, and data access controls for Nonprofit Cloud. Permission Set Groups replace NPSP's fragmented permission model with consolidated feature access bundles. Key permission sets include FundraisingAccess, Advanced Program Management, Outcome Management, Grantmaking Manager, and Manage Volunteer Data. Organization-wide sharing defaults and field-level security protect sensitive donor and participant information.",
  components: [
    {id:"permission-set-groups",name:"Permission Set Groups",icon:"\u{1F511}",desc:"Bundles multiple permission sets into manageable groups for role-based access. Nonprofit Cloud uses permission set groups to grant users access to specific product areas: fundraising operations, donor engagement, philanthropy, program management, and grantmaking. This approach is cleaner than NPSP's per-package permission model.",tags:["PermissionSetGroup"],connections:[{planet:"setup",desc:"Permission sets configured in Salesforce setup"}]},
    {id:"permission-set-licenses",name:"Permission Set Licenses",icon:"\u{1F4DC}",desc:"Controls which Nonprofit Cloud features are available in your org. Each product area (Fundraising, Program Management, Volunteer Management, Grantmaking) has associated permission set licenses that extend the base platform capabilities. Licenses are assigned to users before permission sets can take effect.",tags:["PermissionSetLicense"],connections:[{planet:"setup",desc:"Licenses managed in setup"}]},
    {id:"data-security",name:"Data Security & Privacy",icon:"\u{1F6E1}",desc:"Protects sensitive constituent information through organization-wide sharing defaults, field-level security, and role hierarchies. Identity Verification features prevent unauthorized access to participant data. GDPR-compliant contact point objects support data privacy requirements. Interaction Summary confidentiality controls limit access to sensitive case notes.",tags:[],connections:[{planet:"case_management",desc:"Case data requires strict access controls"},{planet:"constituents",desc:"Donor and participant data is protected"}]},
    {id:"muting-permission-sets",name:"Custom & Muting Permission Sets",icon:"\u{1F507}",desc:"Enables granular permission customization without modifying default sets. Muting permission sets remove specific permissions from the default bundle, while custom permission sets add organization-specific access. Combined through permission set groups, this approach ensures users get exactly the access they need while maintaining upgrade compatibility.",tags:["PermissionSetGroup"],connections:[{planet:"setup",desc:"Custom permissions configured by admins"}]}
  ],
  dataFlow:["Admin assigns Nonprofit Cloud permission set licenses to users","Permission set groups are configured for each functional role","Field-level security and sharing rules protect sensitive data","Muting permission sets remove unnecessary access for specific roles","Users receive exactly the permissions needed for their job function"],
  connections:[{planet:"setup",desc:"Permissions configured in setup"},{planet:"constituents",desc:"Data security protects constituent records"},{planet:"case_management",desc:"Case data access controlled"}]
},

setup: {
  packages: ['nonprofitcloud'],
  name: "Setup & Configuration",
  icon: "\u{2699}",
  color: "#78716c",
  description: "Central hub for configuring all Nonprofit Cloud features. Setup covers enabling product features (Fundraising, Program Management, Volunteer Management, Grantmaking, Outcome Management), configuring fundraising settings (installment processing, lapsed/failing thresholds), managing picklist values, record types, and sales processes. Data Processing Engine configuration powers automated rollup calculations across the platform.",
  components: [
    {id:"feature-enablement",name:"Feature Enablement",icon:"\u{1F504}",desc:"Turns on Nonprofit Cloud product areas through Setup menus. Each feature (Fundraising, Program Management, Volunteer Management, Grantmaking, Outcome Management, Einstein AI) has its own setup page with toggle controls. Features should be enabled in a sandbox first, as some cannot be disabled once turned on.",tags:[],connections:[{planet:"programs",desc:"Program Management enabled in setup"},{planet:"volunteers",desc:"Volunteer Management enabled in setup"},{planet:"grantmaking",desc:"Grantmaking enabled in setup"}]},
    {id:"fundraising-settings",name:"Fundraising Settings",icon:"\u{1F4B0}",desc:"Configures core fundraising behavior including Gift Entry settings, Installment Extension Day Count (window for matching transactions to commitments), Lapsed Unpaid Transaction Count (threshold for lapsed status), Failing Transaction Count (threshold for failing status), and auto-close behavior for recurring commitments.",tags:[],connections:[{planet:"gift_commitments",desc:"Processing thresholds affect commitment status"},{planet:"gift_entry",desc:"Gift entry settings configured here"}]},
    {id:"data-processing-engine",name:"Data Processing Engine",icon:"\u{2699}",desc:"Salesforce's batch data transformation tool that powers automated rollup calculations in Nonprofit Cloud. DPE processes data in your org and writes results to create or update records. In Nonprofit Cloud, it generates rollup field data for both fundraising (designation totals, campaign metrics) and program management (enrollment counts, disbursement totals).",tags:[],connections:[{planet:"designations",desc:"DPE calculates designation rollup totals"},{planet:"campaigns",desc:"DPE aggregates campaign performance metrics"}]},
    {id:"picklists-record-types",name:"Picklists & Record Types",icon:"\u{1F3F7}",desc:"Configures picklist values and record types that customize Nonprofit Cloud behavior. Key picklists include Payment Method, Gift Vehicle, Commitment Type, Relationship Role, Campaign Type, and Benefit Type. Record types on Opportunity enable different sales processes for major gifts, grants, and planned giving.",tags:[],connections:[{planet:"fundraising",desc:"Opportunity record types define fundraising processes"},{planet:"relationships",desc:"Relationship role picklists configured here"}]}
  ],
  dataFlow:["Admin enables desired Nonprofit Cloud features in Setup","Fundraising settings are configured for commitment processing behavior","Picklist values and record types are customized for the organization","Data Processing Engine is configured for rollup calculations","Permission sets and security settings are assigned to users"],
  connections:[{planet:"fundraising",desc:"Fundraising settings"},{planet:"programs",desc:"Program settings"},{planet:"volunteers",desc:"Volunteer settings"},{planet:"case_management",desc:"Case settings"},{planet:"security",desc:"Permissions configured in setup"},{planet:"constituents",desc:"Account model configured"},{planet:"relationships",desc:"Relationship types configured"},{planet:"designations",desc:"DPE calculates rollups"},{planet:"campaigns",desc:"DPE aggregates metrics"}]
}

};
