export default {

  "constituents": {
    "objects": [
      {"name":"Account","type":"standard","domain":"constituents","description":"Account is the central constituent record for individuals represented as Person Accounts and for organizations, households, or other groups represented as Business Accounts. Name and RecordTypeId identify the record and its account model, while ParentId, Type, BillingAddress, and Phone support hierarchy, classification, address, and contact details.","fields":[{"name":"Name","type":"Text","description":"Account name; auto-populated from first/last name for Person Accounts"},{"name":"RecordTypeId","type":"Lookup","description":"Distinguishes Person Accounts from Business Accounts"},{"name":"ParentId","type":"Lookup","description":"Parent account for modeling organizational hierarchies"},{"name":"Type","type":"Picklist","description":"Account classification such as Donor, Foundation, Partner, or Vendor"},{"name":"BillingAddress","type":"Text","description":"Primary billing address compound field"},{"name":"Phone","type":"Phone","description":"Primary phone number for the account"}],"relationships":[{"target":"Contact","type":"parent","description":"Person Accounts have an associated Contact record that stores individual-specific fields"},{"target":"ContactProfile","type":"parent","description":"Accounts can have a Contact Profile with extended fundraising attributes"},{"target":"AccountContactRelation","type":"parent","description":"Accounts are linked to contacts through Account Contact Relationships for household and organizational membership"},{"target":"ContactPointAddress","type":"parent","description":"Accounts have one or more contact point addresses"}]},
      {"name":"Contact","type":"standard","domain":"constituents","description":"Contact stores an individual associated with an Account, including FirstName, LastName, Email, and Birthdate. AccountId links the Contact to the applicable Business Account in account models that use contacts with organizations.","fields":[{"name":"FirstName","type":"Text","description":"Individual's first name"},{"name":"LastName","type":"Text","description":"Individual's last name"},{"name":"Email","type":"Email","description":"Primary email address"},{"name":"Birthdate","type":"Date","description":"Date of birth for age-based segmentation and reporting"},{"name":"AccountId","type":"Lookup","description":"The Account this Contact is associated with"}],"relationships":[{"target":"Account","type":"child","description":"Each Contact belongs to an Account; for Person Accounts this is a one-to-one relationship"},{"target":"ContactContactRelation","type":"parent","description":"Contacts participate in interpersonal relationships"},{"target":"OpportunityContactRole","type":"parent","description":"Contacts are linked to fundraising opportunities through contact roles"}]},
      {"name":"ContactProfile","type":"standard","domain":"constituents","description":"ContactProfile stores fundraising-specific information related to a constituent Account. Name and AccountId identify and associate the profile, while DonorClassification and RecurringDonorType capture donor attributes used by fundraising processes.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated profile identifier"},{"name":"AccountId","type":"Lookup","description":"The constituent account this profile extends"},{"name":"RecurringDonorType","type":"Picklist","description":"Indicates whether the constituent is a sustaining, lapsed, or prospective recurring donor"}],"relationships":[{"target":"Account","type":"child","description":"Each Contact Profile belongs to a single constituent account"}]}
    ]
  },

  "households": {
    "objects": [
      {"name":"PartyRelationshipGroup","type":"standard","domain":"households","description":"PartyRelationshipGroup represents a named household or other group associated with an account. Its Type, StartDate, and EndDate fields classify the group and define the period during which it applies.","fields":[{"name":"Name","type":"Text","description":"Display name for the group, often the household surname"},{"name":"Type","type":"Picklist","description":"Group classification such as Household, Affinity Group, or Board"},{"name":"AccountId","type":"Lookup","description":"The Business Account that represents this group"},{"name":"StartDate","type":"Date","description":"Date when the group was established"},{"name":"EndDate","type":"Date","description":"Date when the group was dissolved, if applicable"}],"relationships":[{"target":"Account","type":"child","description":"Each group is represented by a Business Account"},{"target":"AccountContactRelation","type":"parent","description":"Group membership is tracked through Account Contact Relationship records"}]},
      {"name":"AccountContactRelation","type":"standard","domain":"households","description":"AccountContactRelationship connects a contact to an account for household or other group membership. Roles, IsActive, StartDate, and EndDate describe the member’s participation and the period for which the relationship applies.","fields":[{"name":"AccountId","type":"Lookup","description":"The organization or group account"},{"name":"ContactId","type":"Lookup","description":"The individual contact being linked to the account"},{"name":"Roles","type":"MultiPicklist","description":"One or more roles the individual holds in the organization (Head of Household, Member, Board Member)"},{"name":"IsActive","type":"Checkbox","description":"Whether the relationship is currently active"},{"name":"StartDate","type":"Date","description":"Date when the relationship began"},{"name":"EndDate","type":"Date","description":"Date when the relationship ended, if applicable"}],"relationships":[{"target":"Account","type":"child","description":"Each ACR links to the organization or group account"},{"target":"Contact","type":"child","description":"Each ACR links to the individual contact"},{"target":"PartyRelationshipGroup","type":"lookup","description":"ACRs connect individuals to Party Relationship Group households"}]}
    ]
  },

  "relationships": {
    "objects": [
      {"name":"ContactContactRelation","type":"standard","domain":"relationships","description":"ContactContactRelationship connects the contact in ContactId with the contact in RelatedContactId and uses RoleId to describe their relationship. Name identifies the record, while IsActive and StartDate indicate whether the connection is current and when it began.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated relationship identifier"},{"name":"ContactId","type":"Lookup","description":"The first individual in the relationship"},{"name":"RelatedContactId","type":"Lookup","description":"The second individual in the relationship"},{"name":"PartyRoleRelationId","type":"Lookup","description":"The Party Role Relationship defining the type (e.g., Spouse, Parent)"},{"name":"IsActive","type":"Checkbox","description":"Whether the relationship is currently active"},{"name":"StartDate","type":"Date","description":"Date when the relationship began"}],"relationships":[{"target":"Contact","type":"child","description":"Links to the first individual in the relationship"},{"target":"PartyRoleRelation","type":"child","description":"References the party role that defines the relationship type and reciprocal labels"}]},
      {"name":"AccountAccountRelation","type":"standard","domain":"relationships","description":"AccountAccountRelationship connects the account in AccountId with the account in RelatedAccountId and uses RoleId to classify the connection. Name identifies the record, and IsActive indicates whether the relationship is current.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated relationship identifier"},{"name":"AccountId","type":"Lookup","description":"The first organization in the relationship"},{"name":"RelatedAccountId","type":"Lookup","description":"The second organization in the relationship"},{"name":"PartyRoleRelationId","type":"Lookup","description":"The Party Role Relationship defining the relationship type"},{"name":"IsActive","type":"Checkbox","description":"Whether the organizational relationship is currently active"}],"relationships":[{"target":"Account","type":"child","description":"Links to the first organization account"},{"target":"PartyRoleRelation","type":"child","description":"References the party role defining the relationship type"}]},
      {"name":"PartyRoleRelation","type":"standard","domain":"relationships","description":"PartyRoleRelationship defines an available relationship role using Name, ReciprocalLabel, and RelationshipType. IsActive indicates whether the definition is available for use with relationship records.","fields":[{"name":"Name","type":"Text","description":"Forward-direction label for the relationship (e.g., Parent)"},{"name":"RelatedRoleName","type":"Text","description":"Reverse-direction label (e.g., Child)"}],"relationships":[{"target":"ContactContactRelation","type":"parent","description":"Party roles are used by Contact Contact Relationships"},{"target":"AccountAccountRelation","type":"parent","description":"Party roles are used by Account Account Relationships"}]}
    ]
  },

  "contact_points": {
    "objects": [
      {"name":"ContactPointAddress","type":"standard","domain":"contact_points","description":"ContactPointAddress stores a named address associated with an account through ParentId. It records the address type, street, city, state, postal code, and country, while IsPrimary identifies the account's primary address.","fields":[{"name":"Name","type":"Text","description":"Display label for this address record"},{"name":"ParentId","type":"Lookup","description":"The Account this address belongs to (polymorphic)"},{"name":"AddressType","type":"Picklist","description":"Classification such as Home, Work, Vacation, or Other"},{"name":"Street","type":"TextArea","description":"Street address lines"},{"name":"City","type":"Text","description":"City name"},{"name":"StateCode","type":"Picklist","description":"State or province code"},{"name":"PostalCode","type":"Text","description":"Postal or ZIP code"},{"name":"CountryCode","type":"Picklist","description":"Country code"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the preferred mailing address"}],"relationships":[{"target":"Account","type":"child","description":"Each address belongs to a constituent account"}]},
      {"name":"ContactPointEmail","type":"standard","domain":"contact_points","description":"ContactPointEmail stores a named email address associated with an account through ParentId. EmailType classifies the address, and IsPrimary identifies the primary email record.","fields":[{"name":"Name","type":"Text","description":"Display label for this email record"},{"name":"ParentId","type":"Lookup","description":"The Account this email belongs to (polymorphic)"},{"name":"EmailAddress","type":"Email","description":"The email address"},{"name":"UsageType","type":"Picklist","description":"Classification such as Personal, Work, or Other"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the preferred email address"}],"relationships":[{"target":"Account","type":"child","description":"Each email belongs to a constituent account"}]},
      {"name":"ContactPointPhone","type":"standard","domain":"contact_points","description":"ContactPointPhone stores a named telephone number associated with an account through ParentId. PhoneType classifies the number, and IsPrimary identifies the primary phone record.","fields":[{"name":"Name","type":"Text","description":"Display label for this phone record"},{"name":"ParentId","type":"Lookup","description":"The Account this phone number belongs to (polymorphic)"},{"name":"TelephoneNumber","type":"Phone","description":"The phone number"},{"name":"PhoneType","type":"Picklist","description":"Classification such as Home, Mobile, Work, or Fax"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the preferred phone number"}],"relationships":[{"target":"Account","type":"child","description":"Each phone number belongs to a constituent account"}]}
    ]
  },

  "fundraising": {
    "objects": [
      {"name":"Opportunity","type":"standard","domain":"fundraising","description":"Opportunity represents a tracked fundraising solicitation, including major-gift and inbound-grant activity. Name, Amount, StageName, CloseDate, and Probability describe the ask and its pipeline status, while AccountId, CampaignId, and RecordTypeId associate it with the donor, source campaign, and configured opportunity process.","fields":[{"name":"Name","type":"Text","description":"Descriptive name for the solicitation or proposal"},{"name":"Amount","type":"Currency","description":"Expected gift amount for the opportunity"},{"name":"StageName","type":"Picklist","description":"Current pipeline stage (Prospecting, Cultivation, Solicitation, Closed Won)"},{"name":"CloseDate","type":"Date","description":"Expected or actual close date"},{"name":"Probability","type":"Percent","description":"Likelihood of winning the opportunity"},{"name":"AccountId","type":"Lookup","description":"The donor or organization account"},{"name":"CampaignId","type":"Lookup","description":"The campaign that sourced this opportunity"},{"name":"RecordTypeId","type":"Lookup","description":"Distinguishes major gifts, grants, planned giving, and other fundraising types"}],"relationships":[{"target":"Account","type":"child","description":"Each opportunity is associated with a donor account"},{"target":"Campaign","type":"child","description":"Opportunities are sourced from campaigns"},{"target":"OpportunityContactRole","type":"parent","description":"Opportunities have contact roles identifying involved individuals"},{"target":"GiftCommitment","type":"lookup","description":"Won opportunities can become gift commitments"}]},
      {"name":"OpportunityContactRole","type":"standard","domain":"fundraising","description":"OpportunityContactRole links a contact to an Opportunity and records the contact’s role in the solicitation. OpportunityId and ContactId establish the relationship, Role describes participation, and IsPrimary identifies the primary contact; gift influence is recorded separately with Gift Soft Credit or Gift Default Soft Credit records.","fields":[{"name":"OpportunityId","type":"Lookup","description":"The opportunity this contact role belongs to"},{"name":"ContactId","type":"Lookup","description":"The individual involved in the opportunity"},{"name":"Role","type":"Picklist","description":"The person's role (Primary Donor, Influencer, Decision Maker, Soft Credit)"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the primary contact for the opportunity"}],"relationships":[{"target":"Opportunity","type":"child","description":"Each contact role belongs to an opportunity"},{"target":"Contact","type":"child","description":"Each contact role references an individual"}]}
    ],
    "metadata": [
      {"type":"FundraisingSetting__mdt","name":"Fundraising Settings","fields":{"InstallmentExtensionDayCount__c":"Number","LapsedUnpaidTransactionCount__c":"Number","FailingTransactionCount__c":"Number","AutoCloseEnabled__c":"Checkbox"},"description":"FundraisingSetting__mdt represents Fundraising Settings configuration used by Nonprofit Cloud fundraising processes. Documented settings govern areas such as commitment processing, transaction and status behavior, gift entry, donor matching, RFM scoring, and the temporary pausing of supported gift validations during migrations."}
    ]
  },

  "gift_commitments": {
    "objects": [
      {"name":"GiftCommitment","type":"standard","domain":"gift_commitments","description":"GiftCommitment stores a commitment’s Name, DonorId, ScheduleType, Status, ExpectedTotalCmtAmount, and EffectiveStartDate. CampaignId and OpportunityId associate the commitment with the applicable campaign and opportunity.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated commitment identifier"},{"name":"DonorId","type":"Lookup","description":"The donor account making the commitment"},{"name":"ScheduleType","type":"Picklist","description":"Type of commitment: Recurring or Custom"},{"name":"Status","type":"Picklist","description":"Lifecycle status: Draft, Active, Paused, Lapsed, Failing, or Closed"},{"name":"ExpectedTotalCmtAmount","type":"Currency","description":"Total committed amount across all installments"},{"name":"CampaignId","type":"Lookup","description":"The campaign that sourced this commitment"},{"name":"OpportunityId","type":"Lookup","description":"The originating fundraising opportunity"},{"name":"EffectiveStartDate","type":"Date","description":"Date when the commitment begins"}],"relationships":[{"target":"Account","type":"child","description":"Each commitment belongs to a donor account"},{"target":"GiftCommitmentSchedule","type":"parent","description":"Commitments have one or more schedules defining installment patterns"},{"target":"GiftTransaction","type":"parent","description":"Commitments generate gift transactions for each installment"},{"target":"Opportunity","type":"child","description":"Commitments can originate from fundraising opportunities"}]},
      {"name":"GiftCommitmentSchedule","type":"standard","domain":"gift_commitments","description":"GiftCommitmentSchedule defines payment timing and amounts for a commitment through Name, GiftCommitmentId, TransactionPeriod, TransactionAmount, TransactionDay, StartDate, and EndDate. Nonprofit Cloud uses the schedule to create or update the Gift Commitment’s associated gift transactions.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated schedule identifier"},{"name":"GiftCommitmentId","type":"Lookup","description":"The parent gift commitment"},{"name":"TransactionPeriod","type":"Picklist","description":"Installment frequency: Monthly, Quarterly, Annually, or Custom"},{"name":"TransactionAmount","type":"Currency","description":"Amount per installment payment"},{"name":"TransactionDay","type":"Number","description":"Day of the month on which installments are due"},{"name":"StartDate","type":"Date","description":"Date when this schedule becomes active"},{"name":"EndDate","type":"Date","description":"Date when this schedule stops generating transactions"}],"relationships":[{"target":"GiftCommitment","type":"child","description":"Each schedule belongs to a gift commitment"},{"target":"PaymentInstrument","type":"lookup","description":"Schedules reference the payment method used for installments"}]}
    ]
  },

  "gift_transactions": {
    "objects": [
      {"name":"GiftTransaction","type":"standard","domain":"gift_transactions","description":"GiftTransaction records a donation or payment with its Name, DonorId, OriginalAmount, Status, TransactionDate, PaymentMethod, and GiftType. It can relate the transaction to a GiftCommitmentId, CampaignId, OutreachSourceCodeId, and MatchingEmployerTransactionId, while AcknowledgementStatus tracks acknowledgment processing.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated transaction identifier"},{"name":"DonorId","type":"Lookup","description":"The donor account for this transaction"},{"name":"OriginalAmount","type":"Currency","description":"Transaction amount received or expected"},{"name":"Status","type":"Picklist","description":"Transaction lifecycle: Unpaid, Pending, Paid, Failed, Canceled, Refunded, Written Off"},{"name":"TransactionDate","type":"Date","description":"Date the gift was received"},{"name":"PaymentMethod","type":"Picklist","description":"How the donor paid: Credit Card, Check, ACH, Wire, Cash"},{"name":"GiftType","type":"Picklist","description":"Specifies the type of gift associated with the transaction: Individual or Organizational."},{"name":"GiftCommitmentId","type":"Lookup","description":"The commitment this transaction fulfills, if applicable"},{"name":"CampaignId","type":"Lookup","description":"Campaign attribution for this transaction"},{"name":"OutreachSourceCodeId","type":"Lookup","description":"Granular outreach source code for attribution"},{"name":"AcknowledgementStatus","type":"Picklist","description":"Whether the donor has been thanked: Not Sent, Sent, Failed"},{"name":"MatchingEmployerTransactionId","type":"Lookup","description":"Links to the corporate matching gift transaction"}],"relationships":[{"target":"Account","type":"child","description":"Each transaction belongs to a donor account"},{"target":"GiftCommitment","type":"child","description":"Transactions fulfill commitment installments"},{"target":"Campaign","type":"child","description":"Transactions are attributed to campaigns"},{"target":"GiftTransactionDesignation","type":"parent","description":"Transactions are allocated to designations through junction records"},{"target":"GiftSoftCredit","type":"parent","description":"Transactions can have soft credit recipients"}]},
      {"name":"PaymentInstrument","type":"standard","domain":"gift_transactions","description":"PaymentInstrument stores payment method information associated with an account, using Name, AccountId, and Type. Last4, ExpiryMonth, and ExpiryYear retain the payment details used with gift transactions and gift commitment schedules.","fields":[{"name":"Name","type":"Text","description":"Display name for the payment method (e.g., Visa ending 4242)"},{"name":"AccountId","type":"Lookup","description":"The donor account that owns this payment instrument"},{"name":"Type","type":"Picklist","description":"Type of payment: Credit Card, ACH, Bank Transfer"},{"name":"Last4","type":"Text","description":"Last four digits of the card or account number"},{"name":"ExpiryMonth","type":"Date","description":"Expiration date for credit card instruments"},{"name":"ExpiryYear","type":"Text","description":"Instrument/card expiration year. Added only because the graph's single ExpirationDate maps to two real PaymentInstrument fields (ExpiryMonth + ExpiryYear)."}],"relationships":[{"target":"Account","type":"child","description":"Each payment instrument belongs to a donor account"},{"target":"GiftCommitmentSchedule","type":"lookup","description":"Payment instruments are linked to commitment schedules for recurring processing"}]}
    ]
  },

  "gift_entry": {
    "objects": [
      {"name":"GiftEntry","type":"standard","domain":"gift_entry","description":"GiftEntry stores donation information captured for processing, including Name, DonorId, GiftAmount, PaymentMethod, and an optional GiftBatchId. GiftProcessingStatus and GiftProcessingResult record the processing state and outcome, including errors that users can review and correct.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated entry identifier"},{"name":"DonorId","type":"Lookup","description":"The donor account for this gift entry"},{"name":"GiftAmount","type":"Currency","description":"Gift amount to be processed"},{"name":"PaymentMethod","type":"Picklist","description":"How the donor is paying"},{"name":"GiftBatchId","type":"Lookup","description":"The batch this entry belongs to, if applicable"},{"name":"GiftProcessingStatus","type":"Picklist","description":"Entry status: Draft, Ready, Processing, Completed, Failed"},{"name":"GiftProcessingResult","type":"LongTextArea","description":"Processing outcome details including any error messages"}],"relationships":[{"target":"Account","type":"child","description":"Each gift entry references a donor account"},{"target":"GiftBatch","type":"child","description":"Entries are grouped in batches for bulk processing"},{"target":"GiftTransaction","type":"lookup","description":"Processing creates a gift transaction from each entry"}]},
      {"name":"GiftBatch","type":"standard","domain":"gift_entry","description":"GiftBatch groups GiftEntry records for shared validation and processing. Name and ScreenTemplateName identify the batch and its Gift Entry Grid layout, EstimatedGiftCount and ExpectedValueofGiftsinBatch support expected-count and value checks, and Status and LastProcessedDateTime track processing.","fields":[{"name":"Name","type":"Text","description":"Descriptive name for the batch"},{"name":"ScreenTemplateName","type":"Lookup","description":"The template controlling which fields appear in the batch"},{"name":"EstimatedGiftCount","type":"Number","description":"Expected number of gifts for reconciliation"},{"name":"ExpectedValueofGiftsinBatch","type":"Currency","description":"Expected total value for reconciliation"},{"name":"Status","type":"Picklist","description":"Batch status: Open, Processing, Completed, Partially Processed"},{"name":"LastProcessedDateTime","type":"DateTime","description":"Timestamp when the batch was processed"}],"relationships":[{"target":"GiftEntry","type":"parent","description":"Batches contain multiple gift entries"},{"target":"GiftEntryGridTemplate","type":"child","description":"Each batch uses a template for field configuration"}]},
      {"name":"GiftEntryGridTemplate","type":"standard","domain":"gift_entry","description":"GiftEntryGridTemplate represents a configurable Gift Entry Grid layout used for targeted gift-entry experiences. Name and Description identify the template, TemplateConfiguration stores its configured columns and behavior, and IsActive indicates whether the template is active.","fields":[{"name":"Name","type":"Text","description":"Template name describing its purpose"},{"name":"Description","type":"LongTextArea","description":"Explanation of when to use this template"},{"name":"TemplateConfiguration","type":"LongTextArea","description":"JSON configuration of fields, order, and defaults"},{"name":"IsActive","type":"Checkbox","description":"Whether this template is available for use"}],"relationships":[{"target":"GiftBatch","type":"parent","description":"Templates are applied to gift batches"}]}
    ]
  },

  "designations": {
    "objects": [
      {"name":"GiftDesignation","type":"standard","domain":"designations","description":"GiftDesignation represents a named fund or purpose to which gifts can be allocated. Its fields identify whether the designation is active or the organization-wide default and store its description, total amount, and transaction count for tracking and rollup use.","fields":[{"name":"Name","type":"Text","description":"Fund or purpose name displayed to donors and staff"},{"name":"IsActive","type":"Checkbox","description":"Whether this designation is available for gift allocation"},{"name":"IsDefault","type":"Checkbox","description":"Whether this is the org-wide default designation for unrestricted gifts"},{"name":"TotalTransactionAmount","type":"Currency","description":"Rollup total of all allocated gift transaction amounts"},{"name":"TotalTransactionCount","type":"Number","description":"Rollup count of gift transactions allocated to this designation"},{"name":"Description","type":"LongTextArea","description":"Description of the fund's purpose and restrictions"}],"relationships":[{"target":"GiftTransactionDesignation","type":"parent","description":"Designations receive allocations through gift transaction designation junction records"},{"target":"GiftDefaultDesignation","type":"parent","description":"Designations can be set as defaults at various levels"}]},
      {"name":"GiftTransactionDesignation","type":"standard","domain":"designations","description":"GiftTransactionDesignation links a gift transaction to a gift designation and records the allocated Amount and Percent. Multiple records can divide one transaction among several designations, with any remaining allocation assigned to the organization-wide default.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated allocation identifier"},{"name":"GiftTransactionId","type":"Lookup","description":"The gift transaction being allocated"},{"name":"GiftDesignationId","type":"Lookup","description":"The designation receiving the allocation"},{"name":"Amount","type":"Currency","description":"Dollar amount allocated to this designation"},{"name":"Percent","type":"Percent","description":"Percentage of the transaction allocated to this designation"}],"relationships":[{"target":"GiftTransaction","type":"child","description":"Each allocation belongs to a gift transaction"},{"target":"GiftDesignation","type":"child","description":"Each allocation references a gift designation fund"}]},
      {"name":"GiftDefaultDesignation","type":"standard","domain":"designations","description":"GiftDefaultDesignation associates a gift designation with a parent fundraising record so that its allocation can be inherited during commitment or gift processing. Its fields identify the designation and parent record and provide a Priority value for the default relationship.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated default designation identifier"},{"name":"GiftDesignationId","type":"Lookup","description":"The designation to use as the default"},{"name":"ParentRecordId","type":"Lookup","description":"The campaign, commitment, or opportunity this default applies to (polymorphic)"}],"relationships":[{"target":"GiftDesignation","type":"child","description":"Each default references a gift designation"},{"target":"Campaign","type":"lookup","description":"Default designations can be set at the campaign level"},{"target":"GiftCommitment","type":"lookup","description":"Default designations can be set at the commitment level"}]}
    ]
  },

  "soft_credits": {
    "objects": [
      {"name":"GiftSoftCredit","type":"standard","domain":"soft_credits","description":"GiftSoftCredit records associate soft-credit recognition with a Gift Transaction and recipient. Name identifies the record, GiftTransactionId and RecipientId identify the related transaction and recipient, Role identifies the recipient’s role, and PartialAmount stores the credited portion of the gift.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated soft credit identifier"},{"name":"GiftTransactionId","type":"Lookup","description":"The gift transaction being credited"},{"name":"RecipientId","type":"Lookup","description":"The constituent account receiving the soft credit"},{"name":"Role","type":"Picklist","description":"The soft credit role of the account or contact (for example, Honoree, Household Member, Influencer, Matched Donor, Solicitor, Soft Credit, or Other)."},{"name":"PartialAmount","type":"Currency","description":"Amount of the soft credit, which may be partial"}],"relationships":[{"target":"GiftTransaction","type":"child","description":"Each soft credit references a gift transaction"},{"target":"Account","type":"child","description":"Each soft credit is attributed to a constituent account"}]}
    ]
  },

  "campaigns": {
    "objects": [
      {"name":"Campaign","type":"standard","domain":"campaigns","description":"Campaign represents a fundraising or outreach effort and stores its Name, Type, Status, StartDate, and EndDate. BudgetedCost, ExpectedRevenue, and ActualCost support planning and performance analysis, including return-on-investment calculations in Fundraising Intelligence.","fields":[{"name":"Name","type":"Text","description":"Campaign name"},{"name":"Type","type":"Picklist","description":"Campaign type: Appeal, Event, Direct Mail, Digital, Phonathon"},{"name":"Status","type":"Picklist","description":"Campaign lifecycle: Planned, In Progress, Completed, Aborted"},{"name":"StartDate","type":"Date","description":"Campaign start date"},{"name":"EndDate","type":"Date","description":"Campaign end date"},{"name":"BudgetedCost","type":"Currency","description":"Planned budget for the campaign"},{"name":"ExpectedRevenue","type":"Currency","description":"Expected total revenue from the campaign"},{"name":"ActualCost","type":"Currency","description":"Actual cost incurred"}],"relationships":[{"target":"OutreachSourceCode","type":"parent","description":"Campaigns contain outreach source codes for granular attribution"},{"target":"GiftTransaction","type":"parent","description":"Gift transactions are attributed to campaigns"},{"target":"GiftCommitment","type":"parent","description":"Gift commitments are linked to campaigns"},{"target":"Opportunity","type":"parent","description":"Fundraising opportunities are sourced from campaigns"}]},
      {"name":"OutreachSourceCode","type":"standard","domain":"campaigns","description":"OutreachSourceCode represents an outreach method associated with a campaign and can be selected during gift entry to attribute a donation to that effort. Name and CampaignId identify the code and related campaign, while MessageChannel, MessageContent, AudienceInformation, and Status describe the outreach communication, intended audience, and availability state.","fields":[{"name":"Name","type":"Text","description":"Source code identifier, often a formatted tracking code"},{"name":"CampaignId","type":"Lookup","description":"The parent campaign"},{"name":"MessageChannel","type":"Picklist","description":"Communication channel: Email, Direct Mail, Social, Phone, Web"},{"name":"MessageContent","type":"Text","description":"Specific message or creative identifier"},{"name":"AudienceInformation","type":"Text","description":"Target audience segment description"},{"name":"Status","type":"Checkbox","description":"Whether this source code is active for attribution"}],"relationships":[{"target":"Campaign","type":"child","description":"Each source code belongs to a campaign"},{"target":"GiftTransaction","type":"parent","description":"Transactions reference source codes for granular attribution"}]}
    ]
  },

  "programs": {
    "objects": [
      {"name":"Program","type":"standard","domain":"programs","description":"Program represents a mission-driven initiative managed in Nonprofit Cloud. Name and Summary identify and explain the program, while Status, StartDate, and EndDate track its operating state and duration.","fields":[{"name":"Name","type":"Text","description":"Program name"},{"name":"Summary","type":"LongTextArea","description":"Detailed description of the program's purpose and activities"},{"name":"Status","type":"Picklist","description":"Program lifecycle: Active, Inactive, Planned, Completed"},{"name":"StartDate","type":"Date","description":"Date when the program begins operations"},{"name":"EndDate","type":"Date","description":"Date when the program concludes, if applicable"}],"relationships":[{"target":"Benefit","type":"parent","description":"Programs offer specific benefits and services to participants"},{"target":"ProgramEnrollment","type":"parent","description":"Participants enroll in programs"},{"target":"ProgramCohort","type":"parent","description":"Programs organize participants into cohorts"}]},
      {"name":"Benefit","type":"standard","domain":"programs","description":"Benefit represents a good, service, class, workshop, coaching session, or other offering delivered through a program. ProgramId, BenefitTypeId, and UnitId provide its program context, category, and measurement unit, while Name and IsActive identify the benefit and whether it is available.","fields":[{"name":"Name","type":"Text","description":"Benefit name describing the service or good"},{"name":"ProgramId","type":"Lookup","description":"The program that offers this benefit"},{"name":"BenefitTypeId","type":"Lookup","description":"The type category: Coaching, Distribution, Training, etc."},{"name":"UnitId","type":"Lookup","description":"The unit used to measure delivery quantity"},{"name":"IsActive","type":"Checkbox","description":"Whether this benefit is currently offered"}],"relationships":[{"target":"Program","type":"child","description":"Each benefit belongs to a program"},{"target":"BenefitType","type":"child","description":"Benefits are classified by type"},{"target":"BenefitDisbursement","type":"parent","description":"Benefits are delivered through disbursement records"},{"target":"BenefitSchedule","type":"parent","description":"Benefits have delivery schedules"}]},
      {"name":"BenefitType","type":"standard","domain":"programs","description":"BenefitType categorizes benefits that are delivered through Program Management. Name identifies the category, and Description records explanatory information about that type of benefit.","fields":[{"name":"Name","type":"Text","description":"Type name such as Coaching, Distribution, or Training"},{"name":"Description","type":"LongTextArea","description":"Explanation of what this benefit type covers"}],"relationships":[{"target":"Benefit","type":"parent","description":"Benefit types classify one or more benefits across programs"}]},
      {"name":"UnitOfMeasure","type":"standard","domain":"programs","description":"UnitOfMeasure defines how a benefit quantity is expressed, such as Kits or Hours. Name and UnitCode identify the unit, while Status records its current state.","fields":[{"name":"Name","type":"Text","description":"Unit name such as Hours, Sessions, Meals, or Items"},{"name":"UnitCode","type":"Text","description":"Short form of the unit (e.g., hrs, qty)"},{"name":"Status","type":"Checkbox","description":"Whether this unit is available for use"}],"relationships":[{"target":"Benefit","type":"parent","description":"Units of measure are assigned to benefits for quantity tracking"}]},
      {"name":"ProgramEnrollment","type":"standard","domain":"programs","description":"ProgramEnrollment associates a constituent Account with a Program and tracks the constituent's participation. Name, Status, StartDate, and EndDate identify the enrollment and record its state and participation period.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated enrollment identifier"},{"name":"AccountId","type":"Lookup","description":"The participant account"},{"name":"ProgramId","type":"Lookup","description":"The program the participant is enrolling in"},{"name":"Status","type":"Picklist","description":"Enrollment status: Applied, Enrolled, Active, Completed, Withdrawn"},{"name":"StartDate","type":"Date","description":"Date when the participant enrolled"},{"name":"EndDate","type":"Date","description":"Date when the participant completed or withdrew"}],"relationships":[{"target":"Account","type":"child","description":"Each enrollment references a participant account"},{"target":"Program","type":"child","description":"Each enrollment references a program"}]},
      {"name":"ProgramCohort","type":"standard","domain":"programs","description":"ProgramCohort groups participants within a program, such as participants in a geographic area or a particular program run. ProgramId associates the cohort with its program, while Name, StartDate, EndDate, and MaximumMemberCount define the group and its operating parameters.","fields":[{"name":"Name","type":"Text","description":"Cohort name or identifier"},{"name":"ProgramId","type":"Lookup","description":"The program this cohort belongs to"},{"name":"StartDate","type":"Date","description":"Cohort start date"},{"name":"EndDate","type":"Date","description":"Cohort end date"},{"name":"MaximumMemberCount","type":"Number","description":"Maximum number of participants in this cohort"}],"relationships":[{"target":"Program","type":"child","description":"Each cohort belongs to a program"},{"target":"ProgramCohortMember","type":"parent","description":"Cohorts contain member records linking to participants"}]},
      {"name":"ProgramCohortMember","type":"standard","domain":"programs","description":"ProgramCohortMember represents an enrollee's membership in a Program Cohort. ProgramCohortId, ProgramEnrolleeId, and ProgramEnrollmentId provide the related cohort and enrollment context, while Name and ProgramEnrollmentStatus track the membership record and its status.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated member identifier"},{"name":"ProgramCohortId","type":"Lookup","description":"The cohort this member belongs to"},{"name":"ProgramEnrolleeId","type":"Lookup","description":"The participant account"},{"name":"ProgramEnrollmentStatus","type":"Picklist","description":"Membership status: Active, Inactive, Completed"},{"name":"ProgramEnrollmentId","type":"Lookup","description":"Lookup to the ProgramEnrollment placed in this cohort — the junction's defining foreign key; backs the ProgramCohortMember -> ProgramEnrollment edge."}],"relationships":[{"target":"ProgramCohort","type":"child","description":"Each member record belongs to a cohort"},{"target":"Account","type":"child","description":"Each member references a participant account"},{"target":"ProgramEnrollment","type":"child","description":"Each cohort member corresponds to a ProgramEnrollment via ProgramEnrollmentId. This is the junction's core linkage and carries the enrollment<->cohort relationship after the fabricated ProgramEnrollment->ProgramCohort edge is removed. Both endpoints (ProgramCohortMember, ProgramEnrollment) are graph nodes, so the edge is non-dangling."}]},
      {"name":"BenefitDisbursement","type":"standard","domain":"programs","description":"BenefitDisbursement records the actual delivery of an assigned benefit to a recipient. RecipientId and BenefitAssignmentId identify the recipient and assignment, while DisbursedQuantity, ActualCompletionDate, and DisbursementStatus capture the delivered amount, completion date, and status.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated disbursement identifier"},{"name":"RecipientId","type":"Lookup","description":"The participant receiving the benefit"},{"name":"BenefitAssignmentId","type":"Lookup","description":"The benefit being delivered"},{"name":"DisbursedQuantity","type":"Number","description":"Amount delivered in the benefit's unit of measure"},{"name":"ActualCompletionDate","type":"Date","description":"Date of service delivery"},{"name":"DisbursementStatus","type":"Picklist","description":"Delivery status: Scheduled, Delivered, Missed, Canceled"}],"relationships":[{"target":"BenefitAssignment","type":"child","description":"Each disbursement delivers a specific benefit"},{"target":"Account","type":"child","description":"Each disbursement goes to a participant account"},{"target":"BenefitSession","type":"lookup","description":"Disbursements may be linked to scheduled benefit sessions"}]},
      {"name":"BenefitSchedule","type":"standard","domain":"programs","description":"BenefitSchedule defines scheduled delivery for a Benefit and can establish a recurring pattern for sessions. BenefitId identifies the offering, while Name, FirstSessionStartDateTime, and FirstSessionEndDateTime describe the schedule and its first session.","fields":[{"name":"Name","type":"Text","description":"Schedule name describing the delivery pattern"},{"name":"BenefitId","type":"Lookup","description":"The benefit this schedule applies to"},{"name":"FirstSessionStartDateTime","type":"Date","description":"Schedule start date"},{"name":"FirstSessionEndDateTime","type":"Date","description":"Schedule end date"}],"relationships":[{"target":"Benefit","type":"child","description":"Each schedule defines delivery timing for a benefit"},{"target":"BenefitSession","type":"parent","description":"Schedules generate individual benefit sessions"}]},
      {"name":"BenefitSession","type":"standard","domain":"programs","description":"BenefitSession represents a scheduled occurrence created under a Benefit Schedule. BenefitScheduleId connects the session to its schedule, while Name, StartDateTime, and Status identify the occurrence and track its timing and state.","fields":[{"name":"Name","type":"Text","description":"Session name or date identifier"},{"name":"BenefitScheduleId","type":"Lookup","description":"The schedule that generated this session"},{"name":"StartDateTime","type":"DateTime","description":"Date and time of the session"},{"name":"Status","type":"Picklist","description":"Session status: Scheduled, In Progress, Completed, Canceled"}],"relationships":[{"target":"BenefitSchedule","type":"child","description":"Each session is generated from a benefit schedule"},{"target":"BenefitDisbursement","type":"parent","description":"Session attendance creates disbursement records"}]},
      {"name":"BenefitAssignment","type":"standard","domain":"programs","description":"BenefitAssignment associates an enrollee with a Benefit and represents the participant's assigned or entitled offering. EnrolleeId and BenefitId identify the relationship, while Name, EntitlementAmount, and Status record the assignment, its amount, and its state.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated assignment identifier"},{"name":"EnrolleeId","type":"Lookup","description":"The participant assigned to receive this benefit"},{"name":"BenefitId","type":"Lookup","description":"The benefit the participant is assigned to receive"},{"name":"EntitlementAmount","type":"Number","description":"Total quantity the participant is expected to receive"},{"name":"Status","type":"Picklist","description":"Assignment status: Active, Completed, Suspended"}],"relationships":[{"target":"Account","type":"child","description":"Each assignment references a participant account"},{"target":"Benefit","type":"child","description":"Each assignment references a specific benefit"}]},
      {"name":"GoalDefinition","type":"standard","domain":"programs","description":"GoalDefinition defines a reusable participant goal that can be included in a goal hierarchy or care plan template. Name and Description explain the goal, ParentGoalId establishes its parent relationship, and Status tracks its current state.","fields":[{"name":"Name","type":"Text","description":"Goal name describing the desired outcome"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the goal and success criteria"},{"name":"ParentGoalId","type":"Lookup","description":"Parent goal for hierarchical goal structures"},{"name":"Status","type":"Picklist","description":"Goal status: Not Started, In Progress, Achieved, Not Achieved"}],"relationships":[]}
    ],
    "metadata": [
      {"type":"ProgramManagementSetting__mdt","name":"Program Management Settings","fields":{"AutoEnrollmentEnabled__c":"Checkbox","DefaultBenefitType__c":"Text","DisbursementTrackingEnabled__c":"Checkbox","GoalHierarchyDepth__c":"Number"},"description":"ProgramManagementSetting__mdt is the Program Management Settings custom metadata type for Nonprofit Cloud. It represents configuration used by Program Management after the feature is enabled and configured through Nonprofit Cloud Setup."}
    ]
  },

  "case_management": {
    "objects": [
      {"name":"Case","type":"standard","domain":"case_management","description":"Case represents participant work created for assessment and follow-up, including cases converted from referrals. It records identifiers and operational details through CaseNumber, Subject, Status, Priority, Origin, and Description and can relate the case to constituent records through AccountId and ContactId.","fields":[{"name":"CaseNumber","type":"AutoNumber","description":"System-generated case identifier"},{"name":"Subject","type":"Text","description":"Brief description of the case subject"},{"name":"Status","type":"Picklist","description":"Case lifecycle: New, In Progress, Pending, Closed"},{"name":"Priority","type":"Picklist","description":"Urgency level: Low, Medium, High, Critical"},{"name":"AccountId","type":"Lookup","description":"The participant account"},{"name":"ContactId","type":"Lookup","description":"The participant contact"},{"name":"Origin","type":"Picklist","description":"How the case was created: Self-Referral, Partner Agency, Internal, Phone"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the participant's needs"}],"relationships":[{"target":"Account","type":"child","description":"Each case references a participant account"},{"target":"CarePlan","type":"parent","description":"Cases can have personalized care plans"},{"target":"Referral","type":"parent","description":"Cases can be created from referrals"},{"target":"InteractionSummary","type":"parent","description":"Cases have interaction summaries documenting meetings and notes"}]},
      {"name":"CarePlan","type":"standard","domain":"case_management","description":"CarePlan represents a personalized plan for a participant and can be associated with a case and a standardized Care Plan Template. It tracks the participant, template, status, and plan period through ParticipantId, CaseId, CarePlanTemplateId, Status, StartDate, and EndDate.","fields":[{"name":"Name","type":"Text","description":"Care plan name describing its focus area"},{"name":"ParticipantId","type":"Lookup","description":"The participant account this plan serves"},{"name":"CaseId","type":"Lookup","description":"The case this care plan addresses"},{"name":"CarePlanTemplateId","type":"Lookup","description":"The template used as a starting point"},{"name":"Status","type":"Picklist","description":"Plan status: Draft, Active, Completed, Discontinued"},{"name":"StartDate","type":"Date","description":"Plan start date"},{"name":"EndDate","type":"Date","description":"Plan end date"}],"relationships":[{"target":"Account","type":"child","description":"Each care plan serves a participant account"},{"target":"Case","type":"child","description":"Care plans are linked to cases"},{"target":"CarePlanTemplate","type":"child","description":"Care plans are built from templates"}]},
      {"name":"CarePlanTemplate","type":"standard","domain":"case_management","description":"CarePlanTemplate defines a standardized starting point for participant care plans that staff can customize for individual needs. It stores the template’s Name, Description, and Status and can organize template benefits and goals through related records.","fields":[{"name":"Name","type":"Text","description":"Template name describing the scenario it addresses"},{"name":"Description","type":"LongTextArea","description":"Detailed description of when to use this template"},{"name":"Status","type":"Checkbox","description":"Whether this template is available for use"}],"relationships":[{"target":"CarePlan","type":"parent","description":"Templates are used to create care plan instances"},{"target":"CarePlanTemplateBenefit","type":"parent","description":"Templates include pre-configured benefit assignments"},{"target":"CarePlanTemplateGoal","type":"parent","description":"Templates include pre-configured goal definitions"}]},
      {"name":"CarePlanTemplateBenefit","type":"standard","domain":"case_management","description":"CarePlanTemplateBenefit associates a benefit with a Care Plan Template. It identifies the relationship through Name, CarePlanTemplateId, and BenefitId so that the benefit can be included when the template is used.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"CarePlanTemplateId","type":"Lookup","description":"The parent care plan template"},{"name":"BenefitId","type":"Lookup","description":"The benefit to include in the plan"}],"relationships":[{"target":"CarePlanTemplate","type":"child","description":"Each template benefit belongs to a care plan template"},{"target":"Benefit","type":"child","description":"References the benefit to be included"}]},
      {"name":"CarePlanTemplateGoal","type":"standard","domain":"case_management","description":"CarePlanTemplateGoal associates a goal definition with a Care Plan Template. It uses Name, CarePlanTemplateId, and GoalDefinitionId to include standardized goals in template-based care plans.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"CarePlanTemplateId","type":"Lookup","description":"The parent care plan template"},{"name":"GoalDefinitionId","type":"Lookup","description":"The goal to include in the plan"}],"relationships":[{"target":"CarePlanTemplate","type":"child","description":"Each template goal belongs to a care plan template"},{"target":"GoalDefinition","type":"child","description":"References the goal definition to track"}]},
      {"name":"Referral","type":"standard","domain":"case_management","description":"Referral represents an inbound or outbound participant referral that can be converted to or associated with a case for assessment and follow-up. It records Name, CaseId, ReferralType, ReferrerId, and Status, and the object supports Path.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated referral identifier"},{"name":"CaseId","type":"Lookup","description":"The case created from or associated with this referral"},{"name":"ReferralType","type":"Picklist","description":"Direction: Inbound or Outbound"},{"name":"ReferrerId","type":"Lookup","description":"The account or contact that referred the participant (polymorphic ReferrerId)"},{"name":"Status","type":"Picklist","description":"Referral status: Pending, Accepted, Declined, Completed"}],"relationships":[{"target":"Case","type":"child","description":"Each referral is linked to a case"},{"target":"Account","type":"lookup","description":"ReferrerId references the account (or contact) that referred the participant"}]},
      {"name":"AssessmentTask","type":"standard","domain":"case_management","description":"AssessmentTask represents a task used in assessment work. It records the task’s Name and Status for identification and progress tracking.","fields":[{"name":"Name","type":"Text","description":"Assessment name or type"},{"name":"Status","type":"Picklist","description":"Assessment status: Not Started, In Progress, Completed"}],"relationships":[{"target":"Account","type":"child","description":"Each assessment is completed for a participant"},{"target":"Case","type":"lookup","description":"Assessments are linked to participant cases"}]},
      {"name":"InteractionSummary","type":"standard","domain":"case_management","description":"InteractionSummary stores detailed, permanent notes associated with an account. It records Name, MeetingNotes, NextSteps, and ConfidentialityType through the provided fields and can supply Interaction Summary data used by Einstein Notes Summary.","fields":[{"name":"Name","type":"Text","description":"Interaction title or subject"},{"name":"AccountId","type":"Lookup","description":"The account this interaction relates to"},{"name":"MeetingNotes","type":"RichTextArea","description":"Detailed notes from the interaction"},{"name":"NextSteps","type":"LongTextArea","description":"Planned follow-up actions"},{"name":"ConfidentialityType","type":"Checkbox","description":"Whether this interaction contains sensitive information requiring restricted access"}],"relationships":[{"target":"Account","type":"child","description":"Each interaction is linked to a constituent account"},{"target":"Case","type":"lookup","description":"Interactions can be linked to a case for case management context"}]}
    ]
  },

  "outcomes": {
    "objects": [
      {"name":"Outcome","type":"standard","domain":"outcomes","description":"Outcome represents an intended result in a Nonprofit Cloud impact strategy or theory of change. It stores the result’s Name and Description and can be related to Program and IndicatorDefinition records.","fields":[{"name":"Name","type":"Text","description":"Outcome name describing the desired impact"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the outcome and its significance"}],"relationships":[{"target":"Program","type":"lookup","description":"Outcomes link to the programs that drive them"},{"target":"IndicatorDefinition","type":"parent","description":"Outcomes are measured through indicators"}]},
      {"name":"IndicatorDefinition","type":"standard","domain":"outcomes","description":"IndicatorDefinition represents a measure used with an Outcome in Nonprofit Cloud. Its Name identifies the measure, which supports organizing program-performance and intended-outcome tracking.","fields":[{"name":"Name","type":"Text","description":"Indicator name describing the metric"}],"relationships":[{"target":"Outcome","type":"child","description":"Each indicator measures a specific outcome"},{"target":"IndicatorResult","type":"parent","description":"Indicators accumulate result data points over time"}]},
      {"name":"IndicatorResult","type":"standard","domain":"outcomes","description":"IndicatorResult records a measured value for an Indicator Definition within an Indicator Performance Period. It stores Name, IndicatorPerformancePeriodId, ResultValue, and MeasurementDate for progress evaluation and reporting.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated result identifier"},{"name":"IndicatorPerformancePeriodId","type":"Lookup","description":"The indicator this result measures"},{"name":"ResultValue","type":"Number","description":"The measured value"},{"name":"MeasurementDate","type":"Date","description":"Date when the measurement was taken"}],"relationships":[{"target":"IndicatorDefinition","type":"child","description":"Each result belongs to an indicator"},{"target":"Program","type":"lookup","description":"Results are collected from program activities"}]}
    ]
  },

  "volunteers": {
    "objects": [
      {"name":"VolunteerInitiative","type":"standard","domain":"volunteers","description":"VolunteerInitiative represents organized volunteer work in Nonprofit Cloud. Name, Description, StartDate, EndDate, and Status describe its scope and lifecycle, while ParentVolunteerInitiativeId supports related initiatives and IsPublished controls publication for Experience Cloud.","fields":[{"name":"Name","type":"Text","description":"Initiative name"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the volunteer project"},{"name":"StartDate","type":"Date","description":"Initiative start date"},{"name":"EndDate","type":"Date","description":"Initiative end date"},{"name":"Status","type":"Picklist","description":"Initiative status: Planned, Active, Completed, Canceled"},{"name":"ParentVolunteerInitiativeId","type":"Lookup","description":"Parent initiative for hierarchical structures"},{"name":"IsPublished","type":"Checkbox","description":"Whether this initiative is visible on the volunteer portal"}],"relationships":[{"target":"JobPosition","type":"parent","description":"Initiatives are staffed by job positions"}]},
      {"name":"Position","type":"standard","domain":"volunteers","description":"Position represents a reusable functional volunteer role that can apply across multiple Volunteer Initiatives. Name and Description identify the role, RequiredQualifications captures its requirements, and IsActive indicates whether it is available for use.","fields":[{"name":"Name","type":"Text","description":"Position title"},{"name":"Description","type":"LongTextArea","description":"Role description and general responsibilities"},{"name":"RequiredQualifications","type":"LongTextArea","description":"Qualifications needed for this role"},{"name":"IsActive","type":"Checkbox","description":"Whether this position is available for use"}],"relationships":[{"target":"JobPosition","type":"parent","description":"Generic positions are customized as job positions for specific initiatives"},{"target":"Competency","type":"lookup","description":"Positions may require specific competencies"}]},
      {"name":"JobPosition","type":"standard","domain":"volunteers","description":"JobPosition represents a specific volunteer role associated with a Volunteer Initiative and, when applicable, a reusable Position. Name, VolunteerInitiativeId, PositionId, and LocationId identify the role, its initiative, its general position, and where the work occurs.","fields":[{"name":"Name","type":"Text","description":"Job position name specific to this initiative"},{"name":"VolunteerInitiativeId","type":"Lookup","description":"The initiative this job position belongs to"},{"name":"PositionId","type":"Lookup","description":"The generic position this job position instantiates"},{"name":"LocationId","type":"Text","description":"Where the volunteer will work"}],"relationships":[{"target":"VolunteerInitiative","type":"child","description":"Each job position belongs to a volunteer initiative"},{"target":"Position","type":"child","description":"Each job position references a generic position"},{"target":"JobPositionShift","type":"parent","description":"Job positions have one or more shifts"}]},
      {"name":"JobPositionShift","type":"standard","domain":"volunteers","description":"JobPositionShift represents a dated and timed work period for a Job Position. Name, JobPositionId, StartDate, EndDate, StartTime, and EndTime define the shift, while MaximumAttendeesCount and PositionAssignmentCount support capacity and coverage tracking.","fields":[{"name":"Name","type":"Text","description":"Shift name or time slot description"},{"name":"JobPositionId","type":"Lookup","description":"The job position this shift belongs to"},{"name":"StartDate","type":"DateTime","description":"Shift start date and time"},{"name":"EndDate","type":"DateTime","description":"Shift end date and time"},{"name":"MaximumAttendeesCount","type":"Number","description":"Maximum number of volunteers for this shift"},{"name":"PositionAssignmentCount","type":"Number","description":"Number of volunteers currently assigned"},{"name":"StartTime","type":"Time","description":"Shift start time (split partner of StartDate)"},{"name":"EndTime","type":"Time","description":"Shift end time (split partner of EndDate)"}],"relationships":[{"target":"JobPosition","type":"child","description":"Each shift belongs to a job position"},{"target":"JobPositionAssignment","type":"parent","description":"Shifts have volunteer assignments"}]},
      {"name":"JobPositionAssignment","type":"standard","domain":"volunteers","description":"JobPositionAssignment represents a volunteer's assignment to a Job Position and, when selected, a specific Job Position Shift. AssignedAccountId identifies the volunteer, AssignedPositionShiftId is used for a shift-specific assignment, and Status and ActualDuration record participation and actual time; if no shift is selected, Nonprofit Cloud applies the assignment to the Job Position without creating a specific Job Position Shift.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated assignment identifier"},{"name":"AssignedPositionShiftId","type":"Lookup","description":"The shift this volunteer is assigned to"},{"name":"AssignedAccountId","type":"Lookup","description":"The volunteer's person account"},{"name":"Status","type":"Picklist","description":"Assignment status: Upcoming, In Progress, Completed, No Show, Canceled"},{"name":"ActualDuration","type":"Number","description":"Actual hours worked by the volunteer"}],"relationships":[{"target":"JobPositionShift","type":"child","description":"Each assignment belongs to a shift"},{"target":"Account","type":"child","description":"Each assignment references a volunteer account"}]},
      {"name":"Competency","type":"standard","domain":"volunteers","description":"Competency defines a skill that can be associated with volunteer qualifications and volunteer records. Name, Description, Category, and IsActive classify the competency and indicate whether it is available for use.","fields":[{"name":"Name","type":"Text","description":"Competency name"},{"name":"Description","type":"LongTextArea","description":"What this competency represents"},{"name":"Category","type":"Picklist","description":"Competency category: Skill, Certification, License, Background Check"},{"name":"IsActive","type":"Checkbox","description":"Whether this competency is actively tracked"}],"relationships":[{"target":"PersonCompetency","type":"parent","description":"Competencies are held by individuals through person competency records"},{"target":"Position","type":"lookup","description":"Positions may require specific competencies"}]},
      {"name":"PersonCompetency","type":"standard","domain":"volunteers","description":"PersonCompetency associates a constituent Account with a Competency. Name, AccountId, CompetencyId, ProficiencyLevel, DateAchieved, and ExpirationDate record the person's competency, proficiency, achievement date, and applicable expiration.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"AccountId","type":"Lookup","description":"The volunteer who holds this competency"},{"name":"CompetencyId","type":"Lookup","description":"The competency being recorded"},{"name":"ProficiencyLevel","type":"Picklist","description":"Proficiency: Beginner, Intermediate, Advanced, Expert"},{"name":"DateAchieved","type":"Date","description":"When the volunteer earned this competency"},{"name":"ExpirationDate","type":"Date","description":"When the competency expires, if applicable"}],"relationships":[{"target":"Account","type":"child","description":"Each person competency belongs to a volunteer account"},{"target":"Competency","type":"child","description":"References the competency definition"}]},
      {"name":"Examination","type":"standard","domain":"volunteers","description":"Examination defines an assessment that can qualify volunteers for a required or preferred license or permit. Name and Description identify the assessment, while PassingScore, ValidityPeriod, and IsActive describe its passing requirement, validity, and availability.","fields":[{"name":"Name","type":"Text","description":"Examination name"},{"name":"Description","type":"LongTextArea","description":"What this examination covers and how it is administered"},{"name":"PassingScore","type":"Number","description":"Minimum score required to pass"},{"name":"ValidityPeriod","type":"Number","description":"Number of months the result remains valid"},{"name":"IsActive","type":"Checkbox","description":"Whether this examination is currently in use"}],"relationships":[{"target":"PersonExamination","type":"parent","description":"Examinations are taken by individuals through person examination records"}]},
      {"name":"PersonExamination","type":"standard","domain":"volunteers","description":"PersonExamination records an Examination taken by a constituent Account. Name, AccountId, ExaminationId, Score, Result, ExaminationDate, and EffectiveTo capture the person, assessment, outcome, completion date, and effective period.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"AccountId","type":"Lookup","description":"The volunteer who took the examination"},{"name":"ExaminationId","type":"Lookup","description":"The examination that was taken"},{"name":"Score","type":"Number","description":"Score achieved on the examination"},{"name":"Result","type":"Checkbox","description":"Whether the volunteer passed"},{"name":"ExaminationDate","type":"Date","description":"Date the examination was completed"},{"name":"EffectiveTo","type":"Date","description":"Date when this result expires"}],"relationships":[{"target":"Account","type":"child","description":"Each exam result belongs to a volunteer account"},{"target":"Examination","type":"child","description":"References the examination definition"}]},
      {"name":"PersonLocationAvailability","type":"standard","domain":"volunteers","description":"PersonLocationAvailability associates a constituent Account with a Location where the person is available. Name, AccountId, and LocationId identify the availability record, volunteer, and applicable location for location-based matching.","fields":[{"name":"Name","type":"Text","description":"Location description"},{"name":"AccountId","type":"Lookup","description":"The volunteer who is available at this location"},{"name":"LocationId","type":"Lookup(Location)","description":"The location where the person is available (real backing for the removed City/State fields)"}],"relationships":[{"target":"Account","type":"child","description":"Each location availability belongs to a volunteer account"}]}
    ]
  },

  "grantmaking": {
    "objects": [
      {"name":"FundingOpportunity","type":"standard","domain":"grantmaking","description":"FundingOpportunity defines an outbound funding offering in Nonprofit Cloud. It stores Name, Description, FundingAmount, ApplicationDeadline, EligibilityCriteria, Status, and IsPublished so funders can manage application details and publication.","fields":[{"name":"Name","type":"Text","description":"Funding opportunity title"},{"name":"Description","type":"RichTextArea","description":"Detailed description of the funding opportunity"},{"name":"FundingAmount","type":"Currency","description":"Total funding available for this opportunity"},{"name":"ApplicationDeadline","type":"DateTime","description":"Last date to submit applications"},{"name":"EligibilityCriteria","type":"LongTextArea","description":"Requirements applicants must meet"},{"name":"Status","type":"Picklist","description":"Opportunity status: Draft, Open, Closed, Awarded"},{"name":"IsPublished","type":"Checkbox","description":"Whether visible on the grantee portal"}],"relationships":[{"target":"IndividualApplication","type":"parent","description":"Funding opportunities receive grant applications"},{"target":"Program","type":"lookup","description":"Funding opportunities may be tied to specific programs"}]},
      {"name":"IndividualApplication","type":"standard","domain":"grantmaking","description":"IndividualApplication records an organization’s request for a specific FundingOpportunity. It uses FundingOpportunityId and AccountId to identify the opportunity and applicant account and captures Name, RequestedAmount, ProjectNarrative, Status, and SubmittedDate.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated application identifier"},{"name":"FundingOpportunityId","type":"Lookup","description":"The funding opportunity being applied for"},{"name":"AccountId","type":"Lookup","description":"The organization submitting the application"},{"name":"RequestedAmount","type":"Currency","description":"Amount of funding requested"},{"name":"ProjectNarrative","type":"RichTextArea","description":"Description of the proposed project"},{"name":"Status","type":"Picklist","description":"Application status: Draft, Submitted, Under Review, Awarded, Declined"},{"name":"SubmittedDate","type":"DateTime","description":"When the application was submitted"}],"relationships":[{"target":"FundingOpportunity","type":"child","description":"Each application is for a specific funding opportunity"},{"target":"Account","type":"child","description":"Applications reference the applicant organization account"},{"target":"ApplicationReview","type":"parent","description":"Applications are evaluated through review records"},{"target":"FundingAward","type":"parent","description":"Approved applications receive funding awards"}]},
      {"name":"ApplicationReview","type":"standard","domain":"grantmaking","description":"ApplicationReview records a reviewer’s evaluation of an Individual Application. It associates ApplicationId and ReviewerId with Score, Comment, and ApplicationRecommendation for use during review and approval.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated review identifier"},{"name":"ApplicationId","type":"Lookup","description":"The application being reviewed"},{"name":"ReviewerId","type":"Lookup","description":"The user performing the review"},{"name":"Score","type":"Number","description":"Numeric evaluation score"},{"name":"Comment","type":"RichTextArea","description":"Qualitative assessment comments"},{"name":"ApplicationRecommendation","type":"Picklist","description":"Reviewer recommendation: Approve, Decline, Revise and Resubmit"}],"relationships":[{"target":"IndividualApplication","type":"child","description":"Each review evaluates a specific application"}]},
      {"name":"Budget","type":"standard","domain":"grantmaking","description":"Budget captures the categorized financial details submitted for grant review. It records Category, RequestedAmount, ApprovedAmount, and Justification so requested and approved values can be reviewed together.","fields":[{"name":"Name","type":"Text","description":"Budget name or category"},{"name":"Category","type":"Picklist","description":"Budget category: Personnel, Direct Costs, Overhead, Travel, Equipment"},{"name":"RequestedAmount","type":"Currency","description":"Amount requested for this budget line"},{"name":"ApprovedAmount","type":"Currency","description":"Amount approved for this budget line"},{"name":"Justification","type":"LongTextArea","description":"Narrative explaining why this cost is necessary"}],"relationships":[{"target":"FundingAward","type":"lookup","description":"Approved budgets inform funding award amounts"}]},
      {"name":"FundingAward","type":"standard","domain":"grantmaking","description":"FundingAward represents outbound funding approved for an Individual Application and awardee. It uses IndividualApplicationId and AwardeeId and tracks Name, Amount, AwardDate, and Status.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated award identifier"},{"name":"IndividualApplicationId","type":"Lookup","description":"The approved application"},{"name":"AwardeeId","type":"Lookup","description":"The grantee organization account"},{"name":"Amount","type":"Currency","description":"Total approved funding amount"},{"name":"AwardDate","type":"Date","description":"Date the award was granted"},{"name":"Status","type":"Picklist","description":"Award status: Active, Completed, Suspended, Terminated"}],"relationships":[{"target":"IndividualApplication","type":"child","description":"Each award results from an approved application"},{"target":"Account","type":"child","description":"Awards are linked to the grantee organization"}]}
    ]
  },

  "agentforce": {
    "objects": [

    ]
  },

  "action_plans": {
    "objects": [
      {"name":"ActionPlan","type":"standard","domain":"action_plans","description":"ActionPlan represents an executable plan created from an Action Plan Template for a target record. Its Name, ActionPlanTemplateId, TargetId, Status, StartDate, and CompletionPercentage fields identify the process, its context, its starting point, and its overall progress.","fields":[{"name":"Name","type":"Text","description":"Action plan name, usually derived from the template"},{"name":"ActionPlanTemplateVersionId","type":"Lookup","description":"The template used to create this plan"},{"name":"TargetId","type":"Lookup","description":"The record this plan is applied to (polymorphic: Opportunity, Case, Initiative)"},{"name":"ActionPlanState","type":"Picklist","description":"Plan status: Not Started, In Progress, Completed"},{"name":"StartDate","type":"Date","description":"Date the plan was initiated"}],"relationships":[{"target":"ActionPlanTemplate","type":"child","description":"Each plan is created from a template"},{"target":"ActionPlanItem","type":"parent","description":"Plans contain task items to be completed"}]},
      {"name":"ActionPlanTemplate","type":"standard","domain":"action_plans","description":"ActionPlanTemplate defines a reusable set of tasks for a business process. Its Name and Description explain the process, TargetObjectType identifies the records to which it applies, and IsActive indicates whether the template is active.","fields":[{"name":"Name","type":"Text","description":"Template name describing the process"},{"name":"Description","type":"LongTextArea","description":"Detailed description of when to use this template"},{"name":"TargetEntityType","type":"Picklist","description":"Object type this template applies to: Opportunity, Case, Initiative"},{"name":"Status","type":"Checkbox","description":"Whether this template is available for use"}],"relationships":[{"target":"ActionPlan","type":"parent","description":"Templates are used to create action plan instances"},{"target":"ActionPlanTemplateItem","type":"parent","description":"Templates contain template item definitions"}]},
      {"name":"ActionPlanTemplateItem","type":"standard","domain":"action_plans","description":"ActionPlanTemplateItem defines a task within an Action Plan Template. Its Description, DaysFromStart, Priority, and DependsOnItemId fields capture the task details, relative timing, importance, and dependency, while ActionPlanTemplateId associates it with its template.","fields":[{"name":"Name","type":"Text","description":"Task name"},{"name":"ActionPlanTemplateVersionId","type":"Lookup","description":"The parent template"}],"relationships":[{"target":"ActionPlanTemplate","type":"child","description":"Each item belongs to a template"}]},
      {"name":"ActionPlanItem","type":"standard","domain":"action_plans","description":"ActionPlanItem represents an individual task generated for an ActionPlan. Its AssignedToId, DueDate, Status, and Priority fields identify who is responsible, when the task is due, and how the task is tracked during execution.","fields":[{"name":"Name","type":"Text","description":"Task name from the template item"},{"name":"ActionPlanId","type":"Lookup","description":"The parent action plan"},{"name":"ItemState","type":"Picklist","description":"Task status: Not Started, In Progress, Completed"}],"relationships":[{"target":"ActionPlan","type":"child","description":"Each item belongs to an action plan"}]},
      {"name":"StageDefinition","type":"metadata","domain":"action_plans","description":"StageDefinition defines an ordered stage for records of a specified object type. Its Name, ObjectType, StageOrder, and Description fields characterize the stage, while ActionPlanTemplateId can associate it with a repeatable task process.","fields":[{"name":"masterLabel","type":"Text","description":"Stage name"},{"name":"referenceObject","type":"Picklist","description":"The object this stage applies to: Initiative, Position, Assignment"},{"name":"Description","type":"LongTextArea","description":"Description of what this stage represents"}],"relationships":[]},
      {"name":"ActionPlanTemplateVersion","type":"standard","domain":"action_plans","description":"A version of an Action Plan Template. Templates are versioned: template items belong to a version, and an ActionPlan is instantiated from a specific template version. Publication lifecycle (Status) and activation/inactivation timestamps live at the version level.","fields":[{"name":"Name","type":"Text","description":"Version name"},{"name":"ActionPlanTemplateId","type":"Lookup","description":"Parent template this version belongs to"},{"name":"Status","type":"Picklist","description":"Publication lifecycle: Draft / Final-Published / Obsolete / ReadOnly"},{"name":"ActivationDateTime","type":"DateTime","description":"When the version became active"},{"name":"InactivationDateTime","type":"DateTime","description":"When the version was inactivated"}],"relationships":[{"target":"ActionPlanTemplate","type":"child","description":"Each version belongs to a template (ActionPlanTemplateId)."},{"target":"ActionPlanTemplateItem","type":"parent","description":"Template items belong to a version (ActionPlanTemplateVersionId)."},{"target":"ActionPlan","type":"parent","description":"Action plans are instantiated from a version (ActionPlan.ActionPlanTemplateVersionId)."}]}
    ]
  },

  "security": {
    "objects": [
      {"name":"PermissionSetGroup","type":"standard","domain":"security","description":"PermissionSetGroup represents a consolidated assignment of related permission sets. In Nonprofit Cloud, groups can combine managed permissions with custom and muting permission sets so users retain updated default access while receiving organization-specific additions or restrictions.","fields":[],"relationships":[]},
      {"name":"PermissionSetLicense","type":"standard","domain":"security","description":"PermissionSetLicense represents a license prerequisite for permissions associated with certain Salesforce capabilities. For example, gift acknowledgment document generation requires designated administrators to receive the DocGen Designer permission set license.","fields":[],"relationships":[]}
    ]
  },

  "setup": {
    "objects": [

    ],
    "metadata": [
      {"type":"NonprofitCloudSetting__mdt","name":"Nonprofit Cloud Settings","fields":{"FundraisingEnabled__c":"Checkbox","ProgramManagementEnabled__c":"Checkbox","VolunteerManagementEnabled__c":"Checkbox","GrantmakingEnabled__c":"Checkbox","OutcomeManagementEnabled__c":"Checkbox"},"description":"NonprofitCloudSetting__mdt represents configuration metadata for Nonprofit Cloud settings. These settings support centrally managed product behavior alongside feature-specific setup and permissions."},
      {"type":"DataProcessingEngineDefinition__mdt","name":"Data Processing Engine Definitions","fields":{"SourceObject__c":"Text","TargetObject__c":"Text","CalculationType__c":"Picklist","IsActive__c":"Checkbox"},"description":"DataProcessingEngineDefinition__mdt represents configuration metadata associated with Data Processing Engine definitions. Definitions describe transformations that process organizational data and write calculated results used by Nonprofit Cloud rollups and summaries."}
    ]
  }

};
