export default {

  "constituents": {
    "objects": [
      {"name":"Account","type":"standard","domain":"constituents","description":"Account is the central constituent record for individuals represented as Person Accounts and for organizations, households, or other groups represented as Business Accounts. Name and RecordTypeId identify the record and its account model, while ParentId, Type, BillingAddress, and Phone support hierarchy, classification, address, and contact details.","fields":[{"name":"Name","type":"Text","description":"Account name; auto-populated from first/last name for Person Accounts"},{"name":"RecordTypeId","type":"Lookup","description":"Distinguishes Person Accounts from Business Accounts"},{"name":"ParentId","type":"Lookup","description":"Parent account for modeling organizational hierarchies"},{"name":"Type","type":"Picklist","description":"Account classification such as Donor, Foundation, Partner, or Vendor"},{"name":"BillingAddress","type":"Text","description":"Primary billing address compound field"},{"name":"Phone","type":"Phone","description":"Primary phone number for the account"}],"relationships":[{"target":"Contact","type":"parent","description":"Person Accounts have an associated Contact record that stores individual-specific fields"},{"target":"ContactProfile","type":"parent","description":"Accounts can have a Contact Profile with extended fundraising attributes"},{"target":"AccountContactRelationship","type":"parent","description":"Accounts are linked to contacts through Account Contact Relationships for household and organizational membership"},{"target":"ContactPointAddress","type":"parent","description":"Accounts have one or more contact point addresses"}]},
      {"name":"Contact","type":"standard","domain":"constituents","description":"Contact stores an individual associated with an Account, including FirstName, LastName, Email, and Birthdate. AccountId links the Contact to the applicable Business Account in account models that use contacts with organizations.","fields":[{"name":"FirstName","type":"Text","description":"Individual's first name"},{"name":"LastName","type":"Text","description":"Individual's last name"},{"name":"Email","type":"Email","description":"Primary email address"},{"name":"Birthdate","type":"Date","description":"Date of birth for age-based segmentation and reporting"},{"name":"AccountId","type":"Lookup","description":"The Account this Contact is associated with"}],"relationships":[{"target":"Account","type":"child","description":"Each Contact belongs to an Account; for Person Accounts this is a one-to-one relationship"},{"target":"ContactContactRelationship","type":"parent","description":"Contacts participate in interpersonal relationships"},{"target":"OpportunityContactRole","type":"parent","description":"Contacts are linked to fundraising opportunities through contact roles"}]},
      {"name":"ContactProfile","type":"custom","domain":"constituents","description":"ContactProfile stores fundraising-specific information related to a constituent Account. Name and AccountId identify and associate the profile, while DonorClassification and RecurringDonorType capture donor attributes used by fundraising processes.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated profile identifier"},{"name":"AccountId","type":"Lookup","description":"The constituent account this profile extends"},{"name":"DonorClassification","type":"Picklist","description":"Donor segmentation category such as Major Donor, Mid-Level, or Annual Fund"},{"name":"RecurringDonorType","type":"Picklist","description":"Indicates whether the constituent is a sustaining, lapsed, or prospective recurring donor"}],"relationships":[{"target":"Account","type":"child","description":"Each Contact Profile belongs to a single constituent account"},{"target":"GiftCommitment","type":"lookup","description":"Contact profiles inform recurring commitment tracking and donor classification"}]}
    ]
  },

  "households": {
    "objects": [
      {"name":"PartyRelationshipGroup","type":"custom","domain":"households","description":"PartyRelationshipGroup represents a named household or other group associated with an account. Its Type, StartDate, and EndDate fields classify the group and define the period during which it applies.","fields":[{"name":"Name","type":"Text","description":"Display name for the group, often the household surname"},{"name":"Type","type":"Picklist","description":"Group classification such as Household, Affinity Group, or Board"},{"name":"AccountId","type":"Lookup","description":"The Business Account that represents this group"},{"name":"StartDate","type":"Date","description":"Date when the group was established"},{"name":"EndDate","type":"Date","description":"Date when the group was dissolved, if applicable"}],"relationships":[{"target":"Account","type":"child","description":"Each group is represented by a Business Account"},{"target":"AccountContactRelationship","type":"parent","description":"Group membership is tracked through Account Contact Relationship records"}]},
      {"name":"AccountContactRelationship","type":"standard","domain":"households","description":"AccountContactRelationship connects a contact to an account for household or other group membership. Roles, IsActive, StartDate, and EndDate describe the member’s participation and the period for which the relationship applies.","fields":[{"name":"AccountId","type":"Lookup","description":"The organization or group account"},{"name":"ContactId","type":"Lookup","description":"The individual contact being linked to the account"},{"name":"Roles","type":"MultiPicklist","description":"One or more roles the individual holds in the organization (Head of Household, Member, Board Member)"},{"name":"IsActive","type":"Checkbox","description":"Whether the relationship is currently active"},{"name":"StartDate","type":"Date","description":"Date when the relationship began"},{"name":"EndDate","type":"Date","description":"Date when the relationship ended, if applicable"}],"relationships":[{"target":"Account","type":"child","description":"Each ACR links to the organization or group account"},{"target":"Contact","type":"child","description":"Each ACR links to the individual contact"},{"target":"PartyRelationshipGroup","type":"lookup","description":"ACRs connect individuals to Party Relationship Group households"}]}
    ]
  },

  "relationships": {
    "objects": [
      {"name":"ContactContactRelationship","type":"custom","domain":"relationships","description":"ContactContactRelationship connects the contact in ContactId with the contact in RelatedContactId and uses RoleId to describe their relationship. Name identifies the record, while IsActive and StartDate indicate whether the connection is current and when it began.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated relationship identifier"},{"name":"ContactId","type":"Lookup","description":"The first individual in the relationship"},{"name":"RelatedContactId","type":"Lookup","description":"The second individual in the relationship"},{"name":"RoleId","type":"Lookup","description":"The Party Role Relationship defining the type (e.g., Spouse, Parent)"},{"name":"IsActive","type":"Checkbox","description":"Whether the relationship is currently active"},{"name":"StartDate","type":"Date","description":"Date when the relationship began"}],"relationships":[{"target":"Contact","type":"child","description":"Links to the first individual in the relationship"},{"target":"PartyRoleRelationship","type":"child","description":"References the party role that defines the relationship type and reciprocal labels"}]},
      {"name":"AccountAccountRelationship","type":"custom","domain":"relationships","description":"AccountAccountRelationship connects the account in AccountId with the account in RelatedAccountId and uses RoleId to classify the connection. Name identifies the record, and IsActive indicates whether the relationship is current.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated relationship identifier"},{"name":"AccountId","type":"Lookup","description":"The first organization in the relationship"},{"name":"RelatedAccountId","type":"Lookup","description":"The second organization in the relationship"},{"name":"RoleId","type":"Lookup","description":"The Party Role Relationship defining the relationship type"},{"name":"IsActive","type":"Checkbox","description":"Whether the organizational relationship is currently active"}],"relationships":[{"target":"Account","type":"child","description":"Links to the first organization account"},{"target":"PartyRoleRelationship","type":"child","description":"References the party role defining the relationship type"}]},
      {"name":"PartyRoleRelationship","type":"custom","domain":"relationships","description":"PartyRoleRelationship defines an available relationship role using Name, ReciprocalLabel, and RelationshipType. IsActive indicates whether the definition is available for use with relationship records.","fields":[{"name":"Name","type":"Text","description":"Forward-direction label for the relationship (e.g., Parent)"},{"name":"ReciprocalLabel","type":"Text","description":"Reverse-direction label (e.g., Child)"},{"name":"RelationshipType","type":"Picklist","description":"Category of relationship (Family, Professional, Community)"},{"name":"IsActive","type":"Checkbox","description":"Whether this relationship type is available for selection"}],"relationships":[{"target":"ContactContactRelationship","type":"parent","description":"Party roles are used by Contact Contact Relationships"},{"target":"AccountAccountRelationship","type":"parent","description":"Party roles are used by Account Account Relationships"}]}
    ]
  },

  "contact_points": {
    "objects": [
      {"name":"ContactPointAddress","type":"standard","domain":"contact_points","description":"ContactPointAddress stores a named address associated with an account through ParentId. It records the address type, street, city, state, postal code, and country, while IsPrimary identifies the account's primary address.","fields":[{"name":"Name","type":"Text","description":"Display label for this address record"},{"name":"ParentId","type":"Lookup","description":"The Account this address belongs to (polymorphic)"},{"name":"AddressType","type":"Picklist","description":"Classification such as Home, Work, Vacation, or Other"},{"name":"Street","type":"TextArea","description":"Street address lines"},{"name":"City","type":"Text","description":"City name"},{"name":"StateCode","type":"Picklist","description":"State or province code"},{"name":"PostalCode","type":"Text","description":"Postal or ZIP code"},{"name":"CountryCode","type":"Picklist","description":"Country code"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the preferred mailing address"}],"relationships":[{"target":"Account","type":"child","description":"Each address belongs to a constituent account"},{"target":"PartyRelationshipGroup","type":"lookup","description":"Household members may share addresses through the group"}]},
      {"name":"ContactPointEmail","type":"standard","domain":"contact_points","description":"ContactPointEmail stores a named email address associated with an account through ParentId. EmailType classifies the address, and IsPrimary identifies the primary email record.","fields":[{"name":"Name","type":"Text","description":"Display label for this email record"},{"name":"ParentId","type":"Lookup","description":"The Account this email belongs to (polymorphic)"},{"name":"EmailAddress","type":"Email","description":"The email address"},{"name":"EmailType","type":"Picklist","description":"Classification such as Personal, Work, or Other"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the preferred email address"}],"relationships":[{"target":"Account","type":"child","description":"Each email belongs to a constituent account"}]},
      {"name":"ContactPointPhone","type":"standard","domain":"contact_points","description":"ContactPointPhone stores a named telephone number associated with an account through ParentId. PhoneType classifies the number, and IsPrimary identifies the primary phone record.","fields":[{"name":"Name","type":"Text","description":"Display label for this phone record"},{"name":"ParentId","type":"Lookup","description":"The Account this phone number belongs to (polymorphic)"},{"name":"TelephoneNumber","type":"Phone","description":"The phone number"},{"name":"PhoneType","type":"Picklist","description":"Classification such as Home, Mobile, Work, or Fax"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the preferred phone number"}],"relationships":[{"target":"Account","type":"child","description":"Each phone number belongs to a constituent account"}]}
    ]
  },

  "fundraising": {
    "objects": [
      {"name":"Opportunity","type":"standard","domain":"fundraising","description":"Opportunity is the standard Salesforce record used to track a fundraising ask through its solicitation pipeline. Name, Amount, StageName, CloseDate, and Probability describe the ask and its progress, while AccountId, CampaignId, and RecordTypeId associate it with the donor or organization, campaign source, and configured fundraising process.","fields":[{"name":"Name","type":"Text","description":"Descriptive name for the solicitation or proposal"},{"name":"Amount","type":"Currency","description":"Expected gift amount for the opportunity"},{"name":"StageName","type":"Picklist","description":"Current pipeline stage (Prospecting, Cultivation, Solicitation, Closed Won)"},{"name":"CloseDate","type":"Date","description":"Expected or actual close date"},{"name":"Probability","type":"Percent","description":"Likelihood of winning the opportunity"},{"name":"AccountId","type":"Lookup","description":"The donor or organization account"},{"name":"CampaignId","type":"Lookup","description":"The campaign that sourced this opportunity"},{"name":"RecordTypeId","type":"Lookup","description":"Distinguishes major gifts, grants, planned giving, and other fundraising types"}],"relationships":[{"target":"Account","type":"child","description":"Each opportunity is associated with a donor account"},{"target":"Campaign","type":"child","description":"Opportunities are sourced from campaigns"},{"target":"OpportunityContactRole","type":"parent","description":"Opportunities have contact roles identifying involved individuals"},{"target":"GiftCommitment","type":"lookup","description":"Won opportunities can become gift commitments"}]},
      {"name":"OpportunityContactRole","type":"standard","domain":"fundraising","description":"OpportunityContactRole links a constituent contact to an Opportunity and records that contact's participation in the ask. OpportunityId and ContactId establish the relationship, Role describes the contact's involvement, and IsPrimary identifies the primary contact; these roles also drive soft-credit recognition.","fields":[{"name":"OpportunityId","type":"Lookup","description":"The opportunity this contact role belongs to"},{"name":"ContactId","type":"Lookup","description":"The individual involved in the opportunity"},{"name":"Role","type":"Picklist","description":"The person's role (Primary Donor, Influencer, Decision Maker, Soft Credit)"},{"name":"IsPrimary","type":"Checkbox","description":"Whether this is the primary contact for the opportunity"}],"relationships":[{"target":"Opportunity","type":"child","description":"Each contact role belongs to an opportunity"},{"target":"Contact","type":"child","description":"Each contact role references an individual"},{"target":"GiftSoftCredit","type":"lookup","description":"Contact roles can inform soft credit attribution"}]}
    ],
    "metadata": [
      {"type":"FundraisingSetting__mdt","name":"Fundraising Settings","fields":{"InstallmentExtensionDayCount__c":"Number","LapsedUnpaidTransactionCount__c":"Number","FailingTransactionCount__c":"Number","AutoCloseEnabled__c":"Checkbox"},"description":"FundraisingSetting__mdt stores Fundraising Settings used to configure fundraising behavior in Nonprofit Cloud. Administrators manage Fundraising settings in Setup, including settings that can temporarily pause gift transaction, gift commitment, and gift commitment schedule validations during bulk migration; those validation pauses should be turned off when migration is complete."}
    ]
  },

  "gift_commitments": {
    "objects": [
      {"name":"GiftCommitment","type":"custom","domain":"gift_commitments","description":"GiftCommitment represents a donor’s promised gift and records its Name, AccountId, CommitmentType, Status, TotalAmount, and StartDate. CampaignId and OpportunityId connect the commitment to the fundraising campaign or opportunity associated with the gift.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated commitment identifier"},{"name":"AccountId","type":"Lookup","description":"The donor account making the commitment"},{"name":"CommitmentType","type":"Picklist","description":"Type of commitment: Recurring or Custom"},{"name":"Status","type":"Picklist","description":"Lifecycle status: Draft, Active, Paused, Lapsed, Failing, or Closed"},{"name":"TotalAmount","type":"Currency","description":"Total committed amount across all installments"},{"name":"CampaignId","type":"Lookup","description":"The campaign that sourced this commitment"},{"name":"OpportunityId","type":"Lookup","description":"The originating fundraising opportunity"},{"name":"StartDate","type":"Date","description":"Date when the commitment begins"}],"relationships":[{"target":"Account","type":"child","description":"Each commitment belongs to a donor account"},{"target":"GiftCommitmentSchedule","type":"parent","description":"Commitments have one or more schedules defining installment patterns"},{"target":"GiftTransaction","type":"parent","description":"Commitments generate gift transactions for each installment"},{"target":"Opportunity","type":"child","description":"Commitments can originate from fundraising opportunities"}]},
      {"name":"GiftCommitmentSchedule","type":"custom","domain":"gift_commitments","description":"GiftCommitmentSchedule defines payment timing for a commitment through GiftCommitmentId, Frequency, InstallmentAmount, DayOfMonth, EffectiveStartDate, and EffectiveEndDate. Its Name identifies the schedule, which Nonprofit Cloud uses when processing the commitment and related gift transactions.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated schedule identifier"},{"name":"GiftCommitmentId","type":"Lookup","description":"The parent gift commitment"},{"name":"Frequency","type":"Picklist","description":"Installment frequency: Monthly, Quarterly, Annually, or Custom"},{"name":"InstallmentAmount","type":"Currency","description":"Amount per installment payment"},{"name":"DayOfMonth","type":"Number","description":"Day of the month on which installments are due"},{"name":"EffectiveStartDate","type":"Date","description":"Date when this schedule becomes active"},{"name":"EffectiveEndDate","type":"Date","description":"Date when this schedule stops generating transactions"}],"relationships":[{"target":"GiftCommitment","type":"child","description":"Each schedule belongs to a gift commitment"},{"target":"PaymentInstrument","type":"lookup","description":"Schedules reference the payment method used for installments"}]},
      {"name":"GiftCommitmentChangeAttributionLog","type":"custom","domain":"gift_commitments","description":"GiftCommitmentChangeAttributionLog records an attributed change to a commitment through GiftCommitmentId, ChangeType, ChangeDate, and PerDayAmountChange. CampaignId and OutreachSourceCodeId associate the modification with relevant fundraising outreach, while Name identifies the log record.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated log entry identifier"},{"name":"GiftCommitmentId","type":"Lookup","description":"The commitment that was changed"},{"name":"ChangeType","type":"Picklist","description":"Type of change: Upgrade, Downgrade, Pause, Resume, Payment Method Change"},{"name":"PerDayAmountChange","type":"Currency","description":"Daily amount impact of the change for ROI calculation"},{"name":"CampaignId","type":"Lookup","description":"The campaign that influenced this change"},{"name":"OutreachSourceCodeId","type":"Lookup","description":"The specific outreach source code that drove the change"},{"name":"ChangeDate","type":"DateTime","description":"Timestamp when the change was made"}],"relationships":[{"target":"GiftCommitment","type":"child","description":"Each log entry references the modified commitment"},{"target":"Campaign","type":"child","description":"Changes are attributed to campaigns for ROI analysis"}]}
    ]
  },

  "gift_transactions": {
    "objects": [
      {"name":"GiftTransaction","type":"custom","domain":"gift_transactions","description":"GiftTransaction records an individual donation or payment and identifies its donor account, amount, status, received date, payment method, and gift vehicle. It can relate the payment to a gift commitment, campaign, outreach source code, acknowledgment status, and a matching employer transaction.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated transaction identifier"},{"name":"AccountId","type":"Lookup","description":"The donor account for this transaction"},{"name":"Amount","type":"Currency","description":"Transaction amount received or expected"},{"name":"Status","type":"Picklist","description":"Transaction lifecycle: Unpaid, Pending, Paid, Failed, Canceled, Refunded, Written Off"},{"name":"GiftReceivedDate","type":"Date","description":"Date the gift was received"},{"name":"PaymentMethod","type":"Picklist","description":"How the donor paid: Credit Card, Check, ACH, Wire, Cash"},{"name":"GiftVehicle","type":"Picklist","description":"Gift type: Cash, Check, Credit Card, Stock, Wire Transfer, In-Kind"},{"name":"GiftCommitmentId","type":"Lookup","description":"The commitment this transaction fulfills, if applicable"},{"name":"CampaignId","type":"Lookup","description":"Campaign attribution for this transaction"},{"name":"OutreachSourceCodeId","type":"Lookup","description":"Granular outreach source code for attribution"},{"name":"AcknowledgmentStatus","type":"Picklist","description":"Whether the donor has been thanked: Not Sent, Sent, Failed"},{"name":"MatchingEmployerTransactionId","type":"Lookup","description":"Links to the corporate matching gift transaction"}],"relationships":[{"target":"Account","type":"child","description":"Each transaction belongs to a donor account"},{"target":"GiftCommitment","type":"child","description":"Transactions fulfill commitment installments"},{"target":"Campaign","type":"child","description":"Transactions are attributed to campaigns"},{"target":"GiftTransactionDesignation","type":"parent","description":"Transactions are allocated to designations through junction records"},{"target":"GiftSoftCredit","type":"parent","description":"Transactions can have soft credit recipients"}]},
      {"name":"PaymentInstrument","type":"custom","domain":"gift_transactions","description":"PaymentInstrument stores payment information associated with an account, including the payment type, last four digits, expiration date, and active status. Nonprofit Cloud can create a payment instrument when ACH or credit card details with at least the last four digits are supplied during supported commitment schedule or transaction workflows.","fields":[{"name":"Name","type":"Text","description":"Display name for the payment method (e.g., Visa ending 4242)"},{"name":"AccountId","type":"Lookup","description":"The donor account that owns this payment instrument"},{"name":"PaymentType","type":"Picklist","description":"Type of payment: Credit Card, ACH, Bank Transfer"},{"name":"LastFourDigits","type":"Text","description":"Last four digits of the card or account number"},{"name":"ExpirationDate","type":"Date","description":"Expiration date for credit card instruments"},{"name":"IsActive","type":"Checkbox","description":"Whether this payment instrument is currently active"}],"relationships":[{"target":"Account","type":"child","description":"Each payment instrument belongs to a donor account"},{"target":"GiftCommitmentSchedule","type":"lookup","description":"Payment instruments are linked to commitment schedules for recurring processing"}]}
    ]
  },

  "gift_entry": {
    "objects": [
      {"name":"GiftEntry","type":"custom","domain":"gift_entry","description":"GiftEntry stores donation information awaiting or undergoing processing, including Name, DonorAccountId, Amount, PaymentMethod, and optional GiftBatchId. ProcessingStatus and ProcessingResult record the outcome of converting the entry into related fundraising records such as gift transactions and commitments.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated entry identifier"},{"name":"DonorAccountId","type":"Lookup","description":"The donor account for this gift entry"},{"name":"Amount","type":"Currency","description":"Gift amount to be processed"},{"name":"PaymentMethod","type":"Picklist","description":"How the donor is paying"},{"name":"GiftBatchId","type":"Lookup","description":"The batch this entry belongs to, if applicable"},{"name":"ProcessingStatus","type":"Picklist","description":"Entry status: Draft, Ready, Processing, Completed, Failed"},{"name":"ProcessingResult","type":"LongTextArea","description":"Processing outcome details including any error messages"}],"relationships":[{"target":"Account","type":"child","description":"Each gift entry references a donor account"},{"target":"GiftBatch","type":"child","description":"Entries are grouped in batches for bulk processing"},{"target":"GiftTransaction","type":"lookup","description":"Processing creates a gift transaction from each entry"}]},
      {"name":"GiftBatch","type":"custom","domain":"gift_entry","description":"GiftBatch groups gift entries for validation and processing under the template identified by GiftBatchTemplateId. Name, ExpectedGiftCount, and EstimatedValue describe the batch, while Status and ProcessedDate track its processing lifecycle.","fields":[{"name":"Name","type":"Text","description":"Descriptive name for the batch"},{"name":"GiftBatchTemplateId","type":"Lookup","description":"The template controlling which fields appear in the batch"},{"name":"ExpectedGiftCount","type":"Number","description":"Expected number of gifts for reconciliation"},{"name":"EstimatedValue","type":"Currency","description":"Expected total value for reconciliation"},{"name":"Status","type":"Picklist","description":"Batch status: Open, Processing, Completed, Partially Processed"},{"name":"ProcessedDate","type":"DateTime","description":"Timestamp when the batch was processed"}],"relationships":[{"target":"GiftEntry","type":"parent","description":"Batches contain multiple gift entries"},{"target":"GiftBatchTemplate","type":"child","description":"Each batch uses a template for field configuration"}]},
      {"name":"GiftBatchTemplate","type":"custom","domain":"gift_entry","description":"GiftBatchTemplate defines the fields and presentation used when entering gifts for a batch. Name and Description identify the template, FieldConfiguration stores its configured entry layout, and IsActive indicates whether the template is available for use.","fields":[{"name":"Name","type":"Text","description":"Template name describing its purpose"},{"name":"Description","type":"LongTextArea","description":"Explanation of when to use this template"},{"name":"FieldConfiguration","type":"LongTextArea","description":"JSON configuration of fields, order, and defaults"},{"name":"IsActive","type":"Checkbox","description":"Whether this template is available for use"}],"relationships":[{"target":"GiftBatch","type":"parent","description":"Templates are applied to gift batches"}]}
    ]
  },

  "designations": {
    "objects": [
      {"name":"GiftDesignation","type":"custom","domain":"designations","description":"GiftDesignation represents a named fund or purpose to which gifts can be allocated. Its fields identify whether the designation is active or the organization-wide default and store its description, total amount, and transaction count for tracking and rollup use.","fields":[{"name":"Name","type":"Text","description":"Fund or purpose name displayed to donors and staff"},{"name":"IsActive","type":"Checkbox","description":"Whether this designation is available for gift allocation"},{"name":"IsDefault","type":"Checkbox","description":"Whether this is the org-wide default designation for unrestricted gifts"},{"name":"TotalAmount","type":"Currency","description":"Rollup total of all allocated gift transaction amounts"},{"name":"TransactionCount","type":"Number","description":"Rollup count of gift transactions allocated to this designation"},{"name":"Description","type":"LongTextArea","description":"Description of the fund's purpose and restrictions"}],"relationships":[{"target":"GiftTransactionDesignation","type":"parent","description":"Designations receive allocations through gift transaction designation junction records"},{"target":"GiftDefaultDesignation","type":"parent","description":"Designations can be set as defaults at various levels"}]},
      {"name":"GiftTransactionDesignation","type":"custom","domain":"designations","description":"GiftTransactionDesignation links a gift transaction to a gift designation and records the allocated Amount and Percent. Multiple records can divide one transaction among several designations, with any remaining allocation assigned to the organization-wide default.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated allocation identifier"},{"name":"GiftTransactionId","type":"Lookup","description":"The gift transaction being allocated"},{"name":"GiftDesignationId","type":"Lookup","description":"The designation receiving the allocation"},{"name":"Amount","type":"Currency","description":"Dollar amount allocated to this designation"},{"name":"Percent","type":"Percent","description":"Percentage of the transaction allocated to this designation"}],"relationships":[{"target":"GiftTransaction","type":"child","description":"Each allocation belongs to a gift transaction"},{"target":"GiftDesignation","type":"child","description":"Each allocation references a gift designation fund"}]},
      {"name":"GiftDefaultDesignation","type":"custom","domain":"designations","description":"GiftDefaultDesignation associates a gift designation with a parent fundraising record so that its allocation can be inherited during commitment or gift processing. Its fields identify the designation and parent record and provide a Priority value for the default relationship.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated default designation identifier"},{"name":"GiftDesignationId","type":"Lookup","description":"The designation to use as the default"},{"name":"ParentRecordId","type":"Lookup","description":"The campaign, commitment, or opportunity this default applies to (polymorphic)"},{"name":"Priority","type":"Number","description":"Priority level in the inheritance hierarchy"}],"relationships":[{"target":"GiftDesignation","type":"child","description":"Each default references a gift designation"},{"target":"Campaign","type":"lookup","description":"Default designations can be set at the campaign level"},{"target":"GiftCommitment","type":"lookup","description":"Default designations can be set at the commitment level"}]}
    ]
  },

  "soft_credits": {
    "objects": [
      {"name":"GiftSoftCredit","type":"custom","domain":"soft_credits","description":"GiftSoftCredit records attribute recognition for a Gift Transaction to a person, business, household member, or other account that influenced the gift. Fields including Name, GiftTransactionId, AccountId, CreditType, Amount, and Description identify the transaction, recipient, attribution role, credited amount, and supporting details.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated soft credit identifier"},{"name":"GiftTransactionId","type":"Lookup","description":"The gift transaction being credited"},{"name":"AccountId","type":"Lookup","description":"The constituent account receiving the soft credit"},{"name":"CreditType","type":"Picklist","description":"Type of credit: Influence, Tribute, Solicitation, Household Member, Matching"},{"name":"Amount","type":"Currency","description":"Amount of the soft credit, which may be partial"},{"name":"Description","type":"TextArea","description":"Notes about why this credit was given"}],"relationships":[{"target":"GiftTransaction","type":"child","description":"Each soft credit references a gift transaction"},{"target":"Account","type":"child","description":"Each soft credit is attributed to a constituent account"},{"target":"ContactContactRelationship","type":"lookup","description":"Relationships between constituents inform soft credit decisions"}]}
    ]
  },

  "campaigns": {
    "objects": [
      {"name":"Campaign","type":"standard","domain":"campaigns","description":"Campaign represents a fundraising or outreach effort in Nonprofit Cloud and connects that effort to opportunities, gift commitments, gift transactions, Outreach Source Codes, and default designations. Name, Type, Status, StartDate, EndDate, BudgetedCost, ExpectedRevenue, and ActualCost capture identifying, scheduling, and financial information used to manage and assess the campaign.","fields":[{"name":"Name","type":"Text","description":"Campaign name"},{"name":"Type","type":"Picklist","description":"Campaign type: Appeal, Event, Direct Mail, Digital, Phonathon"},{"name":"Status","type":"Picklist","description":"Campaign lifecycle: Planned, In Progress, Completed, Aborted"},{"name":"StartDate","type":"Date","description":"Campaign start date"},{"name":"EndDate","type":"Date","description":"Campaign end date"},{"name":"BudgetedCost","type":"Currency","description":"Planned budget for the campaign"},{"name":"ExpectedRevenue","type":"Currency","description":"Expected total revenue from the campaign"},{"name":"ActualCost","type":"Currency","description":"Actual cost incurred"}],"relationships":[{"target":"OutreachSourceCode","type":"parent","description":"Campaigns contain outreach source codes for granular attribution"},{"target":"GiftTransaction","type":"parent","description":"Gift transactions are attributed to campaigns"},{"target":"GiftCommitment","type":"parent","description":"Gift commitments are linked to campaigns"},{"target":"Opportunity","type":"parent","description":"Fundraising opportunities are sourced from campaigns"}]},
      {"name":"OutreachSourceCode","type":"custom","domain":"campaigns","description":"OutreachSourceCode represents a specific outreach method associated with a campaign and is used to attribute gifts received in response to a solicitation. Name, CampaignId, Channel, Message, Audience, and IsActive identify the related campaign, outreach approach, intended audience, and whether the code is available for use.","fields":[{"name":"Name","type":"Text","description":"Source code identifier, often a formatted tracking code"},{"name":"CampaignId","type":"Lookup","description":"The parent campaign"},{"name":"Channel","type":"Picklist","description":"Communication channel: Email, Direct Mail, Social, Phone, Web"},{"name":"Message","type":"Text","description":"Specific message or creative identifier"},{"name":"Audience","type":"Text","description":"Target audience segment description"},{"name":"IsActive","type":"Checkbox","description":"Whether this source code is active for attribution"}],"relationships":[{"target":"Campaign","type":"child","description":"Each source code belongs to a campaign"},{"target":"GiftTransaction","type":"parent","description":"Transactions reference source codes for granular attribution"},{"target":"GiftCommitmentChangeAttributionLog","type":"parent","description":"Commitment changes reference source codes for ROI tracking"}]}
    ]
  },

  "programs": {
    "objects": [
      {"name":"Program","type":"custom","domain":"programs","description":"Program represents a mission-driven service or initiative delivered by the organization. Name and Summary identify the program, while Status, StartDate, and EndDate describe its operating state and duration.","fields":[{"name":"Name","type":"Text","description":"Program name"},{"name":"Summary","type":"LongTextArea","description":"Detailed description of the program's purpose and activities"},{"name":"Status","type":"Picklist","description":"Program lifecycle: Active, Inactive, Planned, Completed"},{"name":"StartDate","type":"Date","description":"Date when the program begins operations"},{"name":"EndDate","type":"Date","description":"Date when the program concludes, if applicable"}],"relationships":[{"target":"Benefit","type":"parent","description":"Programs offer specific benefits and services to participants"},{"target":"ProgramEnrollment","type":"parent","description":"Participants enroll in programs"},{"target":"ProgramCohort","type":"parent","description":"Programs organize participants into cohorts"},{"target":"OutcomeDefinition","type":"lookup","description":"Programs are measured against defined outcomes"}]},
      {"name":"Benefit","type":"custom","domain":"programs","description":"Benefit represents a service, good, class, workshop, coaching session, or other assistance associated with a program. ProgramId, BenefitTypeId, and UnitOfMeasureId classify the offering, while Name and IsActive identify it and indicate whether it is available.","fields":[{"name":"Name","type":"Text","description":"Benefit name describing the service or good"},{"name":"ProgramId","type":"Lookup","description":"The program that offers this benefit"},{"name":"BenefitTypeId","type":"Lookup","description":"The type category: Coaching, Distribution, Training, etc."},{"name":"UnitOfMeasureId","type":"Lookup","description":"The unit used to measure delivery quantity"},{"name":"IsActive","type":"Checkbox","description":"Whether this benefit is currently offered"}],"relationships":[{"target":"Program","type":"child","description":"Each benefit belongs to a program"},{"target":"BenefitType","type":"child","description":"Benefits are classified by type"},{"target":"BenefitDisbursement","type":"parent","description":"Benefits are delivered through disbursement records"},{"target":"BenefitSchedule","type":"parent","description":"Benefits have delivery schedules"}]},
      {"name":"BenefitType","type":"custom","domain":"programs","description":"BenefitType classifies similar benefits so they can be tracked consistently across programs. Name and Description explain the category, and IsActive indicates whether it is available for use.","fields":[{"name":"Name","type":"Text","description":"Type name such as Coaching, Distribution, or Training"},{"name":"Description","type":"LongTextArea","description":"Explanation of what this benefit type covers"},{"name":"IsActive","type":"Checkbox","description":"Whether this type is available for classifying benefits"}],"relationships":[{"target":"Benefit","type":"parent","description":"Benefit types classify one or more benefits across programs"}]},
      {"name":"UnitOfMeasure","type":"custom","domain":"programs","description":"UnitOfMeasure defines how the quantity of a benefit is expressed, such as kits or hours. Name and Abbreviation identify the unit, while IsActive indicates whether it is available for use.","fields":[{"name":"Name","type":"Text","description":"Unit name such as Hours, Sessions, Meals, or Items"},{"name":"Abbreviation","type":"Text","description":"Short form of the unit (e.g., hrs, qty)"},{"name":"IsActive","type":"Checkbox","description":"Whether this unit is available for use"}],"relationships":[{"target":"Benefit","type":"parent","description":"Units of measure are assigned to benefits for quantity tracking"}]},
      {"name":"ProgramEnrollment","type":"custom","domain":"programs","description":"ProgramEnrollment connects a participant account to a program and tracks participation in that offering. Name, AccountId, and ProgramId identify the enrollment, while Status, EnrollmentDate, and CompletionDate record its lifecycle.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated enrollment identifier"},{"name":"AccountId","type":"Lookup","description":"The participant account"},{"name":"ProgramId","type":"Lookup","description":"The program the participant is enrolling in"},{"name":"Status","type":"Picklist","description":"Enrollment status: Applied, Enrolled, Active, Completed, Withdrawn"},{"name":"EnrollmentDate","type":"Date","description":"Date when the participant enrolled"},{"name":"CompletionDate","type":"Date","description":"Date when the participant completed or withdrew"}],"relationships":[{"target":"Account","type":"child","description":"Each enrollment references a participant account"},{"target":"Program","type":"child","description":"Each enrollment references a program"},{"target":"ProgramCohort","type":"lookup","description":"Enrollees can be assigned to cohorts within the program"}]},
      {"name":"ProgramCohort","type":"custom","domain":"programs","description":"ProgramCohort groups program participants for organized service delivery and reporting. Name and ProgramId identify the cohort, while StartDate, EndDate, and Capacity describe its operating period and intended size.","fields":[{"name":"Name","type":"Text","description":"Cohort name or identifier"},{"name":"ProgramId","type":"Lookup","description":"The program this cohort belongs to"},{"name":"StartDate","type":"Date","description":"Cohort start date"},{"name":"EndDate","type":"Date","description":"Cohort end date"},{"name":"Capacity","type":"Number","description":"Maximum number of participants in this cohort"}],"relationships":[{"target":"Program","type":"child","description":"Each cohort belongs to a program"},{"target":"ProgramCohortMember","type":"parent","description":"Cohorts contain member records linking to participants"}]},
      {"name":"ProgramCohortMember","type":"custom","domain":"programs","description":"ProgramCohortMember associates a participant account with a program cohort. Name, ProgramCohortId, and AccountId identify the membership, while Status tracks the participant's standing in the cohort.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated member identifier"},{"name":"ProgramCohortId","type":"Lookup","description":"The cohort this member belongs to"},{"name":"AccountId","type":"Lookup","description":"The participant account"},{"name":"Status","type":"Picklist","description":"Membership status: Active, Inactive, Completed"}],"relationships":[{"target":"ProgramCohort","type":"child","description":"Each member record belongs to a cohort"},{"target":"Account","type":"child","description":"Each member references a participant account"}]},
      {"name":"BenefitDisbursement","type":"custom","domain":"programs","description":"BenefitDisbursement records a quantity of a benefit delivered or expected to be delivered to a participant. Name, AccountId, and BenefitId identify the record, while Quantity, DisbursementDate, and Status track the delivery.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated disbursement identifier"},{"name":"AccountId","type":"Lookup","description":"The participant receiving the benefit"},{"name":"BenefitId","type":"Lookup","description":"The benefit being delivered"},{"name":"Quantity","type":"Number","description":"Amount delivered in the benefit's unit of measure"},{"name":"DisbursementDate","type":"Date","description":"Date of service delivery"},{"name":"Status","type":"Picklist","description":"Delivery status: Scheduled, Delivered, Missed, Canceled"}],"relationships":[{"target":"Benefit","type":"child","description":"Each disbursement delivers a specific benefit"},{"target":"Account","type":"child","description":"Each disbursement goes to a participant account"},{"target":"BenefitSession","type":"lookup","description":"Disbursements may be linked to scheduled benefit sessions"}]},
      {"name":"BenefitSchedule","type":"custom","domain":"programs","description":"BenefitSchedule defines a recurring or time-bounded plan for delivering a benefit. Name and BenefitId identify the schedule, while Frequency, StartDate, and EndDate describe its recurrence and duration.","fields":[{"name":"Name","type":"Text","description":"Schedule name describing the delivery pattern"},{"name":"BenefitId","type":"Lookup","description":"The benefit this schedule applies to"},{"name":"Frequency","type":"Picklist","description":"Delivery frequency: Daily, Weekly, Biweekly, Monthly"},{"name":"StartDate","type":"Date","description":"Schedule start date"},{"name":"EndDate","type":"Date","description":"Schedule end date"}],"relationships":[{"target":"Benefit","type":"child","description":"Each schedule defines delivery timing for a benefit"},{"target":"BenefitSession","type":"parent","description":"Schedules generate individual benefit sessions"}]},
      {"name":"BenefitSession","type":"custom","domain":"programs","description":"BenefitSession represents a scheduled occurrence created for benefit delivery and attendance tracking. Name and BenefitScheduleId associate it with its schedule, while SessionDate, Location, and Status describe the occurrence.","fields":[{"name":"Name","type":"Text","description":"Session name or date identifier"},{"name":"BenefitScheduleId","type":"Lookup","description":"The schedule that generated this session"},{"name":"SessionDate","type":"DateTime","description":"Date and time of the session"},{"name":"Location","type":"Text","description":"Where the session takes place"},{"name":"Status","type":"Picklist","description":"Session status: Scheduled, In Progress, Completed, Canceled"}],"relationships":[{"target":"BenefitSchedule","type":"child","description":"Each session is generated from a benefit schedule"},{"target":"BenefitDisbursement","type":"parent","description":"Session attendance creates disbursement records"}]},
      {"name":"BenefitAssignment","type":"custom","domain":"programs","description":"BenefitAssignment connects a participant account to a benefit so assigned assistance can be tracked. Name, AccountId, and BenefitId identify the assignment, while AssignedQuantity and Status describe the planned quantity and assignment state.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated assignment identifier"},{"name":"AccountId","type":"Lookup","description":"The participant assigned to receive this benefit"},{"name":"BenefitId","type":"Lookup","description":"The benefit the participant is assigned to receive"},{"name":"AssignedQuantity","type":"Number","description":"Total quantity the participant is expected to receive"},{"name":"Status","type":"Picklist","description":"Assignment status: Active, Completed, Suspended"}],"relationships":[{"target":"Account","type":"child","description":"Each assignment references a participant account"},{"target":"Benefit","type":"child","description":"Each assignment references a specific benefit"}]},
      {"name":"GoalDefinition","type":"custom","domain":"programs","description":"GoalDefinition describes a reusable participant objective and can be organized into a hierarchy. Name and Description define the goal, while ParentGoalId, TargetDate, and Status place it in context and track its timing and state.","fields":[{"name":"Name","type":"Text","description":"Goal name describing the desired outcome"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the goal and success criteria"},{"name":"ParentGoalId","type":"Lookup","description":"Parent goal for hierarchical goal structures"},{"name":"TargetDate","type":"Date","description":"Date by which the goal should be achieved"},{"name":"Status","type":"Picklist","description":"Goal status: Not Started, In Progress, Achieved, Not Achieved"}],"relationships":[{"target":"OutcomeDefinition","type":"lookup","description":"Goals connect to outcome definitions for measurement"},{"target":"CarePlan","type":"lookup","description":"Care plans reference goal definitions for participant-level tracking"},{"target":"Program","type":"lookup","description":"Goals are associated with programs they measure"}]}
    ],
    "metadata": [
      {"type":"ProgramManagementSetting__mdt","name":"Program Management Settings","fields":{"AutoEnrollmentEnabled__c":"Checkbox","DefaultBenefitType__c":"Text","DisbursementTrackingEnabled__c":"Checkbox","GoalHierarchyDepth__c":"Number"},"description":"ProgramManagementSetting__mdt stores configuration represented by Program Management Settings for Nonprofit Cloud. Administrators use Program Management setup to enable and configure the capabilities available to staff who manage and deliver programs."}
    ]
  },

  "case_management": {
    "objects": [
      {"name":"Case","type":"standard","domain":"case_management","description":"Case represents a matter that requires assessment and follow-up for a constituent. It records the case number, subject, status, priority, related account or contact, origin, and description.","fields":[{"name":"CaseNumber","type":"AutoNumber","description":"System-generated case identifier"},{"name":"Subject","type":"Text","description":"Brief description of the case subject"},{"name":"Status","type":"Picklist","description":"Case lifecycle: New, In Progress, Pending, Closed"},{"name":"Priority","type":"Picklist","description":"Urgency level: Low, Medium, High, Critical"},{"name":"AccountId","type":"Lookup","description":"The participant account"},{"name":"ContactId","type":"Lookup","description":"The participant contact"},{"name":"Origin","type":"Picklist","description":"How the case was created: Self-Referral, Partner Agency, Internal, Phone"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the participant's needs"}],"relationships":[{"target":"Account","type":"child","description":"Each case references a participant account"},{"target":"CarePlan","type":"parent","description":"Cases can have personalized care plans"},{"target":"CaseReferral","type":"parent","description":"Cases can be created from referrals"},{"target":"InteractionSummary","type":"parent","description":"Cases have interaction summaries documenting meetings and notes"}]},
      {"name":"CarePlan","type":"custom","domain":"case_management","description":"CarePlan represents a personalized plan associated with a participant account and, when applicable, a case and template. It tracks the plan’s name, status, start date, and end date.","fields":[{"name":"Name","type":"Text","description":"Care plan name describing its focus area"},{"name":"AccountId","type":"Lookup","description":"The participant account this plan serves"},{"name":"CaseId","type":"Lookup","description":"The case this care plan addresses"},{"name":"CarePlanTemplateId","type":"Lookup","description":"The template used as a starting point"},{"name":"Status","type":"Picklist","description":"Plan status: Draft, Active, Completed, Discontinued"},{"name":"StartDate","type":"Date","description":"Plan start date"},{"name":"EndDate","type":"Date","description":"Plan end date"}],"relationships":[{"target":"Account","type":"child","description":"Each care plan serves a participant account"},{"target":"Case","type":"child","description":"Care plans are linked to cases"},{"target":"CarePlanTemplate","type":"child","description":"Care plans are built from templates"},{"target":"GoalDefinition","type":"lookup","description":"Care plans reference goal definitions for tracking progress"}]},
      {"name":"CarePlanTemplate","type":"custom","domain":"case_management","description":"CarePlanTemplate defines a standardized starting point for participant care plans. Its name, description, and active status identify the template and whether it is available for use.","fields":[{"name":"Name","type":"Text","description":"Template name describing the scenario it addresses"},{"name":"Description","type":"LongTextArea","description":"Detailed description of when to use this template"},{"name":"IsActive","type":"Checkbox","description":"Whether this template is available for use"}],"relationships":[{"target":"CarePlan","type":"parent","description":"Templates are used to create care plan instances"},{"target":"CarePlanTemplateBenefit","type":"parent","description":"Templates include pre-configured benefit assignments"},{"target":"CarePlanTemplateGoal","type":"parent","description":"Templates include pre-configured goal definitions"}]},
      {"name":"CarePlanTemplateBenefit","type":"custom","domain":"case_management","description":"CarePlanTemplateBenefit associates a benefit with a Care Plan Template. It records the template, benefit, name, and recommended quantity used when creating personalized plans.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"CarePlanTemplateId","type":"Lookup","description":"The parent care plan template"},{"name":"BenefitId","type":"Lookup","description":"The benefit to include in the plan"},{"name":"RecommendedQuantity","type":"Number","description":"Suggested delivery quantity for this benefit"}],"relationships":[{"target":"CarePlanTemplate","type":"child","description":"Each template benefit belongs to a care plan template"},{"target":"Benefit","type":"child","description":"References the benefit to be included"}]},
      {"name":"CarePlanTemplateGoal","type":"custom","domain":"case_management","description":"CarePlanTemplateGoal associates a goal definition with a Care Plan Template. It identifies the template and goal and records the target number of days.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"CarePlanTemplateId","type":"Lookup","description":"The parent care plan template"},{"name":"GoalDefinitionId","type":"Lookup","description":"The goal to include in the plan"},{"name":"TargetDays","type":"Number","description":"Recommended number of days to achieve this goal"}],"relationships":[{"target":"CarePlanTemplate","type":"child","description":"Each template goal belongs to a care plan template"},{"target":"GoalDefinition","type":"child","description":"References the goal definition to track"}]},
      {"name":"CaseReferral","type":"custom","domain":"case_management","description":"CaseReferral records an inbound or outbound referral and can associate it with a case for follow-up. It captures the referral type, referring organization, reason, and status.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated referral identifier"},{"name":"CaseId","type":"Lookup","description":"The case created from or associated with this referral"},{"name":"ReferralType","type":"Picklist","description":"Direction: Inbound or Outbound"},{"name":"ReferringOrganization","type":"Text","description":"The organization making the referral"},{"name":"Reason","type":"TextArea","description":"Why the participant is being referred"},{"name":"Status","type":"Picklist","description":"Referral status: Pending, Accepted, Declined, Completed"}],"relationships":[{"target":"Case","type":"child","description":"Each referral is linked to a case"},{"target":"Account","type":"lookup","description":"Referrals reference the participant account"}]},
      {"name":"AssessmentTask","type":"custom","domain":"case_management","description":"AssessmentTask tracks participant-specific assessment work associated with an account and Discovery Framework. It records the task status, score, and completion date.","fields":[{"name":"Name","type":"Text","description":"Assessment name or type"},{"name":"AccountId","type":"Lookup","description":"The participant being assessed"},{"name":"DiscoveryFrameworkId","type":"Lookup","description":"The assessment framework used"},{"name":"Status","type":"Picklist","description":"Assessment status: Not Started, In Progress, Completed"},{"name":"Score","type":"Number","description":"Calculated assessment score"},{"name":"CompletedDate","type":"DateTime","description":"When the assessment was completed"}],"relationships":[{"target":"Account","type":"child","description":"Each assessment is completed for a participant"},{"target":"DiscoveryFramework","type":"child","description":"Assessments use a configured discovery framework"},{"target":"Case","type":"lookup","description":"Assessments are linked to participant cases"}]},
      {"name":"DiscoveryFramework","type":"custom","domain":"case_management","description":"DiscoveryFramework defines a reusable structure for collecting and evaluating participant information. It records the framework’s name, description, active status, and scoring method.","fields":[{"name":"Name","type":"Text","description":"Framework name describing the assessment type"},{"name":"Description","type":"LongTextArea","description":"Purpose and usage instructions for this framework"},{"name":"IsActive","type":"Checkbox","description":"Whether this framework is available for use"},{"name":"ScoringMethod","type":"Picklist","description":"How scores are calculated: Sum, Average, Weighted"}],"relationships":[{"target":"AssessmentTask","type":"parent","description":"Frameworks are used to create assessment task instances"}]},
      {"name":"InteractionSummary","type":"custom","domain":"case_management","description":"InteractionSummary stores detailed information about a stakeholder meeting or conversation. It associates the summary with an account and records the interaction type and date, notes, next steps, and confidentiality status.","fields":[{"name":"Name","type":"Text","description":"Interaction title or subject"},{"name":"AccountId","type":"Lookup","description":"The account this interaction relates to"},{"name":"InteractionType","type":"Picklist","description":"Type: Meeting, Phone Call, Email, Home Visit, Group Session"},{"name":"InteractionDate","type":"DateTime","description":"When the interaction took place"},{"name":"Notes","type":"RichTextArea","description":"Detailed notes from the interaction"},{"name":"NextSteps","type":"LongTextArea","description":"Planned follow-up actions"},{"name":"IsConfidential","type":"Checkbox","description":"Whether this interaction contains sensitive information requiring restricted access"}],"relationships":[{"target":"Account","type":"child","description":"Each interaction is linked to a constituent account"},{"target":"Case","type":"lookup","description":"Interactions can be linked to a case for case management context"}]}
    ]
  },

  "outcomes": {
    "objects": [
      {"name":"OutcomeDefinition","type":"custom","domain":"outcomes","description":"OutcomeDefinition records an intended result within an impact strategy or theory of change. Its fields capture the outcome's name, description, target population, optional parent relationship, and active status.","fields":[{"name":"Name","type":"Text","description":"Outcome name describing the desired impact"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the outcome and its significance"},{"name":"TargetPopulation","type":"Text","description":"The group of people this outcome applies to"},{"name":"ParentOutcomeId","type":"Lookup","description":"Parent outcome for hierarchical theory of change"},{"name":"IsActive","type":"Checkbox","description":"Whether this outcome definition is currently tracked"}],"relationships":[{"target":"Program","type":"lookup","description":"Outcomes link to the programs that drive them"},{"target":"Indicator","type":"parent","description":"Outcomes are measured through indicators"},{"target":"GoalDefinition","type":"lookup","description":"Outcomes connect to program goals"}]},
      {"name":"Indicator","type":"custom","domain":"outcomes","description":"Indicator records a measure associated with an OutcomeDefinition. It identifies the data type and collection frequency and stores baseline and target values used to evaluate progress.","fields":[{"name":"Name","type":"Text","description":"Indicator name describing the metric"},{"name":"OutcomeDefinitionId","type":"Lookup","description":"The outcome this indicator measures"},{"name":"DataType","type":"Picklist","description":"Data type: Number, Percent, Currency, Text"},{"name":"CollectionFrequency","type":"Picklist","description":"How often data is collected: Weekly, Monthly, Quarterly, Annually"},{"name":"TargetValue","type":"Number","description":"The target value that represents success"},{"name":"BaselineValue","type":"Number","description":"Starting value before program intervention"}],"relationships":[{"target":"OutcomeDefinition","type":"child","description":"Each indicator measures a specific outcome"},{"target":"IndicatorResult","type":"parent","description":"Indicators accumulate result data points over time"}]},
      {"name":"IndicatorResult","type":"custom","domain":"outcomes","description":"IndicatorResult records a measured value for an Indicator on a specified date. It also captures the collection context needed to interpret the result and support progress evaluation and reporting.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated result identifier"},{"name":"IndicatorId","type":"Lookup","description":"The indicator this result measures"},{"name":"ResultValue","type":"Number","description":"The measured value"},{"name":"MeasurementDate","type":"Date","description":"Date when the measurement was taken"},{"name":"CollectionContext","type":"TextArea","description":"Notes about how and where the data was collected"}],"relationships":[{"target":"Indicator","type":"child","description":"Each result belongs to an indicator"},{"target":"Program","type":"lookup","description":"Results are collected from program activities"}]}
    ]
  },

  "volunteers": {
    "objects": [
      {"name":"VolunteerInitiative","type":"custom","domain":"volunteers","description":"VolunteerInitiative represents an organized volunteer project or effort, including its Name, Description, StartDate, EndDate, Status, TargetVolunteerCount, and TargetHours. ParentInitiativeId supports related initiatives, while IsPublished indicates whether the initiative is available through an Experience Cloud site.","fields":[{"name":"Name","type":"Text","description":"Initiative name"},{"name":"Description","type":"LongTextArea","description":"Detailed description of the volunteer project"},{"name":"StartDate","type":"Date","description":"Initiative start date"},{"name":"EndDate","type":"Date","description":"Initiative end date"},{"name":"Status","type":"Picklist","description":"Initiative status: Planned, Active, Completed, Canceled"},{"name":"TargetVolunteerCount","type":"Number","description":"Target number of volunteers needed"},{"name":"TargetHours","type":"Number","description":"Target total volunteer hours"},{"name":"ParentInitiativeId","type":"Lookup","description":"Parent initiative for hierarchical structures"},{"name":"IsPublished","type":"Checkbox","description":"Whether this initiative is visible on the volunteer portal"}],"relationships":[{"target":"JobPosition","type":"parent","description":"Initiatives are staffed by job positions"},{"target":"Program","type":"lookup","description":"Volunteer initiatives support program delivery"}]},
      {"name":"Position","type":"custom","domain":"volunteers","description":"Position represents a reusable volunteer role that can be related to more specific Job Positions across multiple initiatives. Its Name, Description, RequiredQualifications, and IsActive fields describe the role, its requirements, and whether it is available for use.","fields":[{"name":"Name","type":"Text","description":"Position title"},{"name":"Description","type":"LongTextArea","description":"Role description and general responsibilities"},{"name":"RequiredQualifications","type":"LongTextArea","description":"Qualifications needed for this role"},{"name":"IsActive","type":"Checkbox","description":"Whether this position is available for use"}],"relationships":[{"target":"JobPosition","type":"parent","description":"Generic positions are customized as job positions for specific initiatives"},{"target":"Competency","type":"lookup","description":"Positions may require specific competencies"}]},
      {"name":"JobPosition","type":"custom","domain":"volunteers","description":"JobPosition represents a specific volunteer role associated with a VolunteerInitiative and, when applicable, a reusable Position. Its fields capture the Name, VolunteerInitiativeId, PositionId, Location, RequiresApproval setting, and HeadcountTarget for the role.","fields":[{"name":"Name","type":"Text","description":"Job position name specific to this initiative"},{"name":"VolunteerInitiativeId","type":"Lookup","description":"The initiative this job position belongs to"},{"name":"PositionId","type":"Lookup","description":"The generic position this job position instantiates"},{"name":"Location","type":"Text","description":"Where the volunteer will work"},{"name":"RequiresApproval","type":"Checkbox","description":"Whether signup requires manager approval"},{"name":"HeadcountTarget","type":"Number","description":"Number of volunteers needed for this job position"}],"relationships":[{"target":"VolunteerInitiative","type":"child","description":"Each job position belongs to a volunteer initiative"},{"target":"Position","type":"child","description":"Each job position references a generic position"},{"target":"JobPositionShift","type":"parent","description":"Job positions have one or more shifts"}]},
      {"name":"JobPositionShift","type":"custom","domain":"volunteers","description":"JobPositionShift represents a scheduled period of work associated with a JobPosition. It records the Name, JobPositionId, StartDateTime, EndDateTime, Capacity, and FilledCount used to plan and monitor shift coverage.","fields":[{"name":"Name","type":"Text","description":"Shift name or time slot description"},{"name":"JobPositionId","type":"Lookup","description":"The job position this shift belongs to"},{"name":"StartDateTime","type":"DateTime","description":"Shift start date and time"},{"name":"EndDateTime","type":"DateTime","description":"Shift end date and time"},{"name":"Capacity","type":"Number","description":"Maximum number of volunteers for this shift"},{"name":"FilledCount","type":"Number","description":"Number of volunteers currently assigned"}],"relationships":[{"target":"JobPosition","type":"child","description":"Each shift belongs to a job position"},{"target":"JobPositionAssignment","type":"parent","description":"Shifts have volunteer assignments"}]},
      {"name":"JobPositionAssignment","type":"custom","domain":"volunteers","description":"JobPositionAssignment connects a volunteer account to a JobPositionShift and tracks the volunteer's participation. Its Name, JobPositionShiftId, AccountId, Status, and ActualHours fields support scheduling and hour tracking.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated assignment identifier"},{"name":"JobPositionShiftId","type":"Lookup","description":"The shift this volunteer is assigned to"},{"name":"AccountId","type":"Lookup","description":"The volunteer's person account"},{"name":"Status","type":"Picklist","description":"Assignment status: Upcoming, In Progress, Completed, No Show, Canceled"},{"name":"ActualHours","type":"Number","description":"Actual hours worked by the volunteer"}],"relationships":[{"target":"JobPositionShift","type":"child","description":"Each assignment belongs to a shift"},{"target":"Account","type":"child","description":"Each assignment references a volunteer account"}]},
      {"name":"Competency","type":"custom","domain":"volunteers","description":"Competency defines a skill that can be associated with volunteers and used as a qualification for volunteer roles. Its Name, Description, Category, and IsActive fields identify and organize the competency.","fields":[{"name":"Name","type":"Text","description":"Competency name"},{"name":"Description","type":"LongTextArea","description":"What this competency represents"},{"name":"Category","type":"Picklist","description":"Competency category: Skill, Certification, License, Background Check"},{"name":"IsActive","type":"Checkbox","description":"Whether this competency is actively tracked"}],"relationships":[{"target":"PersonCompetency","type":"parent","description":"Competencies are held by individuals through person competency records"},{"target":"Position","type":"lookup","description":"Positions may require specific competencies"}]},
      {"name":"PersonCompetency","type":"custom","domain":"volunteers","description":"PersonCompetency associates a volunteer account with a Competency and records the person's proficiency and relevant dates. Its fields include Name, AccountId, CompetencyId, ProficiencyLevel, DateAchieved, and ExpirationDate; matching also requires qualification-level information on the applicable competency records.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"AccountId","type":"Lookup","description":"The volunteer who holds this competency"},{"name":"CompetencyId","type":"Lookup","description":"The competency being recorded"},{"name":"ProficiencyLevel","type":"Picklist","description":"Proficiency: Beginner, Intermediate, Advanced, Expert"},{"name":"DateAchieved","type":"Date","description":"When the volunteer earned this competency"},{"name":"ExpirationDate","type":"Date","description":"When the competency expires, if applicable"}],"relationships":[{"target":"Account","type":"child","description":"Each person competency belongs to a volunteer account"},{"target":"Competency","type":"child","description":"References the competency definition"}]},
      {"name":"Examination","type":"custom","domain":"volunteers","description":"Examination defines an assessment that can qualify volunteers for a required or preferred license or permit. Its Name, Description, PassingScore, ValidityPeriod, and IsActive fields describe the examination and its validity.","fields":[{"name":"Name","type":"Text","description":"Examination name"},{"name":"Description","type":"LongTextArea","description":"What this examination covers and how it is administered"},{"name":"PassingScore","type":"Number","description":"Minimum score required to pass"},{"name":"ValidityPeriod","type":"Number","description":"Number of months the result remains valid"},{"name":"IsActive","type":"Checkbox","description":"Whether this examination is currently in use"}],"relationships":[{"target":"PersonExamination","type":"parent","description":"Examinations are taken by individuals through person examination records"}]},
      {"name":"PersonExamination","type":"custom","domain":"volunteers","description":"PersonExamination records an examination completed by a volunteer and the resulting qualification information. Its fields capture Name, AccountId, ExaminationId, Score, Passed, CompletedDate, and ExpirationDate.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated identifier"},{"name":"AccountId","type":"Lookup","description":"The volunteer who took the examination"},{"name":"ExaminationId","type":"Lookup","description":"The examination that was taken"},{"name":"Score","type":"Number","description":"Score achieved on the examination"},{"name":"Passed","type":"Checkbox","description":"Whether the volunteer passed"},{"name":"CompletedDate","type":"Date","description":"Date the examination was completed"},{"name":"ExpirationDate","type":"Date","description":"Date when this result expires"}],"relationships":[{"target":"Account","type":"child","description":"Each exam result belongs to a volunteer account"},{"target":"Examination","type":"child","description":"References the examination definition"}]},
      {"name":"PersonLocationAvailability","type":"custom","domain":"volunteers","description":"PersonLocationAvailability records location information used to help match a volunteer account to Job Positions. Its Name, AccountId, City, State, and MaxDistanceMiles fields identify the volunteer and the geographic area in which the person is available.","fields":[{"name":"Name","type":"Text","description":"Location description"},{"name":"AccountId","type":"Lookup","description":"The volunteer who is available at this location"},{"name":"City","type":"Text","description":"City where the volunteer is available"},{"name":"State","type":"Text","description":"State or province"},{"name":"MaxDistanceMiles","type":"Number","description":"Maximum distance the volunteer is willing to travel"}],"relationships":[{"target":"Account","type":"child","description":"Each location availability belongs to a volunteer account"}]}
    ]
  },

  "grantmaking": {
    "objects": [
      {"name":"FundingOpportunity","type":"custom","domain":"grantmaking","description":"FundingOpportunity defines an available funding program and its application details. It stores the opportunity’s Name, Description, FundingAmount, ApplicationDeadline, EligibilityCriteria, Status, and IsPublished value for managing and communicating the opportunity.","fields":[{"name":"Name","type":"Text","description":"Funding opportunity title"},{"name":"Description","type":"RichTextArea","description":"Detailed description of the funding opportunity"},{"name":"FundingAmount","type":"Currency","description":"Total funding available for this opportunity"},{"name":"ApplicationDeadline","type":"DateTime","description":"Last date to submit applications"},{"name":"EligibilityCriteria","type":"LongTextArea","description":"Requirements applicants must meet"},{"name":"Status","type":"Picklist","description":"Opportunity status: Draft, Open, Closed, Awarded"},{"name":"IsPublished","type":"Checkbox","description":"Whether visible on the grantee portal"}],"relationships":[{"target":"GrantApplication","type":"parent","description":"Funding opportunities receive grant applications"},{"target":"Program","type":"lookup","description":"Funding opportunities may be tied to specific programs"}]},
      {"name":"GrantApplication","type":"custom","domain":"grantmaking","description":"GrantApplication records an organization’s request for a specific funding opportunity. It identifies the FundingOpportunityId and ApplicantAccountId and captures the RequestedAmount, ProjectNarrative, Status, and SubmittedDate.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated application identifier"},{"name":"FundingOpportunityId","type":"Lookup","description":"The funding opportunity being applied for"},{"name":"ApplicantAccountId","type":"Lookup","description":"The organization submitting the application"},{"name":"RequestedAmount","type":"Currency","description":"Amount of funding requested"},{"name":"ProjectNarrative","type":"RichTextArea","description":"Description of the proposed project"},{"name":"Status","type":"Picklist","description":"Application status: Draft, Submitted, Under Review, Awarded, Declined"},{"name":"SubmittedDate","type":"DateTime","description":"When the application was submitted"}],"relationships":[{"target":"FundingOpportunity","type":"child","description":"Each application is for a specific funding opportunity"},{"target":"Account","type":"child","description":"Applications reference the applicant organization account"},{"target":"ApplicationReview","type":"parent","description":"Applications are evaluated through review records"},{"target":"FundingAward","type":"parent","description":"Approved applications receive funding awards"}]},
      {"name":"ApplicationReview","type":"custom","domain":"grantmaking","description":"ApplicationReview records a reviewer’s evaluation of a GrantApplication. It associates the application and ReviewerId with a Score, Comments, and Recommendation used during review and approval.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated review identifier"},{"name":"GrantApplicationId","type":"Lookup","description":"The application being reviewed"},{"name":"ReviewerId","type":"Lookup","description":"The user performing the review"},{"name":"Score","type":"Number","description":"Numeric evaluation score"},{"name":"Comments","type":"RichTextArea","description":"Qualitative assessment comments"},{"name":"Recommendation","type":"Picklist","description":"Reviewer recommendation: Approve, Decline, Revise and Resubmit"}],"relationships":[{"target":"GrantApplication","type":"child","description":"Each review evaluates a specific application"}]},
      {"name":"Budget","type":"custom","domain":"grantmaking","description":"Budget captures a categorized funding request associated with a GrantApplication. It preserves the RequestedAmount, ApprovedAmount, and Justification so the submitted and approved budget values can be managed together.","fields":[{"name":"Name","type":"Text","description":"Budget name or category"},{"name":"GrantApplicationId","type":"Lookup","description":"The application this budget belongs to"},{"name":"Category","type":"Picklist","description":"Budget category: Personnel, Direct Costs, Overhead, Travel, Equipment"},{"name":"RequestedAmount","type":"Currency","description":"Amount requested for this budget line"},{"name":"ApprovedAmount","type":"Currency","description":"Amount approved for this budget line"},{"name":"Justification","type":"LongTextArea","description":"Narrative explaining why this cost is necessary"}],"relationships":[{"target":"GrantApplication","type":"child","description":"Each budget belongs to a grant application"},{"target":"FundingAward","type":"lookup","description":"Approved budgets inform funding award amounts"}]},
      {"name":"FundingAward","type":"custom","domain":"grantmaking","description":"FundingAward represents an approved grant associated with a GrantApplication and recipient AccountId. It tracks the AwardAmount, AwardDate, Status, and DisbursedAmount as funding is delivered and evaluated.","fields":[{"name":"Name","type":"AutoNumber","description":"System-generated award identifier"},{"name":"GrantApplicationId","type":"Lookup","description":"The approved application"},{"name":"AccountId","type":"Lookup","description":"The grantee organization account"},{"name":"AwardAmount","type":"Currency","description":"Total approved funding amount"},{"name":"AwardDate","type":"Date","description":"Date the award was granted"},{"name":"Status","type":"Picklist","description":"Award status: Active, Completed, Suspended, Terminated"},{"name":"DisbursedAmount","type":"Currency","description":"Total amount disbursed to date"}],"relationships":[{"target":"GrantApplication","type":"child","description":"Each award results from an approved application"},{"target":"Account","type":"child","description":"Awards are linked to the grantee organization"},{"target":"OutcomeDefinition","type":"lookup","description":"Awards require grantees to report on defined outcomes"}]}
    ]
  },

  "agentforce": {
    "objects": [

    ]
  },

  "action_plans": {
    "objects": [
      {"name":"ActionPlan","type":"custom","domain":"action_plans","description":"ActionPlan represents an executable plan created from an Action Plan Template for a target record. Its Name, ActionPlanTemplateId, TargetId, Status, StartDate, and CompletionPercentage fields identify the process, its context, its starting point, and its overall progress.","fields":[{"name":"Name","type":"Text","description":"Action plan name, usually derived from the template"},{"name":"ActionPlanTemplateId","type":"Lookup","description":"The template used to create this plan"},{"name":"TargetId","type":"Lookup","description":"The record this plan is applied to (polymorphic: Opportunity, Case, Initiative)"},{"name":"Status","type":"Picklist","description":"Plan status: Not Started, In Progress, Completed"},{"name":"StartDate","type":"Date","description":"Date the plan was initiated"},{"name":"CompletionPercentage","type":"Percent","description":"Percentage of tasks completed"}],"relationships":[{"target":"ActionPlanTemplate","type":"child","description":"Each plan is created from a template"},{"target":"ActionPlanItem","type":"parent","description":"Plans contain task items to be completed"}]},
      {"name":"ActionPlanTemplate","type":"custom","domain":"action_plans","description":"ActionPlanTemplate defines a reusable set of tasks for a business process. Its Name and Description explain the process, TargetObjectType identifies the records to which it applies, and IsActive indicates whether the template is active.","fields":[{"name":"Name","type":"Text","description":"Template name describing the process"},{"name":"Description","type":"LongTextArea","description":"Detailed description of when to use this template"},{"name":"TargetObjectType","type":"Picklist","description":"Object type this template applies to: Opportunity, Case, Initiative"},{"name":"IsActive","type":"Checkbox","description":"Whether this template is available for use"}],"relationships":[{"target":"ActionPlan","type":"parent","description":"Templates are used to create action plan instances"},{"target":"ActionPlanTemplateItem","type":"parent","description":"Templates contain template item definitions"}]},
      {"name":"ActionPlanTemplateItem","type":"custom","domain":"action_plans","description":"ActionPlanTemplateItem defines a task within an Action Plan Template. Its Description, DaysFromStart, Priority, and DependsOnItemId fields capture the task details, relative timing, importance, and dependency, while ActionPlanTemplateId associates it with its template.","fields":[{"name":"Name","type":"Text","description":"Task name"},{"name":"ActionPlanTemplateId","type":"Lookup","description":"The parent template"},{"name":"Description","type":"LongTextArea","description":"Task description and instructions"},{"name":"DaysFromStart","type":"Number","description":"Number of days from plan start until this task is due"},{"name":"Priority","type":"Picklist","description":"Task priority: Low, Normal, High"},{"name":"DependsOnItemId","type":"Lookup","description":"Another template item that must be completed first"}],"relationships":[{"target":"ActionPlanTemplate","type":"child","description":"Each item belongs to a template"}]},
      {"name":"ActionPlanItem","type":"custom","domain":"action_plans","description":"ActionPlanItem represents an individual task generated for an ActionPlan. Its AssignedToId, DueDate, Status, and Priority fields identify who is responsible, when the task is due, and how the task is tracked during execution.","fields":[{"name":"Name","type":"Text","description":"Task name from the template item"},{"name":"ActionPlanId","type":"Lookup","description":"The parent action plan"},{"name":"AssignedToId","type":"Lookup","description":"The user assigned to complete this task"},{"name":"DueDate","type":"Date","description":"Calculated due date based on plan start and offset"},{"name":"Status","type":"Picklist","description":"Task status: Not Started, In Progress, Completed"},{"name":"Priority","type":"Picklist","description":"Task priority: Low, Normal, High"}],"relationships":[{"target":"ActionPlan","type":"child","description":"Each item belongs to an action plan"}]},
      {"name":"StageDefinition","type":"custom","domain":"action_plans","description":"StageDefinition defines an ordered stage for records of a specified object type. Its Name, ObjectType, StageOrder, and Description fields characterize the stage, while ActionPlanTemplateId can associate it with a repeatable task process.","fields":[{"name":"Name","type":"Text","description":"Stage name"},{"name":"ObjectType","type":"Picklist","description":"The object this stage applies to: Initiative, Position, Assignment"},{"name":"StageOrder","type":"Number","description":"Sequential order of this stage in the progression"},{"name":"Description","type":"LongTextArea","description":"Description of what this stage represents"},{"name":"ActionPlanTemplateId","type":"Lookup","description":"Template to trigger when a record enters this stage"}],"relationships":[{"target":"ActionPlanTemplate","type":"lookup","description":"Stage transitions can trigger action plan templates"},{"target":"VolunteerInitiative","type":"lookup","description":"Stages track volunteer initiative lifecycle progress"}]}
    ]
  },

  "security": {
    "objects": [
      {"name":"PermissionSetGroup","type":"standard","domain":"security","description":"PermissionSetGroup represents a consolidated assignment of related permission sets. In Nonprofit Cloud, groups can combine managed permissions with custom and muting permission sets so users retain updated default access while receiving organization-specific additions or restrictions.","fields":[],"relationships":[]},
      {"name":"PermissionSetLicense","type":"standard","domain":"security","description":"PermissionSetLicense represents a license prerequisite for permissions associated with certain Salesforce capabilities. For example, gift acknowledgment document generation requires designated administrators to receive the DocGen Designer permission set license.","fields":[],"relationships":[]}
    ]
  },

  "setup": {
    "objects": [

    ],
    "metadata": [
      {"type":"NonprofitCloudSetting__mdt","name":"Nonprofit Cloud Settings","fields":{"FundraisingEnabled__c":"Checkbox","ProgramManagementEnabled__c":"Checkbox","VolunteerManagementEnabled__c":"Checkbox","GrantmakingEnabled__c":"Checkbox","OutcomeManagementEnabled__c":"Checkbox"},"description":"NonprofitCloudSetting__mdt represents configuration metadata for Nonprofit Cloud settings. These settings support centrally managed product behavior alongside feature-specific setup and permissions."},
      {"type":"DataProcessingEngineDefinition__mdt","name":"Data Processing Engine Definitions","fields":{"SourceObject__c":"Text","TargetObject__c":"Text","CalculationType__c":"Picklist","IsActive__c":"Checkbox"},"description":"DataProcessingEngineDefinition__mdt represents configuration metadata associated with Data Processing Engine definitions. Definitions describe transformations that process organizational data and write calculated results used by Nonprofit Cloud rollups and summaries."}
    ]
  }

};
