export const PRODUCT = {

catalog: {
  packages: ['core'],
  name: "Product Catalog",
  icon: "\u{1F4E6}",
  color: "#10b981",
  description: "The foundation of your product universe. The Product Catalog is where you define everything your organization sells or offers, organized into categories, catalogs, and classification hierarchies. Products can have rich attribute sets that drive configuration behavior, and relationships between products power bundles, add-ons, and substitutions. The catalog supports bulk import and export for managing large product portfolios, and product discovery tools help sales reps find the right products quickly.",
  components: [
    {id:"product-management",name:"Product Management",icon:"\u{1F4CB}",desc:"The central hub for creating and maintaining your product definitions. Each product record captures the core details that flow through every downstream process: name, description, product family, and lifecycle status. You can define product attributes like weight, dimensions, or custom fields that drive configuration rules and pricing logic. Products support multiple selling models including one-time, subscription, and usage-based, with effective dating to control when products become available or retire from active selling.",tags:["Product2","ProductAttribute","ProductAttributeSet"],connections:[{planet:"pricing",desc:"Products are assigned to price books for pricing"},{planet:"configurator",desc:"Products use configuration rules for bundling"},{planet:"transactions",desc:"Products appear as line items on quotes and orders"}]},
    {id:"categories-catalogs",name:"Categories and Catalogs",icon:"\u{1F5C2}",desc:"Organizes your product portfolio into logical groupings that match how your business thinks about its offerings. Categories create a hierarchy of product classifications, while catalogs define curated collections of products for specific channels, regions, or use cases. A single product can belong to multiple categories and appear in multiple catalogs, giving you flexibility to present different product views to different audiences. Category-based navigation powers the product selection experience in quotes and orders.",tags:["ProductCatalog","ProductCategory","ProductCategoryProduct"],connections:[{planet:"transactions",desc:"Catalogs determine which products are available during quoting"}]},
    {id:"attributes-classifications",name:"Attributes and Classifications",icon:"\u{1F3F7}",desc:"Extends product records with structured metadata that drives downstream behavior. Attribute sets group related product characteristics together, like physical dimensions for hardware products or capacity tiers for software licenses. Classifications create inheritance hierarchies where child products automatically receive parent attributes, reducing manual data entry for large product families. Attribute values can trigger configuration rules, influence pricing calculations, and appear on customer-facing documents.",tags:["ProductAttribute","ProductAttributeSet","ProductClassification"],connections:[{planet:"configurator",desc:"Attribute values drive configuration rule evaluation"}]},
    {id:"product-discovery",name:"Product Discovery",icon:"\u{1F50D}",desc:"Helps sales reps find the right products from large catalogs quickly and accurately. Search capabilities span product names, descriptions, attributes, and category hierarchies. Guided selling flows ask qualification questions and narrow the product list based on customer needs, reducing the time reps spend browsing through hundreds of products. Recently used products and favorites provide quick access to commonly sold items, and product comparison views help reps evaluate similar offerings side by side.",tags:["ProductSearch","GuidedSelling"],connections:[{planet:"transactions",desc:"Discovered products are added to quotes and orders"}]},
    {id:"product-relationships",name:"Product Relationships",icon:"\u{1F517}",desc:"Defines how products relate to each other across your catalog. Relationship types include bundles (a parent product with required or optional child products), add-ons (complementary products suggested during configuration), substitutes (alternative products that can replace each other), and exclusions (products that cannot be sold together). These relationships drive the configuration experience by automatically suggesting, requiring, or preventing product combinations during the quoting process.",tags:["ProductRelationship","ProductRelationshipType","ProductBundle"],connections:[{planet:"configurator",desc:"Relationships define bundle structures and product rules"},{planet:"transactions",desc:"Relationships influence product suggestions during quoting"}]},
    {id:"import-export",name:"Import and Export",icon:"\u{1F4E5}",desc:"Enables bulk management of your product catalog through structured data import and export capabilities. Import operations support creating new products, updating existing records, and establishing relationships between products in a single batch. Export generates structured files of your catalog data for external analysis, partner distribution, or backup purposes. Change tracking identifies what was modified between import cycles, and validation rules catch data quality issues before records are committed to the catalog.",tags:["ProductImport","ProductExport","DataImportService"],connections:[]}
  ],
  dataFlow:["Admin defines products with attributes and classifications","Products are organized into categories and catalogs","Relationships establish bundles, add-ons, and substitutions","Products are assigned to price books for pricing","Catalog products become available for quoting and ordering"],
  connections:[{planet:"pricing",desc:"Products assigned to price books"},{planet:"configurator",desc:"Product bundles use catalog products"},{planet:"setup",desc:"Catalog permissions managed in settings"}]
},

pricing: {
  packages: ['core'],
  name: "Pricing",
  icon: "\u{1F4B2}",
  color: "#22c55e",
  description: "Controls how your products are priced across every channel and scenario. Pricing brings together price books, pricing procedures, and adjustment rules into a flexible calculation engine that handles everything from simple list prices to complex multi-tier enterprise deals. The price waterfall provides full transparency into how each line item price was calculated, from list price through all discounts and adjustments to the final net price. AI-powered pricing suggestions help reps optimize deal profitability.",
  components: [
    {id:"price-books",name:"Price Books",icon:"\u{1F4D5}",desc:"The starting point for all pricing. Price books contain list prices for your products, organized by currency, region, channel, or any business dimension you need. Every product must have at least one price book entry before it can be added to a quote or order. Multiple price books can apply to a single transaction, with rules determining which book takes priority. Effective dating on price book entries lets you schedule future price changes without disrupting current deals in progress.",tags:["Pricebook2","PricebookEntry","PriceBookAssignment"],connections:[{planet:"catalog",desc:"Price books contain entries for catalog products"},{planet:"transactions",desc:"Price books provide base prices for quote and order lines"}]},
    {id:"pricing-procedures",name:"Pricing Procedures",icon:"\u{2699}",desc:"The calculation engine that determines final prices for every line item on a quote or order. Pricing procedures define the sequence of steps that transform a list price into a customer-facing price, including lookups, calculations, conditions, and adjustments. Each procedure can reference price adjustment schedules, matrix pricing tables, and custom formulas. Procedures execute automatically when lines are added or modified, and administrators can test procedures with simulation tools before activating them in production.",tags:["PricingProcedure","PricingProcedureStep","PricingCalculation"],connections:[{planet:"transactions",desc:"Pricing procedures calculate prices during quoting"},{planet:"rates",desc:"Pricing procedures can invoke rate calculations for usage products"}]},
    {id:"price-adjustments",name:"Price Adjustments",icon:"\u{2702}",desc:"Applies discounts, markups, and other modifications to base prices during the pricing calculation. Adjustments can be percentage-based, fixed-amount, or override the price entirely. Adjustment schedules define tiered pricing based on quantity, revenue, or custom metrics. Volume discounts automatically apply when quantity thresholds are met, and bundled discounts reduce prices when specific product combinations appear together. Each adjustment has eligibility criteria controlling when and where it applies.",tags:["PriceAdjustmentSchedule","PriceAdjustmentTier","PriceAdjustment"],connections:[{planet:"promotions",desc:"Promotions create adjustment entries during pricing"},{planet:"transactions",desc:"Adjustments modify line item prices on quotes and orders"}]},
    {id:"price-waterfall",name:"Price Waterfall",icon:"\u{1F4CA}",desc:"Provides complete transparency into how every price was calculated, step by step. The waterfall shows the journey from list price through each adjustment, discount, surcharge, and margin calculation to arrive at the final net price. Sales reps see the waterfall on every line item, helping them understand their pricing authority and margin impact. Managers use waterfall data to analyze discount patterns across the organization and identify deals that may need additional review or approval.",tags:["PriceWaterfallItem","PriceWaterfallStep"],connections:[{planet:"transactions",desc:"Price waterfall details appear on quote and order lines"},{planet:"intelligence",desc:"Waterfall data feeds pricing analytics and margin reports"}]},
    {id:"price-elements",name:"Price Elements",icon:"\u{1F9E9}",desc:"The building blocks that make up each step in a pricing procedure. Price elements define individual calculations like base price lookups, discount applications, tax computations, and margin calculations. Each element has a specific type (lookup, formula, condition, aggregation) and processes in a defined sequence within the procedure. Elements can reference external data sources, custom formulas, and cross-line calculations that consider the entire transaction context when computing prices.",tags:["PriceElement","PriceElementType","PricingFormula"],connections:[{planet:"procedures",desc:"Price elements can invoke expression sets for complex calculations"}]},
    {id:"contract-pricing",name:"Contract Pricing",icon:"\u{1F4DD}",desc:"Manages negotiated prices that override standard price book values for specific customers or customer groups. Contract prices are established during deal negotiation and stored on the account or contract record, automatically applying to future orders for that customer. Contract pricing supports tiered structures where prices change based on cumulative volume over the contract period. Renewal pricing rules determine how contract prices carry forward or adjust at renewal time.",tags:["ContractPrice","ContractPriceEntry","NegotiatedPrice"],connections:[{planet:"transactions",desc:"Contract prices override list prices during quoting"},{planet:"billing",desc:"Contract pricing flows through to billing schedules"}]},
    {id:"ai-pricing",name:"AI-Powered Pricing",icon:"\u{1F916}",desc:"Uses machine learning to recommend optimal prices based on historical deal data, win rates, and competitive positioning. AI pricing analyzes past transactions to identify patterns in discounting behavior and customer price sensitivity. Sales reps see suggested price ranges with confidence scores, helping them balance competitiveness with profitability. The system learns from deal outcomes over time, continuously improving its recommendations. Guardrails prevent AI suggestions from falling outside approved pricing boundaries.",tags:["AIPricingRecommendation","PricingInsight","PricingModel"],connections:[{planet:"intelligence",desc:"AI pricing models use revenue analytics data"},{planet:"transactions",desc:"AI suggestions appear during quote creation"}]}
  ],
  dataFlow:["Product is added to a quote or order line","Pricing procedure identifies the applicable price book entry","Price elements calculate adjustments, discounts, and surcharges","Price waterfall records each calculation step","Final net price is set on the line item"],
  connections:[{planet:"catalog",desc:"Products assigned to price books"},{planet:"transactions",desc:"Pricing procedures calculate line item prices"},{planet:"rates",desc:"Rate management extends pricing for usage products"},{planet:"promotions",desc:"Promotions apply adjustments via pricing engine"}]
},

rates: {
  packages: ['core'],
  name: "Rating and Metering",
  icon: "\u{1F4CF}",
  color: "#06b6d4",
  description: "Handles consumption-based pricing where costs depend on how much a customer actually uses. Rate cards define the per-unit costs for different usage metrics, and rating procedures calculate charges by applying those rates to recorded consumption data. Rate adjustments and policies provide flexibility for tiered pricing, committed-use discounts, and overage charges. This domain works closely with usage tracking and billing to convert raw consumption data into accurate invoiced amounts.",
  components: [
    {id:"rate-cards",name:"Rate Cards",icon:"\u{1F4C7}",desc:"Defines the per-unit pricing for consumption-based products. Each rate card maps a usage metric (like API calls, storage gigabytes, or compute hours) to a price per unit, with support for multiple tiers where the rate decreases as consumption increases. Rate cards can have effective dates for scheduled rate changes and currency-specific entries for international pricing. Multiple rate cards can apply to the same product for different customer segments or commitment levels.",tags:["RateCard","RateCardEntry","RateTier"],connections:[{planet:"usage",desc:"Rate cards are applied to usage records for charge calculation"},{planet:"pricing",desc:"Rate cards extend the pricing framework for consumption products"}]},
    {id:"rating-procedures",name:"Rating Procedures",icon:"\u{2699}",desc:"The engine that converts raw usage data into monetary charges. Rating procedures define the sequence of steps to look up the applicable rate card, determine the pricing tier based on consumption volume, apply any negotiated rate adjustments, and calculate the final charge amount. Procedures can handle complex scenarios like time-of-use pricing where rates vary by hour or day, and aggregation rules that combine usage across multiple subscriptions for volume discount calculation.",tags:["RatingProcedure","RatingProcedureStep","RatingCalculation"],connections:[{planet:"usage",desc:"Rating procedures process usage records into charges"},{planet:"billing",desc:"Rated charges flow into billing for invoicing"}]},
    {id:"rate-adjustments",name:"Rate Adjustments",icon:"\u{1F4C9}",desc:"Modifies standard rates for specific customers, contracts, or scenarios. Adjustments can increase or decrease rates by a percentage or fixed amount, override rates entirely, or apply special rates for committed-use agreements where customers pre-purchase a volume of usage at a discounted rate. Adjustment rules specify eligibility criteria like customer tier, contract type, or cumulative consumption thresholds, ensuring the right rates apply automatically without manual intervention.",tags:["RateAdjustment","RateAdjustmentRule","CommittedUseDiscount"],connections:[{planet:"pricing",desc:"Rate adjustments interact with pricing procedures"},{planet:"transactions",desc:"Negotiated rate adjustments are captured during deal creation"}]},
    {id:"rate-policies",name:"Rate Policies",icon:"\u{1F4DC}",desc:"Governs how rates are applied across different scenarios and edge cases. Policies define behavior for situations like mid-cycle rate changes (prorate or apply new rate immediately), minimum and maximum charge thresholds, rounding rules for fractional units, and grace periods for overage charges. Rate policies also control how unused committed capacity rolls over between periods and how aggregate rating works across multiple subscriptions on the same account.",tags:["RatePolicy","RatePolicyRule","RatingBehavior"],connections:[{planet:"billing",desc:"Rate policies influence how rated charges appear on invoices"},{planet:"usage",desc:"Policies govern overage and rollover behavior for usage"}]}
  ],
  dataFlow:["Usage records arrive with quantity and timestamp","Rating procedure looks up the applicable rate card","Tier boundaries determine the per-unit rate","Rate adjustments modify the calculated charge","Final rated charge is sent to billing for invoicing"],
  connections:[{planet:"pricing",desc:"Rate management extends pricing for usage products"},{planet:"usage",desc:"Usage resources rated using rate cards"}]
},

configurator: {
  packages: ['core'],
  name: "Product Configurator",
  icon: "\u{1F527}",
  color: "#14b8a6",
  description: "Guides sales reps through building valid, complete product configurations. The configurator enforces business rules that determine which products can be sold together, which options are required or excluded, and how selections cascade through a bundle hierarchy. Visual builders provide an intuitive interface for configuring complex products, while dynamic messages guide reps through the process with contextual help and validation feedback.",
  components: [
    {id:"visual-builder",name:"Visual Builder",icon:"\u{1F3A8}",desc:"Provides a drag-and-drop interface for configuring complex products and bundles. Sales reps see a visual representation of the product structure with nested options, quantities, and attribute selections. The builder validates configurations in real time, highlighting conflicts and suggesting resolutions as reps make changes. For products with many options, the builder supports filtering and search within the configuration tree. Configuration progress indicators show which required selections have been made and which still need attention.",tags:["ProductConfigurationSetup","ConfigurationBuilder","ConfigurationView"],connections:[{planet:"transactions",desc:"Configured products are added to quotes and orders"},{planet:"catalog",desc:"Visual builder loads products and bundles from the catalog"}]},
    {id:"configuration-rules",name:"Configuration Rules",icon:"\u{1F4CF}",desc:"Defines the logic that governs valid product configurations. Rules can require certain options when others are selected (if you choose Product A, Product B is required), set default quantities and attribute values based on selections, and enforce minimum and maximum quantities for each option in a bundle. Rules evaluate in real time as reps build configurations, and each rule includes a user-facing message explaining why a selection was made or prevented. Administrators create rules through a point-and-click interface without code.",tags:["ProductConfigurationRule","RuleCondition","RuleAction"],connections:[{planet:"catalog",desc:"Rules reference products and attributes from the catalog"}]},
    {id:"bundle-configuration",name:"Bundle Configuration",icon:"\u{1F4E6}",desc:"Manages the structure and behavior of product bundles, which are parent products containing child options that can be required, optional, or conditional. Each bundle defines option groups that organize child products into logical categories like hardware, software, and services. Nested bundles allow complex multi-level product structures where a bundle option is itself a bundle. Bundle pricing rules determine whether child product prices are included in the parent price, added on top, or calculated independently.",tags:["ProductBundle","BundleOption","OptionGroup","BundleComponent"],connections:[{planet:"catalog",desc:"Bundles are composed of products from the catalog"},{planet:"pricing",desc:"Bundle pricing rules interact with the pricing engine"}]},
    {id:"exclude-preference-rules",name:"Exclude and Preference Rules",icon:"\u{26D4}",desc:"Controls product compatibility and default selections within configurations. Exclusion rules prevent incompatible products from appearing together in a configuration: selecting a certain hardware model might exclude specific software licenses that are not compatible. Preference rules set recommended defaults based on previous selections, pre-populating options that are commonly chosen together. Both rule types evaluate dynamically as the configuration evolves, updating available options and defaults in real time.",tags:["ExclusionRule","PreferenceRule","ProductCompatibility"],connections:[{planet:"catalog",desc:"Exclusion rules reference product compatibility data"}]},
    {id:"dynamic-messages",name:"Dynamic Messages",icon:"\u{1F4AC}",desc:"Delivers contextual guidance and validation feedback to sales reps during the configuration process. Messages can be informational (explaining an option), warning (flagging a suboptimal choice), or error (blocking an invalid configuration). Each message is tied to a condition that determines when it appears, such as when a required option is missing or when a selected combination triggers a compatibility issue. Messages support rich text formatting and can include links to documentation or training materials.",tags:["ConfigurationMessage","MessageCondition","ValidationMessage"],connections:[{planet:"transactions",desc:"Configuration messages appear during quote line editing"}]}
  ],
  dataFlow:["Sales rep selects a product or bundle to configure","Visual builder loads the product structure with options","Configuration rules evaluate selections and enforce constraints","Exclude and preference rules update available options","Configured product with validated selections is added to the quote"],
  connections:[{planet:"catalog",desc:"Product bundles use catalog products"},{planet:"transactions",desc:"Configured products flow into quotes and orders"}]
},

promotions: {
  packages: ['core'],
  name: "Promotions",
  icon: "\u{1F3AF}",
  color: "#84cc16",
  description: "Enables marketing and sales teams to create targeted promotional offers that automatically apply during the quoting and ordering process. Promotions combine eligibility rules with pricing adjustments to deliver discounts, free items, or special terms to qualifying transactions. The promotion engine evaluates all active promotions against the current transaction and applies those that match, ensuring customers receive the best available offers without manual intervention.",
  components: [
    {id:"promotion-management",name:"Promotion Management",icon:"\u{1F4CB}",desc:"The hub for creating, scheduling, and managing promotional offers. Each promotion has a name, description, effective date range, and status that controls whether it is actively being evaluated. Promotions can target specific products, product categories, customer segments, or transaction types. Administrators can set maximum redemption counts to cap how many times a promotion can be used, and mutual exclusivity rules prevent conflicting promotions from stacking. Promotion dashboards show active offers and their redemption metrics.",tags:["Promotion","PromotionSegment","PromotionTarget"],connections:[{planet:"pricing",desc:"Promotions create price adjustments during pricing calculations"},{planet:"transactions",desc:"Active promotions apply to qualifying quotes and orders"}]},
    {id:"promotion-rules",name:"Promotion Rules",icon:"\u{1F4CF}",desc:"Defines the conditions that must be met for a promotion to apply to a transaction. Rules can evaluate product presence (must include Product X), quantity thresholds (buy 3 or more), transaction value (order total above a certain amount), customer attributes (specific account tier or region), and date ranges. Rules support both AND and OR logic for combining multiple conditions, and nested rule groups enable complex eligibility criteria. Each rule includes a description that appears to sales reps explaining why a promotion did or did not apply.",tags:["PromotionRule","PromotionCondition","PromotionRuleGroup"],connections:[{planet:"catalog",desc:"Promotion rules reference products and categories from the catalog"}]},
    {id:"promotional-pricing",name:"Promotional Pricing",icon:"\u{1F4B0}",desc:"Defines the pricing benefit that a promotion delivers when its rules are satisfied. Benefits include percentage discounts, fixed-amount discounts, buy-one-get-one offers, free add-on products, and special contract terms. Each benefit specifies which line items it applies to and how it interacts with other pricing adjustments in the price waterfall. Stacking rules determine whether promotional discounts compound with volume discounts or are applied independently. The pricing engine processes promotional adjustments as a distinct step in the calculation sequence.",tags:["PromotionalPrice","PromotionBenefit","PromotionDiscount"],connections:[{planet:"pricing",desc:"Promotional pricing feeds into the price adjustment framework"},{planet:"transactions",desc:"Promotional benefits appear as line-level discounts on quotes"}]}
  ],
  dataFlow:["Promotion is created with eligibility rules and date range","Sales rep builds a quote or order with products","Promotion engine evaluates active promotions against the transaction","Matching promotions apply pricing benefits to qualifying lines","Promotional discounts appear in the price waterfall"],
  connections:[{planet:"pricing",desc:"Promotions apply adjustments via pricing engine"}]
},

transactions: {
  packages: ['core'],
  name: "Quotes and Orders",
  icon: "\u{1F4DD}",
  color: "#4d8bff",
  description: "The core transactional domain where deals take shape. Quotes and Orders handles the full lifecycle of a sales transaction, from initial quote creation through line item configuration to order capture and contract execution. The line editor provides a spreadsheet-like experience for managing product lines, and the system supports complex deal structures including amendments, renewals, and ramp deals that change pricing over time. Transaction summaries give reps and managers a clear view of deal economics.",
  components: [
    {id:"quote-management",name:"Quote Management",icon:"\u{1F4C4}",desc:"Manages the creation, versioning, and lifecycle of sales quotes. Each quote captures the customer, products, pricing, terms, and validity period for a proposed deal. Quotes progress through configurable stages from draft through review and approval to accepted or rejected. Version control lets reps create multiple iterations of a quote while preserving the history of changes. Primary quote designation syncs the winning version back to the Salesforce opportunity, keeping CRM data aligned with the latest proposal.",tags:["Quote","QuoteVersion","QuoteDocument","QuoteLineItem"],connections:[{planet:"approvals",desc:"Quotes are submitted through approval workflows"},{planet:"orchestrator",desc:"Accepted quotes convert into orders for fulfillment"}]},
    {id:"order-capture",name:"Order Capture",icon:"\u{1F6D2}",desc:"Converts approved quotes into firm orders that trigger downstream fulfillment and billing processes. Order capture validates that all required fields are complete, pricing is current, and any approval requirements have been met before creating the order record. Orders can be created from a single quote or by combining lines from multiple quotes. The order record becomes the system of record for what was sold, at what price, and under what terms, serving as the contractual basis for fulfillment and billing.",tags:["Order","OrderItem","OrderAction","OrderSummary"],connections:[{planet:"orchestrator",desc:"Orders are decomposed into fulfillment plans"},{planet:"billing",desc:"Orders trigger billing schedule creation"},{planet:"approvals",desc:"Orders may require approval before activation"}]},
    {id:"line-editor",name:"Line Editor",icon:"\u{1F4DD}",desc:"Provides a rich, spreadsheet-like interface for managing product lines on quotes and orders. Reps can add products, adjust quantities, apply manual discounts, and modify attributes directly in the line editor. Inline editing supports bulk operations like applying a discount to multiple lines simultaneously. The editor displays real-time pricing calculations as changes are made, including the price waterfall showing how each adjustment affects the final price. Column configuration lets administrators control which fields are visible and editable.",tags:["QuoteLineItem","OrderItem","LineEditorConfig"],connections:[{planet:"pricing",desc:"Line editor triggers pricing recalculation on changes"},{planet:"configurator",desc:"Complex products open the configurator from the line editor"}]},
    {id:"amendments-renewals",name:"Amendments and Renewals",icon:"\u{1F504}",desc:"Manages changes to existing contracts and subscription renewals. Amendments allow modifications to an active order, such as adding new products, changing quantities, upgrading or downgrading service tiers, and adjusting pricing. The system calculates the financial impact of amendments including prorated credits and charges. Renewals generate new quotes pre-populated with the current contract terms, giving reps a starting point for renewal negotiations. Renewal pricing rules can automatically apply price increases or loyalty discounts.",tags:["Amendment","Renewal","ContractAmendment","RenewalQuote"],connections:[{planet:"orchestrator",desc:"Amendments create new fulfillment plans for changes"},{planet:"billing",desc:"Amendments generate prorated billing adjustments"}]},
    {id:"ramp-deals",name:"Ramp Deals",icon:"\u{1F4C8}",desc:"Supports deal structures where pricing or quantity changes over time according to a predefined schedule. Ramp deals let reps define multiple segments within a single line item, each with its own quantity, discount, and time period. Common use cases include introductory pricing that increases after the first year, volume ramps where a customer commits to increasing usage over the contract term, and graduated pricing where discounts improve as the relationship matures. The system tracks ramp segment transitions and triggers appropriate billing changes.",tags:["RampDeal","RampSegment","RampSchedule"],connections:[{planet:"billing",desc:"Ramp segments trigger billing schedule changes at each transition"},{planet:"pricing",desc:"Each ramp segment has its own pricing calculation"}]},
    {id:"quote-line-import",name:"Quote Line Item Import",icon:"\u{1F4E5}",desc:"Enables bulk creation of quote lines from external data sources like spreadsheets, ERP systems, or partner portals. The import process maps external data fields to quote line attributes, validates product codes against the catalog, and applies pricing procedures to calculate prices for imported lines. Error handling identifies rows that fail validation and provides detailed feedback for correction. This capability is especially valuable for large enterprise deals with hundreds of line items that would be impractical to enter manually.",tags:["QuoteLineImport","ImportMapping","ImportValidation"],connections:[{planet:"procedures",desc:"Document processing engine handles import transformations"},{planet:"catalog",desc:"Import validates product codes against the catalog"}]},
    {id:"transaction-summary",name:"Transaction Summary",icon:"\u{1F4CA}",desc:"Provides a consolidated view of deal economics for quotes and orders. The summary displays total contract value, annual recurring revenue, monthly recurring revenue, one-time charges, total discounts given, and margin analysis. Breakdowns by product category, time period, and pricing component help reps and managers understand the deal structure at a glance. Summary metrics update in real time as line items are added or modified, and comparison views show the financial impact of amendments against the original deal terms.",tags:["TransactionSummary","DealMetrics","RevenueBreakdown"],connections:[{planet:"intelligence",desc:"Transaction metrics feed into revenue dashboards"},{planet:"approvals",desc:"Summary metrics are evaluated by approval rules"}]}
  ],
  dataFlow:["Sales rep creates a quote and adds products via the line editor","Pricing procedures calculate prices for each line item","Quote goes through approval workflow if required","Approved quote converts to an order for fulfillment","Order triggers billing schedules and fulfillment plans"],
  connections:[{planet:"pricing",desc:"Pricing procedures calculate line item prices"},{planet:"configurator",desc:"Configured products flow into quotes and orders"},{planet:"approvals",desc:"Quotes and orders go through approval workflows"},{planet:"orchestrator",desc:"Contracted orders decomposed into fulfillment plans"},{planet:"billing",desc:"Orders trigger billing schedule creation"},{planet:"procedures",desc:"Document processing engine handles quote line imports"},{planet:"agentforce",desc:"AI agents assist with quote and order creation"}]
},

approvals: {
  packages: ['core'],
  name: "Approvals",
  icon: "\u{2705}",
  color: "#0ea5e9",
  description: "Ensures that quotes, orders, and pricing decisions go through the right review process before moving forward. The approvals domain provides configurable workflows that route transactions to the right people based on deal characteristics like discount level, total value, or product type. Approval rules evaluate automatically, and the approval app gives approvers a streamlined interface for reviewing and acting on pending requests from any device.",
  components: [
    {id:"approval-workflows",name:"Approval Workflows",icon:"\u{1F504}",desc:"Defines the step-by-step process that a quote or order follows when it needs approval. Workflows can include sequential steps (one approver after another), parallel steps (multiple approvers simultaneously), or conditional branching where different paths activate based on deal characteristics. Each step specifies what information the approver sees, what actions they can take (approve, reject, request changes), and what happens when the step is completed. Escalation rules automatically reassign pending approvals after a configurable time period.",tags:["ApprovalProcess","ApprovalStep","ApprovalAction","ApprovalEscalation"],connections:[{planet:"transactions",desc:"Workflows are triggered when quotes or orders are submitted for approval"}]},
    {id:"approval-rules",name:"Approval Rules",icon:"\u{1F4CF}",desc:"Determines when and why a transaction requires approval. Rules evaluate deal attributes like discount percentage, total contract value, non-standard terms, specific product inclusion, or deviation from standard pricing. When a rule is triggered, it specifies which approval workflow to initiate and provides the reason for the approval requirement. Multiple rules can apply to a single transaction, and the system combines their requirements into a unified approval path. Administrators can test rules against sample transactions before activating them.",tags:["ApprovalRule","ApprovalCondition","ApprovalCriteria"],connections:[{planet:"transactions",desc:"Rules evaluate quote and order attributes to determine approval needs"},{planet:"pricing",desc:"Pricing thresholds can trigger approval requirements"}]},
    {id:"approver-management",name:"Approver Management",icon:"\u{1F465}",desc:"Manages who can approve what across the organization. Approver assignments can be based on role hierarchy, approval groups, specific user assignments, or dynamic criteria like the deal owner's manager. Approval authority levels define the maximum discount or deal value each approver can authorize, with transactions exceeding their authority automatically escalating to the next level. Delegate approvers handle requests when the primary approver is unavailable, and out-of-office settings automatically redirect approvals during planned absences.",tags:["ApproverAssignment","ApprovalGroup","ApprovalAuthority","ApproverDelegate"],connections:[{planet:"setup",desc:"Approver assignments are configured in user and permission settings"}]},
    {id:"approval-app",name:"Approval App",icon:"\u{1F4F1}",desc:"Provides a dedicated interface for reviewing and acting on approval requests. Approvers see a queue of pending requests with key deal details like customer name, total value, discount level, and the specific reason approval was triggered. The app supports side-by-side comparison of the proposed deal terms against standard pricing or previous versions. Approvers can approve, reject, or request changes with comments that flow back to the submitter. Mobile support ensures approvals are not bottlenecked by approver availability, and batch approval lets managers process multiple routine requests efficiently.",tags:["ApprovalRequest","ApprovalDecision","ApprovalComment","ApprovalQueue"],connections:[{planet:"transactions",desc:"Approval decisions update quote and order status"}]}
  ],
  dataFlow:["Quote or order is submitted for approval","Approval rules evaluate deal attributes against thresholds","Matching rules determine the required approval workflow","Approvers review and act on requests via the approval app","Decision flows back to update the transaction status"],
  connections:[{planet:"transactions",desc:"Quotes and orders go through approval workflows"}]
},

orchestrator: {
  packages: ['core'],
  name: "Order Orchestration",
  icon: "\u{1F3AF}",
  color: "#3b82f6",
  description: "Manages the complex journey from a contracted order to fulfilled delivery. Order orchestration breaks down multi-product orders into individual fulfillment plans, each with its own sequence of steps that can be executed in parallel or in sequence. The system handles the creation of assets that represent what the customer owns, processes amendments and cancellations against existing assets, and provides a workspace for operations teams to monitor fulfillment progress.",
  components: [
    {id:"order-decomposition",name:"Order Decomposition",icon:"\u{1F9E9}",desc:"Breaks a single order containing multiple products into separate fulfillment work items based on product type, delivery method, and fulfillment system. Each decomposed item becomes an independent unit that can be tracked and fulfilled on its own timeline. Decomposition rules determine how order lines are grouped: physical products might go to a warehouse management system, software licenses to a provisioning system, and professional services to a resource management system. This separation enables parallel processing and prevents delays in one area from blocking others.",tags:["OrderDecomposition","FulfillmentItem","DecompositionRule"],connections:[{planet:"transactions",desc:"Decomposition processes contracted order line items"},{planet:"billing",desc:"Decomposed items determine billing trigger points"}]},
    {id:"fulfillment-plans",name:"Fulfillment Plans",icon:"\u{1F4CB}",desc:"Defines the sequence of activities required to deliver each product or service to the customer. A fulfillment plan is a template that specifies which steps must be completed, in what order, and what systems or teams are responsible for each step. Plans can include conditional branches where the next step depends on the outcome of the previous one, and parallel paths where multiple activities happen simultaneously. Each plan has expected duration estimates that power delivery date calculations and SLA tracking.",tags:["FulfillmentPlan","FulfillmentPlanStep","FulfillmentTemplate"],connections:[{planet:"transactions",desc:"Plans are created from order line items after decomposition"}]},
    {id:"fulfillment-steps",name:"Fulfillment Steps",icon:"\u{1F4A1}",desc:"Individual activities within a fulfillment plan that must be completed to deliver a product or service. Each step has an assigned owner (user, queue, or external system), expected duration, and status tracking. Steps can trigger external system calls for tasks like license provisioning, shipping label generation, or service activation. Automated steps execute without human intervention when their prerequisites are met, while manual steps create work items for fulfillment team members. Step completion can trigger downstream events like customer notifications or billing actions.",tags:["FulfillmentStep","StepAction","StepDependency","FulfillmentTask"],connections:[{planet:"billing",desc:"Step completion can trigger billing events"}]},
    {id:"assetization",name:"Assetization",icon:"\u{1F4E6}",desc:"Creates and maintains asset records that represent what a customer owns or is entitled to. When an order is fulfilled, assetization converts order line items into asset records on the customer's account, tracking details like quantity, start and end dates, and current status. Assets provide a single source of truth for the customer's installed base, which is essential for amendments, renewals, and support. The assetization engine handles complex scenarios like partial fulfillment, asset splits, and asset merges during upgrades or consolidations.",tags:["Asset","AssetAction","AssetStatePeriod","AssetRelationship"],connections:[{planet:"transactions",desc:"Order lines are converted into customer assets"},{planet:"billing",desc:"Asset lifecycle events can trigger billing changes"}]},
    {id:"amendment-cancellation",name:"Amendment and Cancellation",icon:"\u{1F504}",desc:"Processes changes to existing customer assets, including quantity increases, quantity decreases, upgrades, downgrades, and full cancellations. When an amendment order is placed, the system identifies the affected assets and creates new fulfillment plans to execute the changes. Cancellation processing handles the reverse workflow: deactivating assets, stopping billing schedules, calculating any early termination fees, and updating the customer's installed base. Amendment orders automatically reference the original order for audit trail continuity.",tags:["AmendmentAction","CancellationAction","AssetAmendment"],connections:[{planet:"transactions",desc:"Amendment orders reference and modify existing assets"},{planet:"billing",desc:"Amendments trigger billing adjustments and cancellation charges"}]},
    {id:"fulfillment-workspace",name:"Fulfillment Workspace",icon:"\u{1F4BB}",desc:"A dedicated interface for operations teams to monitor and manage fulfillment activities across all orders. The workspace shows fulfillment plans in progress, step completion status, blocked items requiring attention, and overall fulfillment metrics. Team members can reassign steps, update statuses, add notes, and escalate issues directly from the workspace. Filtering and sorting capabilities help teams focus on specific product types, customers, or priority levels. Real-time updates ensure everyone sees the current state of fulfillment without manual refresh.",tags:["FulfillmentWorkspace","FulfillmentDashboard","FulfillmentMonitor"],connections:[{planet:"intelligence",desc:"Fulfillment metrics feed into operational dashboards"}]}
  ],
  dataFlow:["Contracted order arrives from the transactions domain","Order decomposition breaks it into fulfillment items by product type","Fulfillment plans define the steps needed for each item","Steps execute in sequence or parallel until fulfillment is complete","Assetization creates asset records representing what the customer owns"],
  connections:[{planet:"transactions",desc:"Contracted orders decomposed into fulfillment plans"},{planet:"billing",desc:"Fulfilled orders trigger billing events"}]
},

usage: {
  packages: ['core'],
  name: "Usage and Consumption",
  icon: "\u{1F4CA}",
  color: "#f59e0b",
  description: "Tracks and manages consumption data for usage-based products and services. The usage domain captures how much of a metered resource a customer has consumed, manages prepaid consumption grants that deplete over time, and handles overage scenarios when usage exceeds committed levels. This data flows into the rating engine for charge calculation and ultimately into billing for invoicing.",
  components: [
    {id:"usage-modeling",name:"Usage Modeling",icon:"\u{1F4D0}",desc:"Defines the structure and rules for how consumption data is captured and organized. Usage models specify which metrics are tracked for each product (API calls, storage, users, transactions), the unit of measure for each metric, and the aggregation rules for combining usage across time periods or subscription instances. Models also define the expected data format for incoming usage records, enabling validation and normalization of data from multiple source systems. Well-designed usage models ensure accurate and consistent consumption tracking across all customer accounts.",tags:["UsageModel","UsageMetric","UsageDefinition","UsageUnit"],connections:[{planet:"catalog",desc:"Usage models are linked to consumption-based products in the catalog"},{planet:"rates",desc:"Usage metrics map to rate card entries for charge calculation"}]},
    {id:"consumption-tracking",name:"Consumption Tracking",icon:"\u{1F4C8}",desc:"Records and aggregates actual usage data as it arrives from metering systems. Consumption records capture who used what, how much, and when, providing the raw data for charge calculation. The tracking engine supports real-time and batch ingestion of usage data, with deduplication logic to prevent double-counting. Aggregation rules combine individual usage events into summary records at configurable intervals (hourly, daily, monthly). Usage dashboards let both internal teams and customers see current consumption levels relative to their committed volumes.",tags:["UsageRecord","ConsumptionSummary","UsageIngestion","UsageAggregation"],connections:[{planet:"rates",desc:"Consumption data is processed by rating procedures"},{planet:"billing",desc:"Aggregated usage generates billing events"}]},
    {id:"grant-management",name:"Grant Management",icon:"\u{1F381}",desc:"Manages prepaid consumption allowances that customers purchase or receive as part of their subscription. Grants represent a pool of usage units (like 10,000 API calls per month or 500 gigabytes of storage) that deplete as the customer consumes the resource. Each grant tracks its original quantity, remaining balance, and expiration date. When multiple grants exist for the same resource, depletion rules determine which grant is consumed first, typically following a first-expiring-first-out approach. Grant balances are visible to both internal teams and customers for proactive capacity planning.",tags:["UsageGrant","GrantBalance","GrantDepletion","GrantAllocation"],connections:[{planet:"billing",desc:"Grant purchases appear as line items on invoices"},{planet:"transactions",desc:"Grants are established when usage-based orders are activated"}]},
    {id:"overage-handling",name:"Overage Handling",icon:"\u{26A0}",desc:"Manages what happens when a customer's consumption exceeds their committed or granted usage levels. Overage policies define whether excess usage is charged at a premium rate, blocked entirely, or allowed with notifications. The system can send alerts when customers approach their usage limits (at 80% and 90% thresholds, for example) to give them time to purchase additional capacity before overage charges apply. Overage charges are calculated using the applicable rate card and flow into billing as separate line items, clearly distinguishing committed usage charges from overage charges on invoices.",tags:["OveragePolicy","OverageCharge","UsageAlert","UsageThreshold"],connections:[{planet:"rates",desc:"Overage rates are defined on rate cards"},{planet:"billing",desc:"Overage charges generate distinct billing line items"}]}
  ],
  dataFlow:["Metering systems send consumption data to usage tracking","Usage records are validated, deduplicated, and aggregated","Grants are depleted based on consumption and depletion rules","Consumption exceeding grants triggers overage handling","Rated usage charges flow into billing for invoicing"],
  connections:[{planet:"rates",desc:"Usage resources rated using rate cards"},{planet:"billing",desc:"Metered usage generates billing events"}]
},

billing: {
  packages: ['core'],
  name: "Billing and Invoicing",
  icon: "\u{1F4B3}",
  color: "#f97316",
  description: "Converts orders and consumption into financial documents that drive revenue collection. Billing manages the complete invoicing lifecycle from schedule creation through invoice generation, tax calculation, payment processing, and credit management. The domain supports multiple billing models including advance billing for subscriptions, arrears billing for usage, and milestone billing for services. Invoice templates and credit/debit notes provide professional, customizable financial documents.",
  components: [
    {id:"billing-schedules",name:"Billing Schedules",icon:"\u{1F4C5}",desc:"Defines when and how customers are billed for their purchases. Each billing schedule specifies the billing frequency (monthly, quarterly, annually, or custom), the billing day of the period, and the billing method (in advance or in arrears). Schedules are created automatically when orders are activated, with one schedule per order line item. For subscription products, the schedule spans the full subscription term and generates billing events at each period boundary. Administrators can pause, resume, or modify schedules to handle customer requests or billing disputes.",tags:["BillingSchedule","BillingScheduleGroup","BillingPeriod"],connections:[{planet:"transactions",desc:"Billing schedules are created from activated order line items"},{planet:"orchestrator",desc:"Fulfillment completion can trigger billing schedule activation"}]},
    {id:"invoice-generation",name:"Invoice Generation",icon:"\u{1F4C4}",desc:"Creates invoice documents from billing events that are ready for collection. The invoice generation process aggregates all billing events for a customer within a billing period into a single invoice, applying any credits or adjustments. Each invoice contains header information (customer, dates, totals, payment terms) and line items detailing what is being charged. Invoice numbering follows configurable sequences, and invoices progress through statuses from draft to posted to paid. Batch invoice generation processes thousands of customers efficiently during billing runs.",tags:["Invoice","InvoiceLine","InvoiceBatch","InvoiceGeneration"],connections:[{planet:"intelligence",desc:"Invoice data feeds revenue dashboards and analytics"}]},
    {id:"billing-policies",name:"Billing Policies",icon:"\u{1F4DC}",desc:"Governs billing behavior across different scenarios and product types. Policies control proration rules for mid-cycle changes (how charges are calculated when a subscription starts or changes mid-period), alignment rules that synchronize billing dates across multiple subscriptions on the same account, and consolidation rules that determine which charges appear on the same invoice. Billing policies also define retry logic for failed payments and dunning sequences for overdue invoices.",tags:["BillingPolicy","BillingPolicyRule","ProrationPolicy","DunningPolicy"],connections:[{planet:"setup",desc:"Billing policies are configured in revenue settings"},{planet:"transactions",desc:"Policies determine how amendments affect billing"}]},
    {id:"payment-processing",name:"Payment Processing",icon:"\u{1F4B5}",desc:"Manages the collection of payments against invoices. Payment processing supports multiple payment methods including credit cards, ACH transfers, wire payments, and payment on account. Payment allocation rules determine how incoming payments are applied when a customer has multiple outstanding invoices. Automatic payment processing can charge stored payment methods on invoice due dates, while manual payment entry handles checks and wire transfers. Payment reconciliation matches bank deposits to invoice payments for accurate financial reporting.",tags:["Payment","PaymentMethod","PaymentAllocation","PaymentGateway"],connections:[{planet:"intelligence",desc:"Payment data feeds into revenue collection dashboards"}]},
    {id:"tax-engine",name:"Tax Engine",icon:"\u{1F4B0}",desc:"Calculates taxes on billing transactions based on product type, customer location, and applicable tax rules. The tax engine supports multiple tax jurisdictions, compound tax calculations, and tax-exempt customers or products. Tax rates can be maintained internally or integrated with external tax calculation services for real-time rates. Tax lines appear as separate entries on invoices, providing transparency for customers and audit compliance. The engine handles tax-inclusive and tax-exclusive pricing models and generates tax reporting data for compliance.",tags:["TaxEngine","TaxCalculation","TaxRate","TaxExemption"],connections:[{planet:"setup",desc:"Tax rules and rates are configured in revenue settings"}]},
    {id:"credit-debit-notes",name:"Credit and Debit Notes",icon:"\u{1F4DD}",desc:"Creates financial adjustment documents that modify the balance owed by a customer. Credit notes reduce the amount owed and are issued for returns, billing errors, service credits, or negotiated adjustments. Debit notes increase the amount owed for additional charges, late fees, or corrections. Both document types reference the original invoice and follow the same approval and posting workflow as invoices. Credit balances can be applied automatically to future invoices or refunded to the customer's payment method.",tags:["CreditNote","DebitNote","CreditNoteLine","FinancialAdjustment"],connections:[{planet:"transactions",desc:"Amendments and cancellations can generate credit notes"},{planet:"intelligence",desc:"Credit and debit note trends appear in revenue analytics"}]},
    {id:"billing-subscriptions",name:"Billing for Subscriptions",icon:"\u{1F504}",desc:"Handles the unique billing requirements of subscription-based products. Subscription billing manages recurring charges that span multiple billing periods, including the initial charge, regular periodic charges, and final-period handling at subscription end. The system processes mid-term changes like upgrades, downgrades, and quantity changes with appropriate proration. Renewal billing generates new billing schedules when subscriptions are renewed, optionally applying renewal price adjustments. Co-termination aligns multiple subscription end dates for simplified billing and renewal management.",tags:["SubscriptionBilling","SubscriptionSchedule","SubscriptionRenewal","CoTermination"],connections:[{planet:"transactions",desc:"Subscription billing aligns with order and amendment lifecycle"},{planet:"orchestrator",desc:"Subscription activation triggers billing schedule creation"}]},
    {id:"invoice-templates",name:"Invoice Templates",icon:"\u{1F4C3}",desc:"Controls the visual layout and content of generated invoice documents. Templates define the header, line item table, summary, payment instructions, and footer sections of an invoice. Administrators can customize branding (logo, colors, fonts), field placement, and which information appears on the document. Multiple templates support different use cases: a detailed template for enterprise customers, a simplified template for small accounts, and a proforma template for pre-billing review. Templates support multiple languages and currencies for international billing.",tags:["InvoiceTemplate","TemplateSection","TemplateLayout"],connections:[]}
  ],
  dataFlow:["Order activation creates billing schedules for each line item","Billing events are generated at each period boundary","Invoice generation aggregates billing events into customer invoices","Tax engine calculates applicable taxes on each invoice line","Payment processing collects payment against posted invoices"],
  connections:[{planet:"transactions",desc:"Orders trigger billing schedule creation"},{planet:"orchestrator",desc:"Fulfilled orders trigger billing events"},{planet:"usage",desc:"Metered usage generates billing events"},{planet:"setup",desc:"Billing policies and tax engines in settings"},{planet:"agentforce",desc:"AI agents help with billing inquiries"},{planet:"intelligence",desc:"Dashboards display billing and revenue data"}]
},

procedures: {
  packages: ['core'],
  name: "Business Rules Engine",
  icon: "\u{2699}",
  color: "#8b5cf6",
  description: "The low-code rules and calculation engine that powers automation across Revenue Cloud. Procedures, expression sets, and decision tables provide reusable business logic that can be invoked from pricing, rating, approvals, and other domains without writing code. Context definitions describe the data available to rules, and batch processing enables high-volume execution of business logic against large datasets.",
  components: [
    {id:"procedure-definitions",name:"Procedure Definitions",icon:"\u{1F4CB}",desc:"Defines reusable sequences of business logic steps that execute in order to produce a result. Each procedure contains steps that can perform calculations, evaluate conditions, look up data, transform values, or call external services. Procedures are versioned so that changes can be tested before activation, and multiple versions can coexist for different contexts. The procedure designer provides a visual canvas for building and connecting steps, with a simulation panel for testing procedures against sample data before deployment.",tags:["OmniProcess","ProcedureDefinition","ProcedureStep","ProcedureVersion"],connections:[{planet:"pricing",desc:"Pricing procedures use the procedure engine for calculations"},{planet:"transactions",desc:"Procedures handle document processing and transformations"}]},
    {id:"expression-sets",name:"Expression Sets",icon:"\u{1F9EE}",desc:"Provides a formula-based calculation framework for defining business rules without code. Expression sets contain one or more expressions that evaluate input variables, perform arithmetic or logical operations, and produce output values. Expressions support standard mathematical operators, conditional logic (IF-THEN-ELSE), string manipulation, date arithmetic, and cross-reference lookups. Expression sets can be chained together for multi-step calculations and are commonly used within pricing procedures, rating procedures, and approval rules to evaluate deal-specific criteria.",tags:["ExpressionSet","Expression","ExpressionVariable"],connections:[{planet:"pricing",desc:"Expression sets perform pricing calculations"},{planet:"rates",desc:"Rating procedures use expressions for charge calculation"}]},
    {id:"decision-tables",name:"Decision Tables",icon:"\u{1F5C2}",desc:"Captures complex conditional logic in a spreadsheet-like table format that is easier to maintain than nested IF statements. Each row in a decision table represents a rule with input conditions and output values. When the table is evaluated, rows are checked in order and the first matching row (or all matching rows, depending on configuration) produces the output. Decision tables are ideal for scenarios like region-based pricing, product eligibility matrices, and tax rate lookups where the logic involves many combinations of input values.",tags:["DecisionTable","DecisionTableRow","DecisionTableColumn"],connections:[{planet:"pricing",desc:"Decision tables drive matrix-based pricing lookups"}]},
    {id:"context-definitions",name:"Context Definitions",icon:"\u{1F4DA}",desc:"Describes the data structure available to business rules during execution. A context definition maps out which objects and fields are accessible, how they relate to each other, and what format the data takes. When a procedure or expression set runs, it operates within a specific context that determines what information it can read and write. Context definitions support nested data structures, lists, and cross-object references, enabling rules to work with complex transaction data spanning quotes, orders, line items, and customer accounts.",tags:["ContextDefinition","ContextNode","ContextMapping"],connections:[]},
    {id:"batch-processing",name:"Batch Processing",icon:"\u{1F504}",desc:"Enables high-volume execution of business rules against large datasets. Batch processing takes a procedure or expression set and runs it against thousands or millions of records, handling chunking, error recovery, and progress tracking automatically. Common use cases include recalculating prices across an entire price book after a rate change, processing end-of-month billing events, and applying new business rules retroactively to existing records. Batch jobs can be scheduled to run at specific times and monitored through the operations console.",tags:["BatchProcess","BatchJob","BatchSchedule","BatchMonitor"],connections:[{planet:"intelligence",desc:"Batch job status and metrics appear in the operations console"}]}
  ],
  dataFlow:["Business rule is invoked by a pricing, rating, or approval process","Context definition determines available data for the rule","Procedure steps, expressions, or decision tables evaluate the logic","Output values are returned to the calling process","Batch processing handles high-volume rule execution"],
  connections:[{planet:"transactions",desc:"Document processing engine handles quote line imports"}]
},

agentforce: {
  packages: ['core'],
  name: "Agentforce for Revenue",
  icon: "\u{1F916}",
  color: "#a855f7",
  description: "Brings AI-powered agents into revenue operations to assist sales reps, billing analysts, and operations teams. Agentforce agents understand natural language requests and can perform actions across quotes, orders, billing, and analytics. Agents are configured with specific skills and guardrails that define what they can do and what requires human approval, ensuring AI assistance stays within safe operational boundaries.",
  components: [
    {id:"ai-agent-setup",name:"AI Agent Setup",icon:"\u{2699}",desc:"Configures the AI agents that will assist users across Revenue Cloud. Agent setup includes defining the agent's persona (name, description, greeting), selecting which skills the agent can use (like creating quotes, looking up billing information, or generating reports), and setting guardrails that prevent the agent from taking high-risk actions without human confirmation. Each agent can be scoped to specific user groups or roles, so a sales-focused agent has different capabilities than a billing-focused agent. Agent setup also manages the knowledge base that agents reference when answering questions.",tags:["AgentDefinition","AgentSkill","AgentGuardrail","AgentPersona"],connections:[{planet:"transactions",desc:"Agents are configured with skills for quote and order operations"},{planet:"billing",desc:"Agents are configured with skills for billing inquiries"}]},
    {id:"agent-actions",name:"Agent Actions",icon:"\u{26A1}",desc:"The specific operations that AI agents can perform on behalf of users. Actions range from simple lookups (find a customer's billing history) to complex multi-step processes (create a renewal quote with updated pricing). Each action has defined inputs, outputs, and confirmation requirements. Some actions execute immediately (retrieving information), while others require user confirmation before making changes (submitting a quote for approval). Actions can be composed together to handle complex requests, like analyzing a customer's usage patterns and recommending an optimized subscription tier.",tags:["AgentAction","ActionDefinition","ActionConfirmation","ActionComposition"],connections:[{planet:"transactions",desc:"Actions can create and modify quotes and orders"},{planet:"billing",desc:"Actions can look up and explain billing details"},{planet:"intelligence",desc:"Actions can generate reports and analytics summaries"}]},
    {id:"agent-monitoring",name:"Agent Monitoring",icon:"\u{1F4CA}",desc:"Tracks how AI agents are being used and how well they are performing. Monitoring dashboards show conversation volumes, action success rates, user satisfaction scores, and topics that agents frequently cannot resolve. Conversation logs provide full transcripts for quality review, with the ability to flag interactions for training improvement. Performance alerts notify administrators when agent accuracy drops below acceptable thresholds or when agents encounter repeated errors with specific action types. This feedback loop drives continuous improvement of agent capabilities.",tags:["AgentMonitoring","AgentMetrics","ConversationLog","AgentAlert"],connections:[{planet:"intelligence",desc:"Agent performance metrics feed into operational dashboards"}]}
  ],
  dataFlow:["User sends a natural language request to the AI agent","Agent interprets the request and selects the appropriate action","Action executes against Revenue Cloud data with guardrail checks","Agent presents results and asks for confirmation if needed","Conversation is logged for monitoring and quality improvement"],
  connections:[{planet:"transactions",desc:"AI agents assist with quote and order creation"},{planet:"billing",desc:"AI agents help with billing inquiries"}]
},

intelligence: {
  packages: ['core'],
  name: "Revenue Intelligence",
  icon: "\u{1F4CA}",
  color: "#ec4899",
  description: "Provides visibility into revenue operations through dashboards, analytics, and an operations console. Revenue Intelligence transforms transaction, billing, and fulfillment data into actionable insights that help leaders understand business performance, identify trends, and make informed decisions. The domain aggregates data from across Revenue Cloud into unified views that span the full quote-to-cash lifecycle.",
  components: [
    {id:"revenue-dashboards",name:"Revenue Dashboards",icon:"\u{1F4CA}",desc:"Pre-built and customizable dashboard views that display key revenue metrics. Dashboards cover areas like pipeline analysis (quotes by stage, conversion rates, average deal size), billing performance (invoices generated, collection rates, days sales outstanding), and customer analytics (revenue by segment, churn indicators, expansion revenue). Each dashboard supports date range filtering, drill-down into underlying records, and export for executive presentations. Administrators can create custom dashboards tailored to specific roles like sales leadership, finance, or operations.",tags:["RevenueDashboard","DashboardComponent","DashboardFilter"],connections:[{planet:"billing",desc:"Dashboards display billing and revenue data"},{planet:"transactions",desc:"Dashboards show pipeline and deal analytics"}]},
    {id:"revenue-insights",name:"Revenue Insights",icon:"\u{1F4A1}",desc:"AI-generated observations and recommendations based on patterns in your revenue data. Insights automatically surface trends like declining deal sizes in a specific segment, increasing discount rates for a product line, or seasonal patterns in usage consumption. Each insight includes the underlying data, a plain-language explanation of the trend, and suggested actions. Insights are delivered proactively through notifications and appear contextually on relevant records, helping users spot opportunities and risks they might otherwise miss.",tags:["RevenueInsight","InsightRecommendation","TrendAnalysis"],connections:[{planet:"pricing",desc:"Pricing insights identify discount trends and margin opportunities"},{planet:"billing",desc:"Billing insights highlight collection patterns and revenue leakage"}]},
    {id:"operations-console",name:"Operations Console",icon:"\u{1F4BB}",desc:"A centralized monitoring interface for revenue operations teams. The console provides a real-time view of system health across all Revenue Cloud domains: batch job statuses, integration sync results, error queues requiring attention, and processing backlogs. Operators can view and retry failed transactions, monitor API usage and rate limits, and track the progress of large-scale operations like billing runs or price updates. Alert configurations notify teams when key metrics exceed thresholds, and incident timelines help with root cause analysis when issues occur.",tags:["OperationsConsole","SystemHealth","ErrorQueue","AlertConfiguration"],connections:[{planet:"procedures",desc:"Console shows batch processing status and results"},{planet:"orchestrator",desc:"Console displays fulfillment progress and blockers"}]}
  ],
  dataFlow:["Transaction, billing, and fulfillment data flows into analytics","Dashboards aggregate and visualize key revenue metrics","AI engine analyzes patterns and generates proactive insights","Operations console monitors system health and processing status","Alerts notify teams when metrics exceed configured thresholds"],
  connections:[{planet:"billing",desc:"Dashboards display billing and revenue data"}]
},

setup: {
  packages: ['core'],
  name: "Setup and Administration",
  icon: "\u{2699}",
  color: "#d946ef",
  description: "The control center for configuring and maintaining your Revenue Cloud implementation. Setup covers everything from initial implementation planning and permission management to ongoing configuration of revenue-specific settings. This domain also manages the migration path from legacy CPQ and billing solutions and supports Experience Cloud integration for customer-facing portals.",
  components: [
    {id:"implementation-planning",name:"Implementation Planning",icon:"\u{1F5FA}",desc:"Guides administrators through the process of setting up Revenue Cloud for the first time. Implementation planning includes readiness assessments that evaluate your current Salesforce configuration, recommended implementation sequences that build capabilities in the right order, and checklists that track completion of configuration steps. The planning tools identify dependencies between features, ensuring that foundational elements like products and pricing are in place before configuring advanced capabilities like orchestration and usage billing.",tags:["ImplementationPlan","ReadinessCheck","SetupChecklist","FeatureDependency"],connections:[]},
    {id:"permissions-users",name:"Permissions and Users",icon:"\u{1F512}",desc:"Controls who can access and modify Revenue Cloud data and functionality. Permission sets define granular access to features like quote creation, price override authority, billing schedule modification, and administrative settings. User assignments determine which permission sets each user receives, and permission set groups bundle common combinations for easy assignment to roles like sales rep, deal desk analyst, or billing administrator. Field-level security controls visibility of sensitive data like cost and margin fields, ensuring users see only what they need for their role.",tags:["PermissionSet","PermissionSetGroup","UserAssignment","FieldLevelSecurity"],connections:[{planet:"approvals",desc:"Permission levels determine approval authority"},{planet:"transactions",desc:"Permissions control who can create and modify quotes and orders"}]},
    {id:"revenue-settings",name:"Revenue Settings",icon:"\u{1F527}",desc:"Centralizes configuration of Revenue Cloud behavior across all domains. Revenue settings include pricing defaults (default currency, rounding rules, price precision), billing configuration (default payment terms, invoice number format, dunning settings), fulfillment preferences (default fulfillment plans, asset creation rules), and general behavior settings (fiscal year, multi-currency support, localization). Settings are organized by domain for easy navigation, with descriptions explaining the impact of each option. Changes to settings take effect immediately or on the next billing cycle, depending on the setting type.",tags:["RevenueSettings","BillingSettings","PricingSettings","SystemConfiguration"],connections:[{planet:"billing",desc:"Billing policies and tax engines are configured here"},{planet:"pricing",desc:"Pricing defaults and rounding rules are set here"}]},
    {id:"migration-upgrades",name:"Migration and Upgrades",icon:"\u{1F4E4}",desc:"Supports organizations transitioning from Salesforce CPQ, Salesforce Billing, or other legacy quoting and billing systems to Revenue Cloud. Migration tools analyze your existing configuration (products, price books, price rules, billing schedules) and map them to Revenue Cloud equivalents. Data migration utilities transfer historical quotes, orders, and billing records while preserving relationships and audit trails. The upgrade path includes a coexistence period where both old and new systems can operate simultaneously, allowing phased rollout by business unit or product line.",tags:["MigrationTool","DataMigration","LegacyMapping","CoexistenceConfig"],connections:[]},
    {id:"experience-cloud",name:"Experience Cloud",icon:"\u{1F310}",desc:"Extends Revenue Cloud capabilities to customer-facing portals built on Salesforce Experience Cloud. Customers and partners can view their orders, track fulfillment status, access invoices, make payments, and manage subscriptions through self-service portals. The Experience Cloud integration includes pre-built components for common scenarios like invoice payment, subscription management, and usage monitoring. Portal administrators can customize which features are available to different user types and apply branding to match the organization's visual identity.",tags:["ExperienceCloud","PortalComponent","SelfServiceConfig","CustomerPortal"],connections:[{planet:"billing",desc:"Customers view and pay invoices through the portal"},{planet:"transactions",desc:"Partners can create and manage orders through the portal"}]}
  ],
  dataFlow:["Administrator plans implementation using readiness tools","Permissions and user assignments are configured for each role","Revenue settings are tuned for the organization's requirements","Migration tools transfer data from legacy systems","Experience Cloud extends capabilities to external users"],
  connections:[{planet:"catalog",desc:"Catalog permissions managed in settings"},{planet:"billing",desc:"Billing policies and tax engines in settings"}]
}

};
