export const PRODUCT = {

omniscripts: {
  packages: ['omnistudio'],
  name: "OmniScripts",
  icon: "\u{1FA84}",
  color: "#a78bfa",
  description: "The heart of OmniStudio's guided experience framework. OmniScripts let you build multi-step, guided processes that walk users through complex workflows without writing code. The visual designer provides a drag-and-drop canvas where you compose steps from a rich palette of input elements, display elements, and server-side actions. Each OmniScript compiles into an optimized Lightning Web Component for production performance, with versioning and activation controls for safe iteration. OmniScripts support session persistence for long-running processes, enabling users to save progress and resume later. They can be embedded in Lightning pages, Experience Cloud sites, or invoked by Agentforce actions.",
  components: [
    {id:"os-designer",name:"OmniScript Designer",icon:"\u{1F3A8}",desc:"The visual canvas for building guided processes. Administrators drag elements from the palette onto steps, configure properties, and wire up data bindings and actions. The designer provides real-time preview, JSON data inspection, and a component tree for navigating complex scripts. Templates and cloning accelerate development, and the designer validates element configurations before activation.",tags:["OmniProcess","OmniProcessElement"],connections:[{planet:"flexcards",desc:"OmniScripts launch FlexCards as embedded displays"},{planet:"integration",desc:"OmniScripts invoke Integration Procedures for server-side logic"},{planet:"datamappers",desc:"OmniScripts use DataRaptors for data read and write operations"},{planet:"formulas",desc:"OmniScripts evaluate formula expressions in SetValues and calculations"},{planet:"lwc",desc:"OmniScripts host custom LWC elements in the designer palette"}]},
    {id:"os-input-elements",name:"Input Elements",icon:"\u{1F4DD}",desc:"Eighteen input types for collecting user data within guided processes. Includes Text, Number, Currency, Date, Time, Email, URL, Telephone, Password, TextArea, Select, Multi-Select, Lookup, Checkbox, Radio, Range, File Upload, and Signature Capture. Each input supports validation rules, conditional visibility, default values, and data binding to the OmniScript JSON data model.",tags:["OmniProcessElement"],connections:[]},
    {id:"os-display-elements",name:"Display & Formula Elements",icon:"\u{1F4CA}",desc:"Elements for presenting computed data and controlling layout within steps. Disclosure elements create collapsible sections, Formula elements evaluate expressions in real-time, Aggregate elements summarize data across repeatable blocks, and SetValues elements perform silent data transformations in the background. These elements let you build dynamic, responsive step layouts that react to user input without round-trips to the server.",tags:["OmniProcessElement"],connections:[{planet:"formulas",desc:"Display elements use formula functions for computed values"}]},
    {id:"os-action-elements",name:"Action Elements",icon:"\u{26A1}",desc:"Server-side operation elements that connect OmniScripts to backend systems. Integration Procedure Actions invoke IP flows, DataRaptor Actions read and write Salesforce data, Remote Actions call Apex classes, HTTP Actions make REST callouts, Email Actions send templated messages, DocuSign Actions trigger e-signature workflows, and Navigate Actions redirect users on completion. Actions can execute on step entry, step exit, or user click.",tags:["OmniProcessElement","OmniProcess"],connections:[{planet:"integration",desc:"Action elements execute Integration Procedures"},{planet:"datamappers",desc:"Action elements invoke DataRaptor operations"},{planet:"config",desc:"Action elements reference e-signature and interaction configurations"}]},
    {id:"os-groups",name:"Step & Group Elements",icon:"\u{1F4C2}",desc:"Structural elements for organizing OmniScript content. Steps define the top-level pages in a guided process with navigation controls. Edit Blocks create repeatable groups of elements for collecting list data. Action Blocks group multiple actions into a single execution unit. Radio Groups present mutually exclusive option sets. These grouping elements control the flow, branching, and conditional logic of the overall process.",tags:["OmniProcessElement"],connections:[]},
    {id:"os-sessions",name:"Saved Sessions & Resume",icon:"\u{1F4BE}",desc:"Session persistence for long-running guided processes. When enabled, OmniScripts automatically save user progress so they can close the browser and resume later from exactly where they left off. Saved sessions capture the full JSON data model state, the current step position, and any uploaded files. Administrators can configure auto-save intervals, session expiration policies, and resume URLs. Session data is stored in OmniscriptSavedSession records with full audit trail.",tags:["OmniscriptSavedSession","OmniProcessTransientData"],connections:[]},
    {id:"os-compilation",name:"Activation & Compilation",icon:"\u{2699}",desc:"Compiles OmniScript definitions into optimized Lightning Web Component bundles for production execution. Activation locks the design and generates a deployable LWC that loads significantly faster than the interpreted version. Version management lets teams maintain multiple versions with clear active/inactive lifecycle states. Compilation validates all element references and data bindings, catching errors before deployment. Deactivation reverts to the previous active version automatically.",tags:["OmniProcessCompilation","OmniProcess"],connections:[{planet:"deployment",desc:"Compiled OmniScripts are packaged in DataPacks for migration"},{planet:"testing",desc:"Compiled OmniScripts are validated in preview and test frameworks"}]}
  ],
  dataFlow:["Designer assembles steps with input, display, and action elements","User launches the OmniScript and navigates through steps","Input elements collect data into the JSON data model","Action elements invoke Integration Procedures and DataRaptors","Completion triggers final save, navigation, or downstream processes"],
  connections:[{planet:"flexcards",desc:"OmniScripts embed FlexCards for data display"},{planet:"integration",desc:"OmniScripts invoke Integration Procedures for server logic"},{planet:"datamappers",desc:"OmniScripts call DataRaptors for data read/write"},{planet:"formulas",desc:"OmniScripts use formula functions in calculations"},{planet:"analytics",desc:"OmniScript interactions are tracked for analytics"},{planet:"testing",desc:"OmniScripts are validated in preview and test tools"},{planet:"agentforce",desc:"OmniScripts are exposed as Agentforce actions"},{planet:"experience",desc:"OmniScripts are embedded in Experience Cloud pages"},{planet:"config",desc:"OmniScripts read interaction configuration settings"},{planet:"deployment",desc:"OmniScripts are exported via DataPacks"},{planet:"lwc",desc:"OmniScripts host custom LWC elements"}]
},

flexcards: {
  packages: ['omnistudio'],
  name: "FlexCards",
  icon: "\u{1F5C2}",
  color: "#f472b6",
  description: "A declarative UI framework for building contextual data cards that surface the right information at the right time. FlexCards pull data from multiple sources and render it in compact, visually rich card layouts with conditional states and interactive actions. The visual designer lets you compose card layouts without code, bind data from Integration Procedures, SOQL queries, Apex, or REST APIs, and define multiple card states that switch based on data conditions. FlexCards can launch OmniScripts, navigate to records, or open flyout panels. They support nesting through child cards, enabling modular and reusable UI compositions across Lightning pages and Experience Cloud sites.",
  components: [
    {id:"fc-designer",name:"FlexCard Designer",icon:"\u{1F3A8}",desc:"The visual editor for building card layouts and managing card states. The designer provides a canvas where you arrange fields, images, icons, and action buttons into responsive layouts. A real-time preview shows how the card renders with live data. The property panel lets you configure each element's data binding, styling, and conditional visibility. Templates accelerate development by providing pre-built card patterns for common use cases.",tags:["OmniUiCard"],connections:[{planet:"omniscripts",desc:"FlexCards launch OmniScripts from action buttons"},{planet:"integration",desc:"FlexCards invoke Integration Procedures as data sources"},{planet:"lwc",desc:"FlexCards embed custom LWC components for extended functionality"}]},
    {id:"fc-datasources",name:"Data Sources",icon:"\u{1F50C}",desc:"Connects FlexCards to backend data through multiple provider types. Integration Procedure data sources invoke server-side flows for complex data assembly. SOQL data sources run queries directly against Salesforce objects. Apex data sources call custom controller methods. REST data sources fetch from external APIs. Streaming API sources enable real-time card updates when underlying data changes. Each data source maps response fields to card elements through a visual binding interface.",tags:["OmniUiCard"],connections:[{planet:"integration",desc:"Data sources invoke Integration Procedures for complex data assembly"},{planet:"datamappers",desc:"Data sources use DataRaptors for Salesforce data queries"}]},
    {id:"fc-states",name:"Card States & Conditions",icon:"\u{1F504}",desc:"Enables conditional rendering where a single FlexCard switches between different layouts based on data values. Each state defines its own element arrangement, styling, and actions, and condition logic determines which state is active. States can represent record statuses (Open, Closed, Escalated), user roles, or any data-driven scenario. Default states handle cases where no condition matches, ensuring the card always renders meaningful content.",tags:["OmniUiCard"],connections:[]},
    {id:"fc-actions",name:"Actions & Flyouts",icon:"\u{1F3AF}",desc:"Interactive capabilities that make FlexCards actionable rather than purely informational. Actions can launch OmniScripts in modals or inline, navigate to record pages, invoke quick actions, or trigger custom JavaScript. Flyout panels open as slide-out overlays containing additional FlexCards or OmniScripts, keeping the user in context while performing related tasks. Action visibility can be conditional based on data values or user permissions.",tags:["OmniUiCard","OmniProcess"],connections:[{planet:"omniscripts",desc:"Actions launch OmniScripts as modals or inline guided processes"},{planet:"agentforce",desc:"FlexCard actions integrate with Agentforce workflows"}]},
    {id:"fc-child-cards",name:"Child Cards & Embedding",icon:"\u{1F4E6}",desc:"Enables modular card composition through nesting. A parent FlexCard can embed child FlexCards that receive data context from the parent, creating reusable card components that maintain consistent layouts across different contexts. Child cards can be repeated over list data, creating dynamic card grids. This composition pattern encourages building a library of small, focused cards that combine into rich contextual displays.",tags:["OmniUiCard"],connections:[{planet:"experience",desc:"Composed FlexCards are placed on Experience Cloud pages"}]}
  ],
  dataFlow:["Data source fetches records from Integration Procedures, SOQL, or APIs","Card state conditions evaluate against the returned data","Active state renders the appropriate layout with bound fields","User interacts with action buttons or flyout triggers","Actions launch OmniScripts, navigate, or invoke backend operations"],
  connections:[{planet:"omniscripts",desc:"FlexCards are embedded in OmniScripts as display elements"},{planet:"integration",desc:"FlexCards use Integration Procedures as data sources"},{planet:"datamappers",desc:"FlexCards read data through DataRaptor queries"},{planet:"testing",desc:"FlexCards are tested with preview and UTAM framework"},{planet:"agentforce",desc:"FlexCards serve as context surfaces for agent actions"},{planet:"experience",desc:"FlexCards are placed on Experience Cloud pages"},{planet:"deployment",desc:"FlexCards are exported via DataPacks"},{planet:"lwc",desc:"FlexCards host custom LWC components"}]
},

integration: {
  packages: ['omnistudio'],
  name: "Integration Procedures",
  icon: "\u{1F5A7}",
  color: "#38bdf8",
  description: "The server-side orchestration engine that assembles data, executes business logic, and coordinates callouts without writing Apex code. Integration Procedures (IPs) define declarative action flows that run on the server with full transaction control. The visual designer lets you chain DataRaptor operations, HTTP callouts, Apex invocations, conditional branching, loops, and error handling into complex integration flows. IPs support caching for performance-critical paths, compilation for optimized execution, and can invoke Decision Matrices and Expression Sets for rules-based logic. They serve as the primary backend for OmniScripts and FlexCards.",
  components: [
    {id:"ip-designer",name:"IP Designer",icon:"\u{1F3A8}",desc:"The visual canvas for building server-side action flows. The designer presents a vertical action sequence where you add, reorder, and configure processing steps. Each action type has a dedicated configuration panel for setting inputs, outputs, and execution options. The designer shows the data shape at each step, helping you trace how data transforms through the flow. Debug mode lets you execute the procedure step by step with full JSON inspection at each stage.",tags:["OmniProcess","OmniProcessElement"],connections:[{planet:"omniscripts",desc:"OmniScripts invoke Integration Procedures for backend processing"},{planet:"flexcards",desc:"FlexCards use Integration Procedures as data sources"},{planet:"config",desc:"IP execution respects interaction configuration settings"}]},
    {id:"ip-data-actions",name:"Data Actions",icon:"\u{1F4C0}",desc:"DataRaptor-based actions for reading, writing, and transforming Salesforce data within an Integration Procedure. Extract actions query records using DataRaptor definitions, Post actions write data back to Salesforce objects, Transform actions reshape JSON structures without database access, and Turbo Extract actions perform high-performance bulk reads. Data actions form the backbone of most Integration Procedures, handling the CRUD operations that OmniScripts and FlexCards depend on.",tags:["OmniProcess","OmniDataTransformation"],connections:[{planet:"datamappers",desc:"Data actions invoke DataRaptor definitions for CRUD operations"}]},
    {id:"ip-http-remote",name:"HTTP & Remote Actions",icon:"\u{1F310}",desc:"Actions for communicating with external systems and custom Apex code. HTTP Actions make REST or SOAP callouts to third-party APIs with configurable headers, authentication, and response mapping. Remote Actions invoke Apex classes implementing the Callable interface, bridging declarative flows with custom code when needed. Email Actions send templated notifications through Salesforce email services. These actions extend Integration Procedures beyond Salesforce data into the broader integration landscape.",tags:["OmniProcess"],connections:[]},
    {id:"ip-flow-control",name:"Flow Control Blocks",icon:"\u{1F500}",desc:"Structural elements that control execution flow within an Integration Procedure. If-Else blocks create conditional branches based on data values or expression evaluation. Loop blocks iterate over list data, executing child actions for each item. Try-Catch blocks provide error handling with fallback logic when actions fail. Cache blocks store action results for configurable durations, dramatically improving performance for frequently accessed data that changes infrequently.",tags:["OmniProcessElement"],connections:[]},
    {id:"ip-decision-actions",name:"Decision & Intelligence Actions",icon:"\u{1F9E0}",desc:"Actions that invoke rules-based decision logic within Integration Procedures. Decision Matrix actions look up values from configurable matrix tables based on input criteria, supporting complex pricing, eligibility, and routing decisions. Expression Set actions evaluate multi-step business rules with variable assignments and conditional logic. Assert actions validate data conditions and halt execution with descriptive errors when assertions fail, enforcing data integrity throughout the flow.",tags:["OmniProcess"],connections:[{planet:"formulas",desc:"Decision actions use expression evaluation for complex rule logic"}]},
    {id:"ip-utility-actions",name:"Utility Actions",icon:"\u{1F6E0}",desc:"General-purpose actions for common operations within Integration Procedures. Batch actions process multiple records efficiently in bulk. List actions manipulate array data with add, remove, sort, and filter operations. Set Values actions assign static or computed values to the data model. Delete actions remove records from Salesforce objects. Chatter actions post to feeds and groups. Response actions shape the final output JSON returned to the calling OmniScript or FlexCard.",tags:["OmniProcess"],connections:[]},
    {id:"ip-compilation",name:"IP Activation & Caching",icon:"\u{1F680}",desc:"Compilation and performance optimization for Integration Procedures. Activation compiles the procedure definition into an optimized execution plan, validating all action references and data bindings. Cache Block configuration lets administrators define TTL values for frequently accessed data, reducing database queries and API callouts. Version management supports multiple procedure versions with clear lifecycle states. Performance monitoring tracks execution times and cache hit rates for optimization.",tags:["OmniProcessCompilation","OmniProcess"],connections:[{planet:"deployment",desc:"Compiled Integration Procedures are packaged in DataPacks"}]}
  ],
  dataFlow:["OmniScript or FlexCard invokes the Integration Procedure","Data actions extract records from Salesforce via DataRaptors","Flow control blocks apply conditional logic, loops, and error handling","HTTP and Remote actions call external APIs and Apex classes","Response action shapes the output JSON returned to the caller"],
  connections:[{planet:"omniscripts",desc:"Integration Procedures provide backend logic for OmniScripts"},{planet:"flexcards",desc:"Integration Procedures serve as data sources for FlexCards"},{planet:"datamappers",desc:"Integration Procedures invoke DataRaptor operations"},{planet:"formulas",desc:"Integration Procedures use formula expressions in decision logic"},{planet:"config",desc:"Integration Procedures respect interaction configuration"},{planet:"deployment",desc:"Integration Procedures are exported via DataPacks"}]
},

datamappers: {
  packages: ['omnistudio'],
  name: "DataRaptors",
  icon: "\u{1F504}",
  color: "#fb923c",
  description: "The declarative data access layer that handles all reading, writing, and transformation of Salesforce data within OmniStudio. DataRaptors provide a visual interface for building SOQL queries, mapping JSON fields to SObject fields for DML operations, and reshaping data structures without touching the database. Four types serve distinct purposes: Extract reads data, Load writes data, Transform reshapes JSON, and Turbo Extract handles high-performance bulk reads. DataRaptors are the primary mechanism through which OmniScripts and Integration Procedures interact with Salesforce data, replacing the need for custom Apex data access classes.",
  components: [
    {id:"dm-extract",name:"Extract (Read)",icon:"\u{1F4E5}",desc:"A declarative SOQL query builder that reads data from Salesforce objects and returns it as structured JSON. The visual interface lets you select objects, fields, and filter criteria without writing SOQL. Extract supports parent-child relationship queries, cross-object field references, and dynamic filter values passed from calling OmniScripts or Integration Procedures. Field-level output mapping transforms the raw query results into the JSON structure your components expect.",tags:["OmniDataTransformation","OmniDataTransformationItem"],connections:[{planet:"omniscripts",desc:"OmniScripts invoke Extract DataRaptors to populate form data"},{planet:"integration",desc:"Integration Procedures use Extract actions for data retrieval"}]},
    {id:"dm-load",name:"Load (Write)",icon:"\u{1F4E4}",desc:"Maps JSON data from OmniScript or Integration Procedure output to Salesforce object fields for DML operations. The visual mapper lets you bind JSON paths to SObject fields, handling both insert and upsert operations. Load supports multi-object writes in a single operation, with configurable field mappings for parent and child records. Error handling captures DML exceptions and returns them to the calling component for user-friendly error display.",tags:["OmniDataTransformation","OmniDataTransformationItem"],connections:[{planet:"omniscripts",desc:"OmniScripts invoke Load DataRaptors to save collected data"},{planet:"integration",desc:"Integration Procedures use Post actions to write data via DataRaptors"}]},
    {id:"dm-transform",name:"Transform (JSON-to-JSON)",icon:"\u{1F503}",desc:"Reshapes JSON data structures without any database access, making it a pure data transformation tool. Transform DataRaptors map fields between different JSON schemas, flatten nested structures, aggregate values, and restructure data to match the format expected by downstream components. They are commonly used between Integration Procedure steps to normalize data from different sources before presenting it to OmniScripts or FlexCards.",tags:["OmniDataTransformation","OmniDataTransformationItem"],connections:[{planet:"integration",desc:"Integration Procedures use Transform actions between processing steps"}]},
    {id:"dm-turbo",name:"Turbo Extract",icon:"\u{26A1}",desc:"A high-performance variant of Extract optimized for bulk data reads. Turbo Extract uses a streamlined execution path that bypasses some of the overhead of standard Extract, delivering significantly faster query execution for large result sets. It supports the same visual query builder interface but with additional performance tuning options like field selection optimization and query plan analysis. Best suited for Integration Procedures that need to process thousands of records efficiently.",tags:["OmniDataTransformation","OmniDataTransformationItem"],connections:[{planet:"integration",desc:"Integration Procedures use Turbo Extract for high-volume data reads"}]},
    {id:"dm-formulas",name:"Mapping Formulas",icon:"\u{1F9EE}",desc:"Field-level formula expressions within DataRaptor mappings that compute derived values during extract and transform operations. Formulas can concatenate strings, perform arithmetic on numeric fields, format dates, apply conditional logic with IF/CASE statements, and reference multiple source fields in a single output mapping. These inline formulas reduce the need for separate transformation steps by handling field-level computation directly within the DataRaptor definition.",tags:["OmniDataTransformationItem"],connections:[{planet:"formulas",desc:"Mapping formulas use the same function library as OmniStudio formulas"}]}
  ],
  dataFlow:["Extract DataRaptor queries Salesforce objects and returns JSON","Transform DataRaptor reshapes the data structure for component consumption","OmniScript or FlexCard displays the mapped data to the user","User input is collected and mapped to SObject fields","Load DataRaptor writes the data back to Salesforce records"],
  connections:[{planet:"omniscripts",desc:"DataRaptors provide data read/write for OmniScripts"},{planet:"flexcards",desc:"DataRaptors supply query data for FlexCard data sources"},{planet:"integration",desc:"DataRaptors are invoked as actions within Integration Procedures"},{planet:"formulas",desc:"DataRaptor mappings use formula expressions"},{planet:"deployment",desc:"DataRaptors are exported via DataPacks"}]
},

formulas: {
  packages: ['omnistudio'],
  name: "Functions & Formulas",
  icon: "\u{1D453}",
  color: "#facc15",
  description: "A comprehensive expression language that powers calculations, data transformations, and conditional logic across all OmniStudio components. The formula engine provides over 100 functions spanning math, string manipulation, date operations, list processing, and JSON navigation. Formulas appear in OmniScript SetValues and Formula elements, DataRaptor mapping expressions, and Integration Procedure conditional evaluations. The function library supports eleven data types with automatic coercion and explicit conversion functions, enabling complex business calculations without custom code.",
  components: [
    {id:"fn-math-logic",name:"Math & Logical Functions",icon:"\u{2795}",desc:"Arithmetic and decision-making functions for business calculations. Math functions include ADD, SUBTRACT, MULTIPLY, DIVIDE, MOD, ROUND, CEILING, FLOOR, ABS, and aggregate functions like SUM, AVERAGE, MIN, MAX over lists. Logical functions include IF, CASE, AND, OR, NOT, ISBLANK, and ISNULL for conditional evaluation. These functions power pricing calculations, eligibility checks, and dynamic field visibility rules throughout OmniStudio components.",tags:["OmniProcessElement"],connections:[{planet:"omniscripts",desc:"Math and logical functions power OmniScript calculations"},{planet:"integration",desc:"Logical functions drive conditional branching in Integration Procedures"}]},
    {id:"fn-string",name:"String Functions",icon:"\u{1F524}",desc:"Text manipulation functions for formatting, parsing, and validating string data. Includes CONCATENATE for joining text, LEFT/RIGHT/MID for substring extraction, LEN for length, UPPER/LOWER/PROPER for case conversion, TRIM for whitespace removal, SUBSTITUTE and REPLACE for text replacement, and REGEX for pattern matching and validation. These functions handle display formatting, input normalization, and data cleansing operations across OmniScript and DataRaptor contexts.",tags:["OmniProcessElement"],connections:[]},
    {id:"fn-date-time",name:"Date & Time Functions",icon:"\u{1F4C5}",desc:"Functions for working with dates, times, and durations in business process calculations. TODAY and NOW return current date and datetime values. ADDDAYS, ADDMONTHS, and ADDYEARS perform date arithmetic. DATEFORMAT converts dates to display strings. DATEDIFF calculates intervals between dates. DATEVALUE and DATETIMEVALUE parse strings into date types. These functions power scheduling logic, age calculations, SLA tracking, and deadline management in guided processes.",tags:["OmniProcessElement"],connections:[]},
    {id:"fn-list-json",name:"List & JSON Functions",icon:"\u{1F4CB}",desc:"Functions for navigating and manipulating structured data within OmniStudio's JSON data model. LIST creates arrays from elements, VLOOKUP searches lists by key, FLATTEN converts nested arrays to flat lists, and JSONPath expressions navigate deeply nested JSON structures. COUNT, FIRST, LAST, and SORT operate on list data. These functions are essential for working with multi-record data in Edit Blocks, DataRaptor transforms, and Integration Procedure loops.",tags:["OmniProcessElement","OmniDataTransformationItem"],connections:[{planet:"datamappers",desc:"JSON functions process list data in DataRaptor transformations"}]},
    {id:"fn-datatypes",name:"Data Types & Conversion",icon:"\u{1F522}",desc:"Eleven data types with explicit conversion functions for ensuring type correctness across component boundaries. Supported types include Text, Number, Currency, Date, DateTime, Time, Boolean, Percent, Phone, Email, and URL. Conversion functions TOTEXT, TONUMBER, TODATE, and TODATETIME transform values between types. Type validation functions check data format compliance before processing. Proper type handling prevents calculation errors and ensures consistent data flow between OmniScripts, DataRaptors, and Integration Procedures.",tags:["OmniProcessElement"],connections:[]}
  ],
  dataFlow:["Formula element or SetValues references a function expression","Expression parser tokenizes the formula string","Functions evaluate against the current JSON data context","Type coercion converts operands as needed","Computed result updates the OmniScript data model or DataRaptor mapping"],
  connections:[{planet:"omniscripts",desc:"Formulas power calculations in OmniScript elements"},{planet:"integration",desc:"Formulas drive conditional logic in Integration Procedures"},{planet:"datamappers",desc:"Formulas compute derived values in DataRaptor mappings"}]
},

lwc: {
  packages: ['omnistudio'],
  name: "Custom LWC Extensions",
  icon: "\u{1F4BB}",
  color: "#60a5fa",
  description: "The developer extension point for OmniStudio, enabling custom Lightning Web Components to participate in OmniScript and FlexCard compositions. When the declarative palette doesn't cover a requirement, developers build custom LWC elements that appear alongside standard elements in the designer. Custom elements inherit the OmniScript data context, can read and write to the JSON data model through a documented API, and fire events that integrate with OmniScript navigation and validation. For FlexCards, custom LWC components extend the rendering capabilities beyond the built-in element types.",
  components: [
    {id:"lwc-custom-elements",name:"Custom OmniScript Elements",icon:"\u{1F9E9}",desc:"Developer-built Lightning Web Components that integrate into the OmniScript designer palette as first-class elements. Custom elements extend the OmniElement base class, inheriting data binding, validation, and navigation capabilities. They appear in the designer element palette alongside standard inputs and displays, and administrators can configure their properties through the same property panel. Common use cases include custom file viewers, specialized input controls, map integrations, and rich media displays.",tags:["OmniProcessElement"],connections:[{planet:"omniscripts",desc:"Custom elements appear in the OmniScript designer palette"}]},
    {id:"lwc-custom-cards",name:"Custom FlexCard Components",icon:"\u{1F5BC}",desc:"Lightning Web Components that extend FlexCard rendering beyond the built-in element types. Custom card components receive the FlexCard's data context and can render specialized visualizations, interactive charts, or complex layouts that the declarative designer cannot produce. They integrate with FlexCard actions and can trigger flyouts and OmniScript launches through the card's event system. Developers register custom components as FlexCard-compatible through metadata configuration.",tags:["OmniUiCard"],connections:[{planet:"flexcards",desc:"Custom components extend FlexCard rendering capabilities"}]},
    {id:"lwc-data-binding",name:"Data Context & Events",icon:"\u{1F517}",desc:"The JavaScript API that custom LWC elements use to interact with the OmniScript JSON data model. The omniGetMergeField method reads values from the data tree, omniUpdateDataJson writes values back, and omniValidate integrates with step-level validation. Custom events like omniNavigateTo control step navigation, and omniAggregate participates in Aggregate element calculations. This API ensures custom elements behave identically to built-in elements from the OmniScript engine's perspective.",tags:["OmniProcess","OmniProcessElement"],connections:[{planet:"omniscripts",desc:"Data context API connects custom elements to OmniScript data model"}]}
  ],
  dataFlow:["Developer creates an LWC extending the OmniElement base class","Component is registered in the OmniScript or FlexCard metadata","Designer palette displays the custom element for drag-and-drop placement","At runtime, the element receives data context and renders custom UI","User interactions update the JSON data model through the binding API"],
  connections:[{planet:"omniscripts",desc:"Custom LWCs extend the OmniScript element palette"},{planet:"flexcards",desc:"Custom LWCs extend FlexCard rendering"}]
},

config: {
  packages: ['omnistudio'],
  name: "Configuration & Settings",
  icon: "\u{2699}",
  color: "#64748b",
  description: "Central administration settings that govern how OmniStudio components behave across your org. OmniInteractionConfig records control runtime behavior like session persistence, caching policies, and feature toggles. Global auto number definitions generate sequential identifiers for business processes. Usage-based entitlements track component execution against licensed limits. Electronic signature integration connects OmniScripts to DocuSign templates for legally binding signature capture. These settings provide the operational foundation that all other OmniStudio domains depend on.",
  components: [
    {id:"cfg-interaction",name:"Interaction Configuration",icon:"\u{1F4CB}",desc:"OmniInteractionConfig records that control runtime behavior for OmniStudio components. Configuration settings include session persistence options, caching policies, logging levels, and feature toggles. Administrators can create multiple configuration records for different contexts, such as internal vs. external users, and assign them based on profiles or permission sets. Configuration changes take effect immediately without requiring reactivation of OmniScripts or Integration Procedures.",tags:["OmniInteractionConfig"],connections:[{planet:"omniscripts",desc:"Interaction config controls OmniScript runtime behavior"},{planet:"integration",desc:"Interaction config governs IP caching and execution policies"},{planet:"experience",desc:"Interaction config defines settings for Experience Cloud contexts"}]},
    {id:"cfg-autonumber",name:"Global Auto Number",icon:"\u{1F522}",desc:"Sequential identifier generation for OmniStudio business processes. Auto number definitions create unique, formatted identifiers like case numbers, application IDs, or reference codes that increment automatically. Administrators configure the prefix, suffix, number format, and starting value. Auto numbers are thread-safe and gap-free, suitable for compliance scenarios requiring sequential numbering. They can be invoked from OmniScripts and Integration Procedures through SetValues or dedicated actions.",tags:["OmniProcess"],connections:[{planet:"omniscripts",desc:"Auto numbers generate sequential IDs within guided processes"}]},
    {id:"cfg-entitlements",name:"Usage-Based Entitlements",icon:"\u{1F4CA}",desc:"Execution metering that tracks OmniStudio component usage against licensed limits. Entitlement tracking monitors OmniScript launches, Integration Procedure executions, and DataRaptor operations, providing administrators with visibility into consumption patterns. Dashboard views show current usage against entitled limits with trend analysis. Threshold alerts notify administrators when usage approaches licensed maximums, enabling proactive capacity planning and license optimization.",tags:["OmniInteractionConfig"],connections:[{planet:"analytics",desc:"Entitlement data feeds into analytics dashboards"}]},
    {id:"cfg-esignature",name:"Electronic Signatures",icon:"\u{270D}",desc:"DocuSign template integration that enables legally binding electronic signature capture within OmniScript guided processes. Administrators configure DocuSign connection settings, map signature template fields to OmniScript data, and define signing workflows with multiple signers and signing order. The integration supports envelope status tracking, automatic document generation from OmniScript data, and callback handling to resume the guided process after signing completion.",tags:["OmniElectronicSignatureTemplate"],connections:[{planet:"omniscripts",desc:"E-signature actions are invoked from OmniScript steps"}]}
  ],
  dataFlow:["Administrator creates OmniInteractionConfig records with runtime settings","OmniScript or IP reads applicable configuration at execution time","Auto number definitions generate sequential identifiers on demand","Entitlement tracking records each component execution","Usage dashboards display consumption against licensed limits"],
  connections:[{planet:"omniscripts",desc:"Configuration settings control OmniScript runtime behavior"},{planet:"integration",desc:"Configuration governs Integration Procedure execution"},{planet:"analytics",desc:"Usage entitlements feed analytics reporting"},{planet:"testing",desc:"Configuration settings affect test execution context"},{planet:"experience",desc:"Configuration defines Experience Cloud-specific behavior"}]
},

experience: {
  packages: ['omnistudio'],
  name: "Experience Cloud",
  icon: "\u{1F310}",
  color: "#f87171",
  description: "Extends OmniStudio components to customer-facing and partner portals built on Salesforce Experience Cloud. OmniScripts and FlexCards can be placed directly on Experience Builder pages, providing the same guided process and contextual data card capabilities to external users. Authentication controls manage what data and processes are available to guest vs. authenticated users. Custom LWC extensions built for Experience Cloud contexts handle the unique styling, navigation, and security requirements of portal environments.",
  components: [
    {id:"ec-components",name:"Experience Builder Components",icon:"\u{1F9E9}",desc:"OmniStudio components surfaced as drag-and-drop elements in Experience Builder. OmniScripts and FlexCards appear in the component palette and can be placed on any Experience Cloud page. Administrators configure which OmniScript or FlexCard to display, set component properties, and control responsive behavior. The components automatically adapt their styling to the site's theme and branding, ensuring a consistent visual experience for portal users.",tags:["OmniProcess","OmniUiCard"],connections:[{planet:"omniscripts",desc:"OmniScripts are placed on Experience Cloud pages"},{planet:"flexcards",desc:"FlexCards are rendered on Experience Cloud pages"}]},
    {id:"ec-authentication",name:"Guest & Authenticated Access",icon:"\u{1F512}",desc:"Visibility and data access controls for OmniStudio components in portal environments. Authenticated access leverages the portal user's profile and permission sets to control data visibility within OmniScripts and FlexCards. Guest access enables unauthenticated users to interact with specific OmniScripts for use cases like public intake forms and self-service applications. Administrators configure sharing rules, field-level security, and Integration Procedure execution permissions for each access context.",tags:["OmniProcess"],connections:[{planet:"config",desc:"Authentication settings reference interaction configuration"}]},
    {id:"ec-lwc",name:"Custom LWC Extensions",icon:"\u{1F4BB}",desc:"Lightning Web Components built specifically for Experience Cloud contexts where OmniStudio components need portal-specific customizations. These extensions handle scenarios like custom navigation after OmniScript completion, portal-specific styling overrides, integration with Experience Cloud session management, and custom header or footer components that wrap OmniStudio elements. They extend the standard OmniElement base class with additional portal-aware capabilities.",tags:["OmniProcess","OmniUiCard"],connections:[]}
  ],
  dataFlow:["Experience Builder page includes OmniScript or FlexCard components","Portal user accesses the page with guest or authenticated credentials","Authentication layer determines data visibility and process access","OmniScript or FlexCard renders with portal-appropriate styling","User interactions flow through the same backend as internal users"],
  connections:[{planet:"omniscripts",desc:"OmniScripts are embedded in Experience Cloud pages"},{planet:"flexcards",desc:"FlexCards are displayed on Experience Cloud pages"},{planet:"config",desc:"Experience Cloud uses interaction configuration for portal settings"}]
},

agentforce: {
  packages: ['omnistudio'],
  name: "Agentforce Integration",
  icon: "\u{1F916}",
  color: "#c084fc",
  description: "Connects OmniStudio components to Salesforce's Agentforce platform, enabling AI agents to leverage guided processes and contextual data displays. OmniScripts and Integration Procedures can be exposed as invocable agent actions, allowing agents to execute structured workflows on behalf of users. FlexCards serve as context surfaces that present relevant data to agents during conversations. Multi-component orchestration lets agents chain multiple OmniStudio components together to handle complex customer interactions that span data retrieval, process execution, and decision-making.",
  components: [
    {id:"af-actions",name:"Agent Actions",icon:"\u{26A1}",desc:"OmniScripts and Integration Procedures exposed as invocable actions for Agentforce agents. Administrators mark OmniStudio components as agent-callable and define the input parameters agents provide and the output data agents receive. Agents can launch guided processes, execute backend logic, and return results to the conversation context. Action definitions include natural language descriptions that help agents understand when and how to invoke each action appropriately.",tags:["OmniProcess"],connections:[{planet:"omniscripts",desc:"OmniScripts are exposed as callable agent actions"},{planet:"integration",desc:"Integration Procedures execute as agent backend operations"}]},
    {id:"af-context",name:"Context Surfaces",icon:"\u{1F4C4}",desc:"FlexCards configured as context display surfaces within Agentforce agent interfaces. Context surfaces present relevant customer data, case details, and account information to agents during conversations, giving them the information needed to assist customers effectively. The same FlexCard definitions used in Lightning pages and Experience Cloud are reused as agent context, ensuring consistent data presentation across all channels.",tags:["OmniUiCard"],connections:[{planet:"flexcards",desc:"FlexCards provide contextual data display for agents"}]},
    {id:"af-orchestration",name:"Agent Orchestration",icon:"\u{1F3AF}",desc:"Multi-component workflows that chain OmniStudio elements together for complex agent interactions. Orchestration defines sequences where an agent retrieves data via FlexCards, executes business logic through Integration Procedures, and guides users through OmniScript processes, all within a single conversation flow. Branching logic lets agents choose different paths based on customer responses or data conditions, handling sophisticated service scenarios declaratively.",tags:["OmniProcess"],connections:[{planet:"omniscripts",desc:"Orchestration chains OmniScript guided processes"},{planet:"flexcards",desc:"Orchestration uses FlexCards for agent data context"}]}
  ],
  dataFlow:["Agent receives a customer request during a conversation","Agent action invokes an OmniScript or Integration Procedure","Context surfaces display relevant customer data via FlexCards","Orchestration chains multiple components for complex workflows","Agent returns results and next steps to the conversation"],
  connections:[{planet:"omniscripts",desc:"OmniScripts are exposed as Agentforce actions"},{planet:"flexcards",desc:"FlexCards serve as context surfaces for agents"}]
},

analytics: {
  packages: ['omnistudio'],
  name: "OmniStudio Analytics",
  icon: "\u{1F4C8}",
  color: "#2dd4bf",
  description: "Tracking and measurement capabilities that provide visibility into how users interact with OmniStudio components. Tracking definitions capture events like step entries, element interactions, and process completions within OmniScripts. Engagement metrics aggregate this event data into actionable insights about completion rates, average time per step, and drop-off points. Analytics dashboards visualize these metrics through CRM Analytics, enabling administrators to identify process bottlenecks, optimize step design, and measure the business impact of guided experiences.",
  components: [
    {id:"oa-tracking",name:"Tracking Definitions",icon:"\u{1F4CD}",desc:"Configuration records that define which events are captured during OmniScript execution. Tracking definitions specify the interaction types to monitor: step entries, element clicks, form submissions, error occurrences, and process completions. Each definition maps events to named tracking categories for organized reporting. Administrators enable tracking at the OmniScript level and can configure different tracking granularity for different processes based on analysis needs.",tags:["OmniAnalyticsTrackingDef"],connections:[{planet:"omniscripts",desc:"Tracking definitions capture events from OmniScript execution"}]},
    {id:"oa-metrics",name:"Engagement Metrics",icon:"\u{1F4CA}",desc:"Aggregated measurements derived from raw tracking event data. Engagement metrics calculate completion rates showing what percentage of users finish each OmniScript, average time per step revealing where users spend the most effort, drop-off analysis identifying where users abandon processes, and error frequency highlighting which elements cause the most validation failures. Metrics support filtering by date range, user segment, and OmniScript version for targeted analysis.",tags:["OmniAnalyticsTrackingDef"],connections:[]},
    {id:"oa-dashboards",name:"Analytics Dashboards",icon:"\u{1F4C9}",desc:"CRM Analytics visualization layer for OmniStudio tracking data. Pre-built dashboard templates display key OmniScript performance indicators including funnel views of step completion, heat maps of element interaction frequency, trend charts of usage over time, and comparison views across OmniScript versions. Custom dashboards can be built using the tracked event dataset, enabling administrators to answer specific questions about process efficiency and user behavior patterns.",tags:["OmniAnalyticsTrackingDef"],connections:[{planet:"config",desc:"Dashboards display entitlement usage and configuration metrics"}]}
  ],
  dataFlow:["Tracking definitions are enabled on target OmniScripts","User interactions generate tracking events during execution","Events are aggregated into engagement metrics","CRM Analytics dashboards visualize metrics and trends","Administrators identify bottlenecks and optimize process design"],
  connections:[{planet:"omniscripts",desc:"Analytics track OmniScript user interactions"},{planet:"config",desc:"Analytics report on entitlement usage and configuration"}]
},

testing: {
  packages: ['omnistudio'],
  name: "Testing & Quality",
  icon: "\u{2705}",
  color: "#a3e635",
  description: "Quality assurance tools for validating OmniStudio components during development and before deployment. The UTAM test framework provides page object models for automated browser testing of OmniScripts and FlexCards. The Design Assistant gives real-time feedback during authoring, flagging configuration issues, accessibility violations, and performance concerns before activation. Preview and Debug mode lets developers execute components with live data, inspect the JSON data model at each step, and test conditional logic branches without deploying to production.",
  components: [
    {id:"tq-utam",name:"UTAM Test Framework",icon:"\u{1F9EA}",desc:"UI Test Automation Model page objects for automated testing of OmniStudio components. UTAM provides pre-built page objects for OmniScript steps, input elements, FlexCard states, and action buttons that test scripts can interact with programmatically. Test engineers write automated test suites that navigate through OmniScripts, fill in form data, trigger actions, and validate outcomes. The framework integrates with standard testing tools like WebDriverIO and Jest for CI/CD pipeline integration.",tags:["OmniProcess","OmniUiCard"],connections:[{planet:"omniscripts",desc:"UTAM page objects automate testing of OmniScript flows"},{planet:"flexcards",desc:"UTAM page objects test FlexCard rendering and interactions"}]},
    {id:"tq-design-assistant",name:"Design Assistant",icon:"\u{1F4A1}",desc:"Real-time authoring feedback that analyzes OmniScript and FlexCard configurations as you build them. The Design Assistant flags common issues like missing required field validations, inaccessible color contrast ratios, elements without data bindings, and actions referencing non-existent Integration Procedures. Suggestions are categorized by severity (error, warning, info) and link to documentation explaining the best practice. This proactive quality check reduces the iteration cycles between building and testing.",tags:["OmniProcess","OmniUiCard"],connections:[{planet:"config",desc:"Design Assistant validates against interaction configuration rules"}]},
    {id:"tq-preview",name:"Preview & Debug",icon:"\u{1F50E}",desc:"Live preview mode that executes OmniScripts and FlexCards with real or sample data in the designer context. Preview renders the component exactly as users will see it, including conditional visibility, computed values, and action results. Debug mode adds a JSON panel showing the complete data model state, updated in real-time as you interact with the component. Step-through execution lets you test each step independently and inject test data at any point in the process flow.",tags:["OmniProcess","OmniUiCard"],connections:[{planet:"omniscripts",desc:"Preview mode validates OmniScript behavior before activation"},{planet:"flexcards",desc:"Preview mode tests FlexCard rendering with live data"}]}
  ],
  dataFlow:["Developer builds OmniScript or FlexCard in the designer","Design Assistant provides real-time feedback on configuration quality","Preview mode renders the component with test data for validation","UTAM test suites automate regression testing of component behavior","Validated components are activated and packaged for deployment"],
  connections:[{planet:"omniscripts",desc:"Testing tools validate OmniScript configurations"},{planet:"flexcards",desc:"Testing tools validate FlexCard configurations"},{planet:"config",desc:"Testing respects interaction configuration context"}]
},

deployment: {
  packages: ['omnistudio'],
  name: "Deployment & Migration",
  icon: "\u{1F4E6}",
  color: "#94a3b8",
  description: "Tools for packaging, versioning, and migrating OmniStudio components across Salesforce environments. DataPacks bundle OmniScripts, FlexCards, Integration Procedures, DataRaptors, and their dependencies into portable export files that can be imported into target orgs. Version management controls the activation lifecycle of components, ensuring only one version is active at a time with clear rollback capabilities. Dependency resolution automatically identifies and includes all referenced components when building a DataPack, preventing partial deployments that would break component references in the target environment.",
  components: [
    {id:"dp-datapacks",name:"DataPack Export/Import",icon:"\u{1F4E5}",desc:"Component bundling system for migrating OmniStudio definitions between Salesforce orgs. Export scans a selected component and its dependency tree, generating a structured JSON file containing the complete definition. Import reads the DataPack file and creates or updates components in the target org, with conflict detection for existing definitions. DataPacks support selective export of individual components or bulk export of entire domains. The format is version-controlled and compatible across OmniStudio releases.",tags:["OmniDataPack"],connections:[{planet:"omniscripts",desc:"DataPacks export OmniScript definitions with all elements"},{planet:"flexcards",desc:"DataPacks export FlexCard definitions with states and actions"},{planet:"integration",desc:"DataPacks export Integration Procedure definitions"},{planet:"datamappers",desc:"DataPacks export DataRaptor definitions"}]},
    {id:"dp-versioning",name:"Version Management",icon:"\u{1F4CB}",desc:"Lifecycle controls for managing multiple versions of OmniStudio components. Each OmniScript, FlexCard, Integration Procedure, and DataRaptor supports multiple numbered versions with one active version at a time. Activation compiles the component and makes it the live version. Deactivation reverts to the previous version or removes the component from execution. Version history provides full audit trail of changes, and administrators can compare versions to understand what changed between iterations.",tags:["OmniProcess","OmniUiCard","OmniDataTransformation"],connections:[]},
    {id:"dp-dependencies",name:"Dependency Resolution",icon:"\u{1F517}",desc:"Automatic identification and inclusion of cross-component dependencies during DataPack export. When exporting an OmniScript, the resolver traces all referenced Integration Procedures, DataRaptors, FlexCards, child OmniScripts, and custom LWC references, including them in the export package. Dependency analysis also validates that all references will resolve in the target org, flagging missing components before deployment. This prevents broken references and ensures complete, functional migrations.",tags:["OmniDataPack"],connections:[]}
  ],
  dataFlow:["Administrator selects components for migration in DataPack export","Dependency resolution identifies all referenced components","DataPack bundles definitions into a portable JSON file","Import loads the DataPack into the target org with conflict detection","Version management activates the imported components"],
  connections:[{planet:"omniscripts",desc:"DataPacks package OmniScript definitions"},{planet:"flexcards",desc:"DataPacks package FlexCard definitions"},{planet:"integration",desc:"DataPacks package Integration Procedure definitions"},{planet:"datamappers",desc:"DataPacks package DataRaptor definitions"}]
}

};
