// ══════════════════════════════════════════════════════════════
//  Education Cloud — Domains and Components
//  14 domains covering the complete learner lifecycle
// ══════════════════════════════════════════════════════════════

export const PRODUCT = {

recruitment: {
  packages: ['educationcloud'],
  name: "Recruitment",
  icon: "\u{1F4E3}",
  color: "#3b82f6",
  description: "Manages the top of the enrollment funnel, from first inquiry to application-ready prospect. Recruitment captures leads from campus events, website inquiries, and partner referrals, then nurtures them through targeted campaigns and personalized outreach. AI-powered recruitment agents automate communication sequences and surface high-intent prospects for admissions counselors.",
  components: [
    {id:"prospect-management",name:"Prospect Management",icon:"\u{1F465}",desc:"Captures and tracks prospective students from initial inquiry through application readiness. Each prospect record stores academic interests, demographic information, communication preferences, and engagement history. Lead scoring models identify prospects most likely to apply based on interaction patterns and qualification criteria.",tags:["Lead","ContactProfile"],connections:[{planet:"admissions",desc:"Qualified prospects submit applications"},{planet:"records",desc:"Prospect data flows into person records"}]},
    {id:"campaign-management",name:"Campaign Management",icon:"\u{1F4E8}",desc:"Orchestrates multi-channel recruitment campaigns targeting specific student populations. Campaigns track open houses, campus visits, virtual events, email sequences, and social media outreach. Campaign members are tracked through response stages to measure yield and conversion rates across recruitment activities.",tags:["Campaign","CampaignMember"],connections:[{planet:"analytics",desc:"Campaign metrics feed recruitment dashboards"}]},
    {id:"recruitment-events",name:"Recruitment Events",icon:"\u{1F3AA}",desc:"Manages campus tours, open houses, information sessions, and virtual recruitment events. Event registration captures attendee details and interests, and post-event follow-up workflows automatically engage attendees based on their level of interest. Event capacity management, waitlists, and reminder notifications keep logistics running smoothly.",tags:["Campaign","CampaignMember"],connections:[{planet:"experience",desc:"Event registration through the prospect portal"}]},
    {id:"recruitment-communications",name:"Recruitment Communications",icon:"\u{1F4EC}",desc:"Manages outbound communications to prospective students across email, SMS, and direct mail channels. Communication templates are personalized with prospect data and academic program details. Delivery tracking monitors open rates, click-throughs, and response patterns to optimize messaging effectiveness and timing.",tags:["ContactPointEmail","ContactPointPhone"],connections:[{planet:"agentforce",desc:"Recruitment agent automates outreach sequences"}]},
    {id:"territory-management",name:"Territory Management",icon:"\u{1F5FA}",desc:"Assigns recruitment counselors to geographic territories, feeder schools, and prospect segments. Territory rules ensure equitable distribution of prospects among counselors and automatic routing of new inquiries to the appropriate recruiter. Territory performance dashboards compare yield rates across regions and counselors.",tags:["Lead"],connections:[{planet:"analytics",desc:"Territory performance feeds recruitment analytics"}]}
  ],
  dataFlow:["Prospect submits inquiry or attends recruitment event","Lead record is created and assigned to a recruitment counselor","Counselor nurtures prospect through targeted campaigns","AI recruitment agent automates personalized outreach","Qualified prospect proceeds to formal application submission"],
  connections:[{planet:"admissions",desc:"Qualified prospects move to applications"},{planet:"records",desc:"Prospect data creates person records"},{planet:"agentforce",desc:"AI recruitment agent automates outreach"},{planet:"experience",desc:"Prospect portal for inquiry and events"},{planet:"analytics",desc:"Recruitment funnel dashboards"}]
},

admissions: {
  packages: ['educationcloud'],
  name: "Admissions",
  icon: "\u{1F4CB}",
  color: "#6366f1",
  description: "Handles the full application lifecycle from submission through document collection, review, and admission decisions. Admissions supports multiple application types including undergraduate, graduate, transfer, and international applications. Configurable review workflows route applications through committee evaluation with scoring rubrics, and automated notifications keep applicants informed at every stage.",
  components: [
    {id:"application-management",name:"Application Management",icon:"\u{1F4C4}",desc:"Manages the creation, submission, and lifecycle of student applications. Each application captures academic history, personal statements, program preferences, and supplemental materials. Applications progress through configurable statuses from draft through submitted, under review, and decision rendered. Multi-cycle support allows the same applicant to apply across multiple terms or programs.",tags:["IndividualApplication","Applicant"],connections:[{planet:"recruitment",desc:"Applications originate from recruited prospects"},{planet:"enrollment",desc:"Admitted students proceed to enrollment"}]},
    {id:"document-tracking",name:"Document Tracking",icon:"\u{1F4CE}",desc:"Manages the collection and verification of required application documents including transcripts, test scores, recommendation letters, essays, and financial documents. Checklist items track which documents have been received, verified, or are still outstanding. Automated reminders notify applicants of missing documents, and bulk document processing handles high-volume intake periods.",tags:["DocumentChecklistItem"],connections:[]},
    {id:"application-review",name:"Application Review",icon:"\u{1F50D}",desc:"Routes applications through structured review workflows with configurable reviewer assignments, scoring rubrics, and decision criteria. Multiple reviewers can evaluate the same application independently, and committee reviews aggregate individual scores into a consensus recommendation. Review dashboards show workload distribution and processing timelines across the admissions team.",tags:["IndividualApplication"],connections:[]},
    {id:"admissions-decisions",name:"Admissions Decisions",icon:"\u{2705}",desc:"Records and communicates admission decisions including accept, deny, waitlist, and conditional admission. Decision letters are generated from templates personalized with student and program details. Conditional offers specify requirements that must be met before enrollment, such as final transcript submission or minimum GPA maintenance. Deposit tracking monitors accepted students who confirm their intent to enroll.",tags:["IndividualApplication","Applicant"],connections:[{planet:"financials",desc:"Admission triggers financial aid packaging"}]},
    {id:"preliminary-applications",name:"Preliminary Applications",icon:"\u{1F4DD}",desc:"Supports early-stage or simplified application forms that capture initial interest before a full application is required. Preliminary applications collect basic demographic information, intended major, and term of entry. These lightweight records help institutions gauge demand for programs and begin building relationships with prospective students before the formal application window opens.",tags:["PreliminaryApplication"],connections:[{planet:"recruitment",desc:"Preliminary apps bridge recruitment and admissions"}]},
    {id:"admissions-console",name:"Admissions Console",icon:"\u{1F5A5}",desc:"A purpose-built staff workspace that surfaces the most important admissions data in a single view. The console displays application queues, review assignments, decision summaries, and key metrics like application volume and yield rates. Quick actions let admissions officers update statuses, assign reviewers, and send communications without navigating away from the console.",tags:["IndividualApplication"],connections:[{planet:"agentforce",desc:"Admissions agent answers applicant questions"}]}
  ],
  dataFlow:["Applicant submits application with required documents","Document checklist tracks receipt and verification of materials","Application is routed to reviewers based on program and criteria","Reviewers score and recommend using structured rubrics","Admissions committee renders final decision","Decision is communicated and applicant responds with intent to enroll"],
  connections:[{planet:"recruitment",desc:"Applications originate from recruited prospects"},{planet:"records",desc:"Applicant data stored on person records"},{planet:"enrollment",desc:"Admitted students enroll in programs"},{planet:"financials",desc:"Application fees and financial aid packaging"},{planet:"agentforce",desc:"AI agent answers applicant questions"},{planet:"experience",desc:"Applicant portal for status tracking"}]
},

academics: {
  packages: ['educationcloud'],
  name: "Academic Operations",
  icon: "\u{1F3EB}",
  color: "#8b5cf6",
  description: "The structural backbone that defines what an institution offers: programs, courses, academic terms, and learning objectives. Academic Operations manages the course catalog, schedules offerings across terms, and establishes the credit equivalency mappings that enable transfer credit evaluation. Faculty and teaching assistant assignments link instructors to specific course offerings.",
  components: [
    {id:"program-management",name:"Program Management",icon:"\u{1F393}",desc:"Defines degree programs, certificates, and academic pathways with their requirements, credit thresholds, and learning outcomes. Each program specifies required and elective course groups, minimum GPA requirements, and prerequisite chains. Program records connect to departments and academic organizations, establishing the institutional hierarchy that governs academic governance and reporting.",tags:["Program"],connections:[{planet:"enrollment",desc:"Students enroll in programs"},{planet:"success",desc:"Program requirements drive learning plans"}]},
    {id:"course-management",name:"Course Management",icon:"\u{1F4DA}",desc:"Maintains the institutional course catalog with course descriptions, credit values, prerequisites, and corequisites. Each course record captures the subject area, course number, and level designation used in academic planning. Courses serve as templates from which specific term offerings are created, separating the permanent course definition from its scheduled instances.",tags:["Course"],connections:[]},
    {id:"course-offerings",name:"Course Offerings",icon:"\u{1F4C5}",desc:"Schedules courses for specific academic terms with assigned instructors, meeting times, locations, and enrollment capacity. Each offering inherits its credit value and description from the parent course while adding term-specific details like section numbers and delivery modes. Capacity management tracks available seats and triggers waitlist behavior when sections fill.",tags:["CourseOffering"],connections:[{planet:"enrollment",desc:"Students register for course offerings"},{planet:"appointments",desc:"Academic advising precedes course registration"}]},
    {id:"academic-terms",name:"Academic Terms",icon:"\u{1F4C6}",desc:"Defines the academic calendar with terms, sessions, and time periods that structure when courses are offered and when milestones occur. Terms establish start and end dates, registration windows, add/drop deadlines, and grade submission periods. Academic time periods provide finer-grained scheduling within terms for institutions that run multiple sessions or mini-terms.",tags:["AcademicTerm","AcademicTimePeriod"],connections:[{planet:"financials",desc:"Terms drive tuition fee schedules"}]},
    {id:"learning-objectives",name:"Learning Objectives",icon:"\u{1F3AF}",desc:"Captures measurable learning outcomes tied to courses and programs. Each objective describes what a student should know or be able to do upon completion, aligned with accreditation standards and institutional assessment frameworks. Objectives link to assessments and competency records, enabling outcome-based education tracking across the curriculum.",tags:["LearningObjective"],connections:[{planet:"success",desc:"Objectives map to competency assessments"}]},
    {id:"transfer-credits",name:"Transfer Credits & Equivalencies",icon:"\u{1F504}",desc:"Evaluates and maps credits earned at other institutions to equivalent courses in the catalog. Equivalency rules define how external courses satisfy internal requirements, considering credit values, content alignment, and grading standards. Transfer credit records track the originating institution, original course details, and the equivalent internal course, streamlining evaluation for transfer students.",tags:["TransferCredit","LearningEquivalency"],connections:[{planet:"records",desc:"Transfer credits link to student education history"}]}
  ],
  dataFlow:["Academic departments define programs with degree requirements","Courses are created in the catalog with prerequisites and credit values","Course offerings are scheduled for specific terms with instructors","Equivalency rules are established for transfer credit evaluation","Academic calendar sets registration windows and deadlines"],
  connections:[{planet:"enrollment",desc:"Programs and courses define what students enroll in"},{planet:"records",desc:"Transfer credits link to student education history"},{planet:"financials",desc:"Course structure drives tuition calculation"},{planet:"success",desc:"Learning objectives tie to competency tracking"}]
},

enrollment: {
  packages: ['educationcloud'],
  name: "Enrollment",
  icon: "\u{1F4D6}",
  color: "#0ea5e9",
  description: "Tracks a student's active participation in programs and courses, from initial program enrollment through course registration, grade recording, and achievement recognition. Enrollment manages the transactional core of the student lifecycle, handling registration holds, waitlists, section changes, and withdrawal processing. Achievement records capture grades and credits that accumulate toward degree completion.",
  components: [
    {id:"program-enrollment",name:"Program Enrollment",icon:"\u{1F3C1}",desc:"Records a student's admission and active participation in a degree program or certificate. Each enrollment tracks the start term, expected graduation date, academic standing, and cumulative GPA. Enrollment status transitions capture the student's journey from admitted through active, on leave, withdrawn, or graduated, providing a complete lifecycle view for advisors and registrars.",tags:["ProgramEnrollment"],connections:[{planet:"admissions",desc:"Enrollment follows admission decisions"},{planet:"records",desc:"Enrollment links to student person records"}]},
    {id:"course-registration",name:"Course Registration",icon:"\u{1F4DD}",desc:"Manages a student's registration in specific course offerings for a given term. Registration records capture the section, credit mode, and registration status. The system enforces prerequisite checks, enrollment capacity limits, and time conflict validation during registration. Add/drop processing handles changes within the academic calendar deadlines.",tags:["CourseOfferingParticipant"],connections:[{planet:"academics",desc:"Registration references course offerings"},{planet:"financials",desc:"Registration triggers fee calculation"}]},
    {id:"academic-achievement",name:"Academic Achievement",icon:"\u{1F3C6}",desc:"Records grades, credits earned, and academic milestones that mark a student's progress toward degree completion. Achievement records link to specific course offerings and capture both attempted and earned credits, grade values, and quality points. Cumulative calculations aggregate achievements across terms to produce GPA, total credits, and dean's list eligibility.",tags:["LearningAchievement"],connections:[{planet:"success",desc:"Achievements feed student success tracking"}]},
    {id:"enrollment-status",name:"Enrollment Status Management",icon:"\u{1F4CA}",desc:"Tracks and enforces enrollment lifecycle states including active, hold, probation, suspension, leave of absence, and withdrawal. Status rules define which transitions are valid and what conditions must be met for each change. Financial holds can block registration until outstanding balances are resolved, and academic holds trigger advising requirements before a student can enroll in the next term.",tags:["ProgramEnrollment"],connections:[{planet:"financials",desc:"Financial holds affect enrollment status"}]},
    {id:"learning-plans",name:"Learning Plans",icon:"\u{1F5FA}",desc:"Creates personalized academic roadmaps that sequence courses across terms toward degree completion. Learning plans factor in prerequisite chains, course availability patterns, and remaining requirements. Advisors and students collaborate on plan adjustments when course changes or life circumstances require a modified path to graduation.",tags:["LearningPlan"],connections:[{planet:"success",desc:"Learning plans support student success tracking"},{planet:"appointments",desc:"Plan adjustments often require advising appointments"}]}
  ],
  dataFlow:["Admitted student is enrolled in a degree program","Student registers for course offerings each term","System enforces prerequisites, capacity limits, and time conflicts","Grades are recorded and achievements accumulate","Learning plans track progress toward degree completion"],
  connections:[{planet:"admissions",desc:"Enrollment follows admission decisions"},{planet:"academics",desc:"Enrollment references courses, programs, and terms"},{planet:"records",desc:"Enrollment records link to person accounts"},{planet:"success",desc:"Enrollment progress feeds student success tracking"},{planet:"financials",desc:"Course registration triggers fee calculation"},{planet:"appointments",desc:"Registration may require advising appointments"}]
},

records: {
  packages: ['educationcloud'],
  name: "Student Records",
  icon: "\u{1F464}",
  color: "#10b981",
  description: "The central person data domain that anchors every other part of Education Cloud. Student Records maintains the unified learner profile built on Salesforce Person Accounts, capturing demographics, contact points, family relationships, education history, examination scores, language proficiency, and employment records. Every domain reads from and writes to student records, making it the gravitational center of the data model.",
  components: [
    {id:"person-accounts",name:"Person Accounts",icon:"\u{1F464}",desc:"The core student record built on the Salesforce Person Account model, combining Account and Contact functionality into a single entity. Each person account stores the student's name, date of birth, citizenship, and institutional identifiers like student ID. The person account serves as the master record that all other domains reference when they need to identify a learner.",tags:["Account"],connections:[{planet:"enrollment",desc:"Person accounts are the identity anchor for enrollments"},{planet:"admissions",desc:"Applicants are linked to person accounts"}]},
    {id:"contact-points",name:"Contact Points",icon:"\u{1F4DE}",desc:"Manages multiple addresses, phone numbers, and email addresses for each student with usage designations like home, school, billing, and emergency. Contact points support effective dating so address changes can be scheduled for future terms. Primary contact point designation determines which address or phone number is used for official communications and mailings.",tags:["ContactPointAddress","ContactPointPhone","ContactPointEmail"],connections:[]},
    {id:"relationships",name:"Relationships & Household",icon:"\u{1F46A}",desc:"Maps family, guardian, and household relationships between person records. Relationship records capture the type, primary contact designation, and communication permissions. Household grouping links related individuals for financial aid dependency calculations, family billing, and sibling discount processing.",tags:["ContactRelationship"],connections:[{planet:"mentoring",desc:"Mentoring profiles reference person relationships"}]},
    {id:"education-history",name:"Education History",icon:"\u{1F4DC}",desc:"Stores prior education records from high school and previous institutions including school name, dates attended, degree earned, GPA, and class rank. Education history supports transfer credit evaluation by providing context about where credits were earned. High school records capture standardized information needed for undergraduate admissions evaluation.",tags:["PersonEducation"],connections:[{planet:"academics",desc:"Education history informs transfer credit evaluation"}]},
    {id:"examinations",name:"Examinations & Test Scores",icon:"\u{1F4DD}",desc:"Records standardized test scores including SAT, ACT, GRE, TOEFL, IELTS, and AP exams. Each examination record captures the test date, individual section scores, composite or total scores, and percentile rankings. Score records are used during admissions evaluation, placement decisions, and credit-by-examination processing.",tags:["PersonExamination"],connections:[{planet:"admissions",desc:"Test scores inform admission decisions"}]},
    {id:"demographics-languages",name:"Demographics & Languages",icon:"\u{1F30D}",desc:"Captures language proficiency levels, employment history, and additional demographic information used for institutional reporting, compliance, and personalized student services. Language records include proficiency levels for reading, writing, speaking, and listening. Employment records track work-study positions, internships, and post-graduation employment for career outcome reporting.",tags:["PersonLanguage","PersonEmployment"],connections:[{planet:"alumni",desc:"Employment data tracks post-graduation outcomes"}]}
  ],
  dataFlow:["Person account is created during recruitment or application","Contact points, relationships, and demographics are populated","Education history and test scores are added for admissions evaluation","Record is enriched throughout the student lifecycle","Post-graduation data tracks alumni employment and engagement"],
  connections:[{planet:"recruitment",desc:"Prospect data creates person records"},{planet:"admissions",desc:"Applicant data stored on person records"},{planet:"academics",desc:"Education history informs transfer credit evaluation"},{planet:"enrollment",desc:"Student identity for all enrollment records"},{planet:"success",desc:"Competencies and traits linked to person"},{planet:"financials",desc:"Financial accounts linked to person records"},{planet:"mentoring",desc:"Mentor/mentee profiles reference person records"},{planet:"alumni",desc:"Alumni status tracked on person records"},{planet:"appointments",desc:"Appointments reference student records"},{planet:"data360",desc:"Identity resolution unifies duplicate person records"}]
},

success: {
  packages: ['educationcloud'],
  name: "Student Success",
  icon: "\u{1F31F}",
  color: "#22c55e",
  description: "Empowers advisors and students to track competencies, personal traits, career interests, and academic progress toward degree completion. Student Success brings together competency assessment, early alert systems, and career development planning into a holistic framework for student support. AI-powered advising agents surface at-risk students and recommend interventions based on engagement patterns and academic performance.",
  components: [
    {id:"competency-tracking",name:"Competency Tracking",icon:"\u{1F4AA}",desc:"Records and assesses student skills and proficiencies against defined competency frameworks. Each competency record captures the skill area, proficiency level, assessment method, and evidence of achievement. Competencies can be mapped to courses and programs, enabling outcome-based education where students demonstrate mastery rather than simply accumulating seat time.",tags:["PersonCompetency"],connections:[{planet:"academics",desc:"Learning objectives map to competency assessments"}]},
    {id:"traits-affinities",name:"Traits & Affinities",icon:"\u{1F9E0}",desc:"Captures student strengths, personality characteristics, and interest areas that inform personalized advising and career guidance. Traits describe observable behaviors and strengths identified through assessments or advisor observations. Affinities record academic subject interests, career aspirations, and extracurricular preferences that help match students with appropriate opportunities and resources.",tags:["PersonTrait","PersonAffinity"],connections:[]},
    {id:"advising",name:"Academic Advising",icon:"\u{1F91D}",desc:"Coordinates advisor-to-student assignments and tracks advising interactions, notes, and action items. Care coordinators manage advisor caseloads and ensure students receive timely guidance. Advising records capture meeting topics, recommendations, and follow-up tasks that create a longitudinal record of the support a student has received throughout their academic journey.",tags:["CareCoordinator","CareRole"],connections:[{planet:"appointments",desc:"Advising sessions scheduled as appointments"},{planet:"agentforce",desc:"AI advising agent surfaces at-risk students"}]},
    {id:"academic-alerts",name:"Academic Alerts",icon:"\u{26A0}",desc:"Triggers early warning notifications when students show signs of academic difficulty, disengagement, or risk of dropout. Alert rules evaluate GPA thresholds, attendance patterns, assignment completion rates, and engagement metrics. Each alert is routed to the appropriate advisor or support staff with recommended interventions based on the alert type and student context.",tags:["Case"],connections:[{planet:"enrollment",desc:"Enrollment data triggers academic alerts"}]},
    {id:"career-development",name:"Career Development",icon:"\u{1F680}",desc:"Helps students explore career paths, set professional goals, and build career readiness through structured development activities. Career planning tools connect academic programs to potential career outcomes, and competency gap analysis shows students which skills they need to develop. Integration with alumni career data provides real-world examples of where graduates have found success.",tags:["PersonCompetency","PersonAffinity"],connections:[{planet:"alumni",desc:"Alumni career data informs current student planning"}]}
  ],
  dataFlow:["Student's competencies, traits, and affinities are assessed and recorded","Advisor is assigned based on program, year, and caseload","Early alert system monitors academic performance and engagement","Alerts trigger interventions and advising sessions","Career development planning guides students toward post-graduation goals"],
  connections:[{planet:"academics",desc:"Learning objectives tie to competency tracking"},{planet:"enrollment",desc:"Course performance feeds success interventions"},{planet:"records",desc:"Success metrics stored on person records"},{planet:"mentoring",desc:"Mentoring outcomes feed into success tracking"},{planet:"appointments",desc:"Advising appointments support interventions"},{planet:"agentforce",desc:"AI advising agent surfaces at-risk students"}]
},

financials: {
  packages: ['educationcloud'],
  name: "Student Financials",
  icon: "\u{1F4B0}",
  color: "#f59e0b",
  description: "Manages tuition, fees, financial aid, and student account balances through the Salesforce pricing and order engine adapted for higher education. Student Financials uses Products and Price Books to model fee structures, Academic Orders to generate student charges, and pricing rules to handle complex scenarios like in-state versus out-of-state tuition, lab fees, and meal plan charges.",
  components: [
    {id:"fee-management",name:"Fee Management",icon:"\u{1F4B5}",desc:"Defines the institution's fee structure using Salesforce Products. Each fee type, such as tuition per credit hour, technology fees, lab fees, and meal plans, is represented as a product record with attributes that drive pricing rules. Fee templates support variations based on student attributes like residency status, program level, and enrollment intensity.",tags:["Product2"],connections:[{planet:"academics",desc:"Course and program structure determines applicable fees"}]},
    {id:"price-books",name:"Price Books & Schedules",icon:"\u{1F4D5}",desc:"Establishes term-specific pricing through Salesforce Price Books. Each academic term has an associated price book that contains fee amounts effective for that period. Price book entries link products to their monetary values, supporting multiple pricing tiers for different student populations. Fee schedule automation generates price books for future terms based on approved rate increase percentages.",tags:["Pricebook2","PricebookEntry"],connections:[]},
    {id:"academic-orders",name:"Academic Orders",icon:"\u{1F6D2}",desc:"Generates student financial charges by creating orders populated with fee products. Academic order creation uses invocable actions that evaluate a student's enrollment, attributes, and applicable fee rules to build a complete charge set for the term. Each order captures the student, term, total amount, and individual line items for every fee assessed.",tags:["AcademicOrder","OrderProduct"],connections:[{planet:"enrollment",desc:"Course registration triggers order generation"}]},
    {id:"payment-processing",name:"Payment Processing",icon:"\u{1F4B3}",desc:"Tracks payments received, payment plans, and outstanding balances on student accounts. Payment records link to academic orders and capture payment method, date, amount, and status. Installment plans allow students to spread tuition payments across the term. Balance calculations aggregate charges and payments to show real-time account standing.",tags:["AcademicOrder"],connections:[{planet:"enrollment",desc:"Financial holds can block registration"}]},
    {id:"financial-aid",name:"Financial Aid",icon:"\u{1F381}",desc:"Manages scholarship, grant, and aid award packaging for eligible students. Aid awards specify the amount, type, term applicability, and disbursement schedule. Awards interact with the pricing engine to calculate net cost to the student after aid is applied. Financial need analysis integrates with institutional and federal aid determination processes.",tags:["AcademicOrder","OrderProduct"],connections:[{planet:"admissions",desc:"Financial aid packaging tied to admission offers"}]}
  ],
  dataFlow:["Institution defines fee products with pricing attributes","Price books establish term-specific fee amounts","Student registers for courses, triggering order generation","Pricing rules evaluate student attributes to calculate charges","Financial aid is applied and payment plans are created","Student account balance is updated with net amount due"],
  connections:[{planet:"admissions",desc:"Application fees and financial aid packaging"},{planet:"enrollment",desc:"Registration triggers tuition charges"},{planet:"academics",desc:"Program and course structure drives fee schedules"},{planet:"records",desc:"Financial accounts linked to person records"},{planet:"alumni",desc:"Scholarship funds connect to advancement"},{planet:"agentforce",desc:"Financial aid agent answers billing questions"},{planet:"experience",desc:"Student financial self-service portal"},{planet:"analytics",desc:"Financial health dashboards"}]
},

mentoring: {
  packages: ['educationcloud'],
  name: "Mentoring",
  icon: "\u{1F91D}",
  color: "#f472b6",
  description: "Manages structured mentoring programs that pair students with mentors for academic guidance, career coaching, and personal development. Mentoring uses profile-based matching enhanced by AI to find optimal mentor-mentee pairings based on skills, interests, academic background, and career goals. Benefit assignment workflows track the specific support each mentee receives throughout the mentoring relationship.",
  components: [
    {id:"program-design",name:"Program Design",icon:"\u{1F4CB}",desc:"Defines mentoring programs with goals, eligibility criteria, duration, and available benefits. Each program specifies the type of mentoring offered, such as academic tutoring, career coaching, peer mentoring, or alumni guidance. Program administrators configure matching criteria weights that determine how profiles are compared during the pairing process.",tags:["MentoringProgram"],connections:[]},
    {id:"mentor-profiles",name:"Mentor & Mentee Profiles",icon:"\u{1F464}",desc:"Captures detailed profiles for both mentors and mentees including skills, experience areas, availability, communication preferences, and goals. Profile fields are configurable per program, allowing different programs to collect different matching-relevant information. Profile completion tracking encourages participants to provide enough information for effective matching.",tags:["MentoringProfile"],connections:[{planet:"records",desc:"Profiles reference person account records"}]},
    {id:"mentor-matching",name:"AI-Powered Matching",icon:"\u{1F916}",desc:"Uses Einstein comparison algorithms to analyze mentor and mentee profiles and recommend optimal pairings. The matching engine evaluates profile field similarity scores, weighted by program-specific criteria, to generate ranked match suggestions. Program administrators review suggested matches and can accept, reject, or manually override recommendations before finalizing pairings.",tags:["MentoringProfile"],connections:[]},
    {id:"benefit-assignment",name:"Benefit Assignment & Tracking",icon:"\u{1F4E6}",desc:"Assigns and tracks the specific benefits a mentee receives from their mentoring relationship. Benefits can include tutoring sessions, career advice meetings, networking introductions, skill workshops, and resource referrals. Each benefit assignment records the type, frequency, dates, and outcomes, creating a measurable record of the mentoring relationship's impact.",tags:["MentoringBenefit","MentoringBenefitAssignment"],connections:[{planet:"success",desc:"Mentoring outcomes feed student success metrics"}]}
  ],
  dataFlow:["Program administrator defines mentoring program and benefits","Mentors and mentees create profiles with matching-relevant information","AI matching engine compares profiles and suggests optimal pairings","Administrator reviews and finalizes mentor-mentee assignments","Benefits are assigned and progress is tracked throughout the relationship"],
  connections:[{planet:"records",desc:"Mentor/mentee profiles linked to person records"},{planet:"success",desc:"Mentoring outcomes tracked as success metrics"},{planet:"appointments",desc:"Mentoring sessions scheduled as appointments"}]
},

alumni: {
  packages: ['educationcloud'],
  name: "Alumni & Advancement",
  icon: "\u{1F3C5}",
  color: "#ec4899",
  description: "Engages alumni through lifetime relationship management, gift tracking, pledge fulfillment, and volunteer coordination. Alumni & Advancement connects giving data to institutional advancement goals, provides donor stewardship tools, and tracks the impact of fundraising campaigns. The alumni engagement lifecycle extends the student record with post-graduation career outcomes, event participation, and philanthropic activity.",
  components: [
    {id:"alumni-engagement",name:"Alumni Engagement",icon:"\u{1F465}",desc:"Tracks ongoing relationships with graduates through event participation, communication interactions, volunteer activities, and career updates. Engagement scoring aggregates multiple interaction types into a single metric that identifies highly engaged alumni and those at risk of disengagement. Segmentation tools group alumni by graduation year, program, geographic region, and engagement level for targeted outreach.",tags:["Account"],connections:[{planet:"records",desc:"Alumni are former students with person records"},{planet:"experience",desc:"Alumni portal for community engagement"}]},
    {id:"gift-management",name:"Gift Management",icon:"\u{1F381}",desc:"Records and processes charitable gifts including cash, securities, in-kind donations, and matching gifts. Each gift transaction captures the donor, amount, designation, payment method, and acknowledgment status. Gift processing workflows handle receipt generation, tax acknowledgment letters, and fund allocation according to donor intent.",tags:["GiftTransaction"],connections:[{planet:"financials",desc:"Gift funds connect to institutional finance"}]},
    {id:"gift-commitments",name:"Pledges & Commitments",icon:"\u{1F4DD}",desc:"Manages multi-year pledges and recurring giving commitments where donors commit to future gifts over a defined period. Commitment records track the total pledge amount, payment schedule, amount received to date, and outstanding balance. Pledge reminder workflows notify donors of upcoming scheduled payments and generate reports on pledge fulfillment rates.",tags:["GiftCommitment"],connections:[]},
    {id:"volunteering",name:"Volunteer Management",icon:"\u{270B}",desc:"Coordinates alumni volunteer activities including mentoring current students, serving on advisory boards, participating in career panels, and supporting campus events. Volunteer records capture activity type, hours contributed, and impact metrics. Volunteer recognition programs acknowledge significant contributions and encourage continued participation.",tags:["VolunteerActivity"],connections:[{planet:"mentoring",desc:"Alumni volunteers serve as mentors"}]},
    {id:"fundraising",name:"Fundraising Campaigns",icon:"\u{1F4C8}",desc:"Plans and executes fundraising campaigns with goals, timelines, prospect assignments, and progress tracking. Campaign records link to gift transactions and commitments to measure results against targets. Major gift officers manage prospect portfolios with planned solicitation strategies and cultivation activities.",tags:["Campaign"],connections:[{planet:"analytics",desc:"Giving analytics and advancement dashboards"}]}
  ],
  dataFlow:["Graduate transitions to alumni status on person record","Alumni engagement activities are tracked and scored","Fundraising campaigns target segmented alumni populations","Gifts and pledges are recorded and acknowledged","Volunteer activities are coordinated and recognized"],
  connections:[{planet:"records",desc:"Alumni status tracked on person records"},{planet:"financials",desc:"Gift funds connect to institutional finance"},{planet:"agentforce",desc:"Alumni engagement agent manages outreach"},{planet:"experience",desc:"Alumni portal for giving and volunteering"},{planet:"analytics",desc:"Advancement dashboards and giving reports"}]
},

appointments: {
  packages: ['educationcloud'],
  name: "Appointments",
  icon: "\u{1F4C5}",
  color: "#14b8a6",
  description: "Provides centralized self-service appointment scheduling for advising, tutoring, financial aid counseling, and administrative meetings. Appointments manages staff availability calendars, walk-in waitlists, virtual meeting links, and appointment follow-up workflows. Students can book appointments through the portal based on department, topic, and available time slots.",
  components: [
    {id:"appointment-scheduling",name:"Appointment Scheduling",icon:"\u{1F4C5}",desc:"Enables students to book appointments with staff members based on department, service type, and available time slots. The scheduling interface shows real-time availability and supports multiple appointment durations. Confirmation notifications include meeting details, preparation instructions, and calendar invitations. Rescheduling and cancellation workflows handle changes while maintaining audit trails.",tags:["ServiceAppointment"],connections:[{planet:"enrollment",desc:"Advising appointments precede course registration"},{planet:"success",desc:"Advising sessions support student success"}]},
    {id:"staff-availability",name:"Staff Availability",icon:"\u{1F464}",desc:"Manages staff calendars, service territories, and availability windows for appointment scheduling. Each staff member is configured as a service resource with skills, working hours, and service territory assignments. Capacity settings control how many concurrent appointments each staff member can handle, and blocked time prevents scheduling during meetings or preparation periods.",tags:["ServiceResource","ServiceTerritory"],connections:[]},
    {id:"waitlist-management",name:"Waitlist & Walk-ins",icon:"\u{23F3}",desc:"Supports walk-in appointment flows with waitlist management and estimated wait times. Students can join a waitlist through the portal or by scanning a QR code at a physical location. The waitlist displays current position, estimated wait time, and staff member assignment. Notifications alert students when their turn approaches.",tags:["ServiceAppointment"],connections:[]},
    {id:"virtual-appointments",name:"Virtual Appointments",icon:"\u{1F4F9}",desc:"Extends appointment scheduling with video conferencing integration for remote advising, tutoring, and counseling sessions. Virtual appointments automatically generate meeting links and embed them in confirmation notifications. Multi-channel support allows students to connect via video, phone, or chat based on the appointment type and student preference.",tags:["ServiceAppointment"],connections:[{planet:"mentoring",desc:"Mentoring sessions use appointment scheduling"}]}
  ],
  dataFlow:["Staff configures availability and service territories","Student browses available slots by department and topic","Appointment is booked with confirmation and calendar invite","Walk-in students join the waitlist with estimated wait time","Virtual meeting link is generated for remote appointments"],
  connections:[{planet:"enrollment",desc:"Advising required before registration"},{planet:"records",desc:"Appointments reference student person records"},{planet:"success",desc:"Advising appointments support student success"},{planet:"mentoring",desc:"Mentoring sessions use appointment scheduling"}]
},

analytics: {
  packages: ['educationcloud'],
  name: "Education Analytics",
  icon: "\u{1F4CA}",
  color: "#f97316",
  description: "Delivers institutional insights through CRM Analytics dashboards covering recruitment yield, enrollment trends, retention rates, student success metrics, and financial health. Education Analytics provides pre-built dashboard templates for directors, recruiters, admissions officers, and advisors, each tailored to their decision-making needs. Custom report building enables institutions to create ad-hoc analyses specific to their reporting requirements.",
  components: [
    {id:"director-insights",name:"Director Insights",icon:"\u{1F3E2}",desc:"A multi-page dashboard providing institutional leadership with a comprehensive view of key performance indicators across recruitment, enrollment, retention, and graduation outcomes. The overview page surfaces year-over-year trends and highlights metrics that deviate significantly from targets. Drill-down pages let directors explore specific areas in detail.",tags:[],connections:[]},
    {id:"recruitment-analytics",name:"Recruitment Analytics",icon:"\u{1F4C8}",desc:"Tracks recruitment funnel metrics including inquiry volume, event attendance, application submission rates, and yield percentages by channel, territory, and counselor. Conversion rate analysis identifies which recruitment activities produce the highest-quality applicants. Trend comparisons across recruitment cycles reveal shifts in prospect behavior and channel effectiveness.",tags:[],connections:[{planet:"recruitment",desc:"Recruitment funnel data feeds analytics"}]},
    {id:"student-success-metrics",name:"Student Success Metrics",icon:"\u{1F3C6}",desc:"Monitors retention, persistence, GPA distribution, credit accumulation, and graduation rates across student populations. Cohort analysis compares outcomes for different student groups, revealing disparities that inform equity-focused interventions. At-risk indicators aggregate multiple signals into early warning visualizations.",tags:[],connections:[{planet:"success",desc:"Success tracking data powers analytics"}]},
    {id:"financial-analytics",name:"Financial Analytics",icon:"\u{1F4B0}",desc:"Provides visibility into tuition revenue, financial aid distribution, receivables aging, and payment plan utilization. Revenue forecasting models project future enrollment-driven revenue based on admissions pipeline data. Aid effectiveness analysis shows how different aid packaging strategies affect enrollment yield and net tuition revenue.",tags:[],connections:[{planet:"financials",desc:"Financial data feeds revenue dashboards"}]}
  ],
  dataFlow:["Data from recruitment, enrollment, success, and financial systems flows into analytics","Pre-built dashboards aggregate metrics into role-specific views","Directors review institutional KPIs and trend indicators","Department heads drill into program-level and cohort-level detail","Custom reports address ad-hoc institutional research questions"],
  connections:[{planet:"recruitment",desc:"Recruitment funnel dashboards"},{planet:"financials",desc:"Revenue and financial aid analytics"},{planet:"alumni",desc:"Advancement and giving dashboards"},{planet:"agentforce",desc:"Agent performance monitoring"}]
},

agentforce: {
  packages: ['educationcloud'],
  name: "Agentforce",
  icon: "\u{1F916}",
  color: "#a855f7",
  description: "Deploys AI-powered agents across the student lifecycle to automate communication, answer questions, and surface actionable insights. Agentforce for Education Cloud includes specialized agents for recruitment outreach, admissions Q&A, academic advising, financial aid guidance, and alumni engagement. Each agent is configured with education-specific topics, guardrails, and institutional knowledge.",
  components: [
    {id:"recruitment-agent",name:"Recruitment Agent",icon:"\u{1F4E3}",desc:"Automates personalized outreach to prospective students through email, SMS, and chat channels. The recruitment agent answers questions about programs, campus life, and application requirements using institutional knowledge bases. It identifies high-intent prospects based on interaction patterns and escalates them to human counselors for personal follow-up.",tags:[],connections:[{planet:"recruitment",desc:"Automates recruitment outreach sequences"}]},
    {id:"admissions-agent",name:"Admissions Agent",icon:"\u{1F4CB}",desc:"Provides real-time application status updates and answers common admissions questions through conversational AI. The agent handles inquiries about document requirements, decision timelines, and next steps after admission. It integrates with the application data model to provide personalized, context-aware responses.",tags:[],connections:[{planet:"admissions",desc:"Answers applicant questions about their application"}]},
    {id:"success-agent",name:"Student Success Agent",icon:"\u{1F31F}",desc:"Assists students with academic planning, course selection, and career exploration through personalized conversations. The success agent can access a student's enrollment history, degree requirements, and competency records to provide context-aware guidance. It recommends courses based on remaining requirements and warns about prerequisite gaps.",tags:[],connections:[{planet:"success",desc:"AI advising surfaces at-risk students"}]},
    {id:"financials-agent",name:"Student Financials Agent",icon:"\u{1F4B0}",desc:"Answers questions about account balances, fee breakdowns, payment due dates, and financial aid status. The financials agent provides self-service resolution for common billing inquiries that would otherwise require staff assistance. It can explain how charges were calculated and direct students to appropriate resources.",tags:[],connections:[{planet:"financials",desc:"Handles billing and aid inquiries"}]},
    {id:"alumni-agent",name:"Alumni Agent",icon:"\u{1F3C5}",desc:"Engages alumni through personalized communication about giving opportunities, events, and volunteer activities. The alumni agent can provide gift history summaries, answer questions about tax receipts, and facilitate event registration. It identifies engagement patterns that suggest readiness for increased giving or volunteer involvement.",tags:[],connections:[{planet:"alumni",desc:"Manages alumni outreach and engagement"}]}
  ],
  dataFlow:["Agent is configured with education-specific topics and guardrails","Student or prospect initiates conversation through portal or messaging","Agent accesses relevant records to provide personalized responses","Complex inquiries are escalated to human staff with full context","Agent performance metrics feed into analytics dashboards"],
  connections:[{planet:"recruitment",desc:"Recruitment outreach automation"},{planet:"admissions",desc:"Application status Q&A"},{planet:"success",desc:"At-risk student identification"},{planet:"financials",desc:"Financial aid guidance"},{planet:"alumni",desc:"Alumni engagement automation"},{planet:"analytics",desc:"Agent usage metrics and dashboards"}]
},

experience: {
  packages: ['educationcloud'],
  name: "Experience Cloud",
  icon: "\u{1F310}",
  color: "#64748b",
  description: "Powers learner-facing self-service portals for application tracking, course registration, financial account management, and alumni community engagement. Experience Cloud provides pre-built portal components designed for higher education workflows, with responsive designs that work across desktop and mobile devices. Permission-based content visibility ensures students, applicants, and alumni each see only the information relevant to their role.",
  components: [
    {id:"student-portal",name:"Student Portal",icon:"\u{1F393}",desc:"A self-service hub where enrolled students access their academic records, register for courses, view grades, and manage their personal information. The portal surfaces relevant alerts, upcoming deadlines, and advising recommendations in a personalized dashboard. Quick actions let students update contact information, request transcripts, and submit service requests.",tags:[],connections:[{planet:"enrollment",desc:"Course registration through the portal"},{planet:"financials",desc:"Financial account access and payments"}]},
    {id:"applicant-portal",name:"Applicant Portal",icon:"\u{1F4CB}",desc:"Provides prospective and active applicants with a dedicated workspace for managing their application. The portal shows application status, document checklist completion, upcoming deadlines, and decision notifications. Applicants can upload documents, complete supplemental forms, and communicate with admissions staff through a secure messaging interface.",tags:[],connections:[{planet:"admissions",desc:"Application tracking and document submission"}]},
    {id:"alumni-portal",name:"Alumni Portal",icon:"\u{1F3C5}",desc:"An online community for graduates to stay connected with their institution, update career information, explore giving opportunities, and register for alumni events. The portal features a directory of fellow alumni, class notes, and volunteer opportunity listings. Integration with giving systems allows online donations and pledge management.",tags:[],connections:[{planet:"alumni",desc:"Alumni community and giving portal"}]},
    {id:"mobile-experience",name:"Mobile Experience",icon:"\u{1F4F1}",desc:"Responsive design ensures all portal functionality works seamlessly across smartphones and tablets. Mobile-optimized navigation, touch-friendly form inputs, and push notification support provide a native-like experience through the mobile browser. Key actions like appointment check-in, document photo upload, and quick balance views are designed for on-the-go convenience.",tags:[],connections:[]}
  ],
  dataFlow:["Portal is configured with role-based page layouts and permissions","Student, applicant, or alumni authenticates and accesses personalized dashboard","Self-service actions trigger backend processes in Education Cloud","Status updates and notifications are pushed back to the portal","Mobile-responsive design ensures access across all devices"],
  connections:[{planet:"recruitment",desc:"Prospect inquiry and event portal"},{planet:"admissions",desc:"Application tracking portal"},{planet:"financials",desc:"Financial self-service portal"},{planet:"alumni",desc:"Alumni community portal"}]
},

data360: {
  packages: ['educationcloud'],
  name: "Data 360",
  icon: "\u{1F5C3}",
  color: "#06b6d4",
  description: "Consolidates student data from disparate legacy systems into a unified, deduplicated view using Salesforce Data 360 capabilities. Data 360 handles identity resolution across multiple source systems, standardizes data formats, and creates unified individual records that eliminate duplicate student entries. This is especially critical for institutions migrating from legacy student information systems where the same student may exist in multiple databases.",
  components: [
    {id:"data-consolidation",name:"Data Consolidation",icon:"\u{1F4E5}",desc:"Ingests student data from legacy student information systems, admissions platforms, and external databases into Education Cloud. Data streams define the source system, extraction schedule, and field mappings that transform external data into the Education Cloud data model. Incremental loading processes only new or changed records, minimizing processing time for large institutional datasets.",tags:["DataStream"],connections:[]},
    {id:"identity-resolution",name:"Identity Resolution",icon:"\u{1F50D}",desc:"Detects and resolves duplicate student records across source systems using configurable matching rules. Match rules evaluate combinations of name, date of birth, email, student ID, and other identifying fields to find potential duplicates. Confidence scoring ranks match quality, and resolution workflows present potential duplicates to staff for review and merge decisions.",tags:["IdentityResolutionRuleset","MatchRule"],connections:[{planet:"records",desc:"Resolved identities create unified person records"}]},
    {id:"unified-records",name:"Unified Records",icon:"\u{1F464}",desc:"Creates a single, authoritative record for each individual by merging the best data from multiple sources. Unified individual records apply survivorship rules that determine which source provides the most accurate value for each field. The unified view spans the complete student lifecycle from prospect through alumni.",tags:["UnifiedIndividual"],connections:[{planet:"records",desc:"Unified records feed into person accounts"}]},
    {id:"data-mapping",name:"Data Mapping & Standards",icon:"\u{1F5FA}",desc:"Establishes field-level mappings between external source system schemas and the Education Cloud data model. Mapping rules handle data type conversions, value translations, and validation logic that catches data quality issues during import. Standardization rules normalize formats for addresses, phone numbers, and names across source systems.",tags:["DataStream"],connections:[]}
  ],
  dataFlow:["Source systems are connected via data streams with extraction schedules","Raw data is mapped and transformed to the Education Cloud schema","Identity resolution detects duplicates across source systems","Matched records are merged into unified individual records","Unified data feeds all Education Cloud domains through person accounts"],
  connections:[{planet:"records",desc:"Identity resolution unifies student person records"}]
}

};
