// ══════════════════════════════════════════════════════════════
//  Education Cloud Entities — Objects & Custom Metadata
//  Education Cloud is a native Salesforce product (no managed packages)
// ══════════════════════════════════════════════════════════════

export default {

  "recruitment": {
    "objects": [
      {
        "name": "Lead",
        "type": "standard",
        "domain": "recruitment",
        "description": "Represents a prospective student who has expressed interest in the institution but has not yet applied. Lead records capture inquiry source, academic interests, and engagement history. Leads convert to person account records when the prospect enters the formal application process.",
        "fields": [
          { "name": "FirstName", "type": "Text", "description": "Prospect's first name" },
          { "name": "LastName", "type": "Text", "description": "Prospect's last name" },
          { "name": "Email", "type": "Email", "description": "Primary email address for recruitment communications" },
          { "name": "LeadSource", "type": "Picklist", "description": "Channel through which the prospect first engaged (web inquiry, campus event, referral)" },
          { "name": "Status", "type": "Picklist", "description": "Current stage in the recruitment funnel (new, contacted, qualified, converted)" },
          { "name": "Company", "type": "Text", "description": "High school or current institution name" }
        ],
        "relationships": [
          { "target": "Campaign", "type": "lookup", "description": "Leads are associated with recruitment campaigns through campaign members" }
        ]
      },
      {
        "name": "ContactProfile",
        "type": "standard",
        "domain": "recruitment",
        "description": "Stores additional demographic and biographical information about a prospect or student beyond the core person account. Contact profiles capture citizenship status, residency classification, ethnicity, and other attributes used for admissions evaluation and institutional reporting compliance.",
        "fields": [
          { "name": "CitizenshipStatus", "type": "Picklist", "description": "Citizenship classification (citizen, permanent resident, international)" },
          { "name": "ResidencyStatus", "type": "Picklist", "description": "In-state or out-of-state residency for tuition classification" },
          { "name": "PreferredName", "type": "Text", "description": "Name the student prefers to be called" },
          { "name": "ContactId", "type": "Lookup", "description": "Reference to the person account contact record" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Each contact profile belongs to a person account" }
        ]
      },
      {
        "name": "Campaign",
        "type": "standard",
        "domain": "recruitment",
        "description": "Represents a recruitment campaign, event, or outreach initiative used to attract prospective students. Campaigns track open houses, email sequences, virtual events, and advertising efforts. Campaign metrics measure reach, engagement, and conversion rates for each recruitment activity.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Campaign name" },
          { "name": "Type", "type": "Picklist", "description": "Campaign type (event, email, social media, direct mail)" },
          { "name": "Status", "type": "Picklist", "description": "Campaign lifecycle status (planned, active, completed)" },
          { "name": "StartDate", "type": "Date", "description": "Campaign start date" },
          { "name": "EndDate", "type": "Date", "description": "Campaign end date" },
          { "name": "NumberOfLeads", "type": "Number", "description": "Total leads generated by this campaign" }
        ],
        "relationships": [
          { "target": "CampaignMember", "type": "parent", "description": "Campaigns contain campaign member records for each participant" }
        ]
      },
      {
        "name": "CampaignMember",
        "type": "standard",
        "domain": "recruitment",
        "description": "Links a prospect or student to a specific campaign, tracking their participation and response status. Campaign member records capture attendance, response dates, and progression through campaign-specific stages to measure the effectiveness of each recruitment touchpoint.",
        "fields": [
          { "name": "Status", "type": "Picklist", "description": "Response status within the campaign (sent, responded, attended, converted)" },
          { "name": "CampaignId", "type": "Lookup", "description": "Reference to the parent campaign" },
          { "name": "LeadId", "type": "Lookup", "description": "Reference to the lead record if the member is a prospect" },
          { "name": "ContactId", "type": "Lookup", "description": "Reference to the contact record if the member is an existing student" }
        ],
        "relationships": [
          { "target": "Campaign", "type": "child", "description": "Each member belongs to a campaign" },
          { "target": "Lead", "type": "lookup", "description": "Member may reference a lead record" }
        ]
      }
    ],
    "metadata": [
      {
        "type": "RecruitmentSetting__mdt",
        "name": "Recruitment Settings",
        "fields": { "LeadScoringEnabled__c": "Checkbox", "DefaultLeadSource__c": "Text", "AutoAssignTerritory__c": "Checkbox" },
        "description": "Configures recruitment behavior including lead scoring activation, default lead sources for web inquiries, and automatic territory assignment rules for new prospects."
      }
    ]
  },

  "admissions": {
    "objects": [
      {
        "name": "IndividualApplication",
        "type": "standard",
        "domain": "admissions",
        "description": "The primary application record that tracks a prospective student's application to a specific program and term. Each application captures the program of interest, application type, submission date, and current processing status. Applications support multiple review rounds and configurable decision workflows.",
        "fields": [
          { "name": "Name", "type": "AutoNumber", "description": "System-generated application identifier" },
          { "name": "ApplicationStatus", "type": "Picklist", "description": "Current status (draft, submitted, under review, decision rendered)" },
          { "name": "ApplicationType", "type": "Picklist", "description": "Type of application (freshman, transfer, graduate, international)" },
          { "name": "SubmittedDate", "type": "DateTime", "description": "Timestamp when the applicant submitted the application" },
          { "name": "DecisionStatus", "type": "Picklist", "description": "Admission decision (accepted, denied, waitlisted, conditional)" },
          { "name": "ProgramId", "type": "Lookup", "description": "The academic program the applicant is applying to" }
        ],
        "relationships": [
          { "target": "Applicant", "type": "parent", "description": "Each application has an applicant record linking to the person" },
          { "target": "Program", "type": "lookup", "description": "Applications reference the target academic program" },
          { "target": "DocumentChecklistItem", "type": "parent", "description": "Applications have required document checklist items" }
        ]
      },
      {
        "name": "Applicant",
        "type": "standard",
        "domain": "admissions",
        "description": "Links an individual application to the person account that represents the applying student. The applicant record serves as the junction between the application lifecycle and the student identity, enabling a single person to have multiple applications across different programs or terms.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Applicant display name" },
          { "name": "AccountId", "type": "Lookup", "description": "Reference to the person account" },
          { "name": "IndividualApplicationId", "type": "Lookup", "description": "Reference to the application record" },
          { "name": "ApplicantType", "type": "Picklist", "description": "Applicant classification (first-time, transfer, returning)" }
        ],
        "relationships": [
          { "target": "Account", "type": "lookup", "description": "Each applicant references a person account" },
          { "target": "IndividualApplication", "type": "child", "description": "Each applicant is linked to an application" }
        ]
      },
      {
        "name": "DocumentChecklistItem",
        "type": "standard",
        "domain": "admissions",
        "description": "Tracks a required or optional document within an application's submission checklist. Each item represents a specific document type such as transcripts, test scores, essays, or recommendation letters. Status tracking shows whether each document has been received, is under review, or is still outstanding.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Document type name (transcript, essay, recommendation letter)" },
          { "name": "Status", "type": "Picklist", "description": "Document status (required, received, verified, waived)" },
          { "name": "IsRequired", "type": "Checkbox", "description": "Whether this document is mandatory for application completion" },
          { "name": "ReceivedDate", "type": "Date", "description": "Date the document was received" },
          { "name": "ParentRecordId", "type": "Lookup", "description": "Reference to the parent application record" }
        ],
        "relationships": [
          { "target": "IndividualApplication", "type": "child", "description": "Checklist items belong to an application" }
        ]
      },
      {
        "name": "PreliminaryApplication",
        "type": "standard",
        "domain": "admissions",
        "description": "A lightweight application form that captures early interest from prospective students before the formal application window opens. Preliminary applications collect basic demographic information, intended program, and term of entry to help institutions gauge demand and begin building relationships with prospects.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Applicant name" },
          { "name": "IntendedProgram", "type": "Text", "description": "Program the prospect is interested in" },
          { "name": "IntendedTerm", "type": "Text", "description": "Academic term of intended enrollment" },
          { "name": "Status", "type": "Picklist", "description": "Preliminary application status" },
          { "name": "AccountId", "type": "Lookup", "description": "Reference to the person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "lookup", "description": "Preliminary applications link to person accounts" },
          { "target": "Program", "type": "lookup", "description": "References the intended academic program" }
        ]
      }
    ],
    "metadata": [
      {
        "type": "AdmissionsSetting__mdt",
        "name": "Admissions Settings",
        "fields": { "ReviewWorkflowEnabled__c": "Checkbox", "AutoDecisionThreshold__c": "Number", "RequireDocumentVerification__c": "Checkbox" },
        "description": "Configures admissions processing behavior including review workflow activation, automatic decision score thresholds, and document verification requirements."
      }
    ]
  },

  "academics": {
    "objects": [
      {
        "name": "Program",
        "type": "standard",
        "domain": "academics",
        "description": "Defines a degree program, certificate, or academic pathway offered by the institution. Each program specifies credit requirements, GPA thresholds, and learning outcome expectations. Programs are organized under academic departments and serve as the target for student enrollment.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Program title (e.g., Bachelor of Science in Computer Science)" },
          { "name": "ProgramType", "type": "Picklist", "description": "Degree type (bachelor, master, doctoral, certificate)" },
          { "name": "TotalCreditsRequired", "type": "Number", "description": "Minimum credits needed for completion" },
          { "name": "MinimumGPA", "type": "Number", "description": "Minimum cumulative GPA required for good standing" },
          { "name": "DepartmentId", "type": "Lookup", "description": "Academic department that owns this program" },
          { "name": "IsActive", "type": "Checkbox", "description": "Whether the program is actively accepting enrollments" }
        ],
        "relationships": [
          { "target": "ProgramEnrollment", "type": "parent", "description": "Programs have enrolled students through program enrollment records" },
          { "target": "Course", "type": "parent", "description": "Programs define required and elective courses" }
        ]
      },
      {
        "name": "Course",
        "type": "standard",
        "domain": "academics",
        "description": "A permanent course definition in the institutional catalog, separate from its scheduled instances. Each course record captures the subject area, course number, credit value, description, and prerequisite requirements. Courses serve as templates from which term-specific course offerings are created.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Course title" },
          { "name": "CourseCode", "type": "Text", "description": "Subject area and course number (e.g., CS 101)" },
          { "name": "CreditValue", "type": "Number", "description": "Number of credits awarded upon completion" },
          { "name": "Description", "type": "LongTextArea", "description": "Course description for the catalog" },
          { "name": "Level", "type": "Picklist", "description": "Course level (introductory, intermediate, advanced, graduate)" }
        ],
        "relationships": [
          { "target": "CourseOffering", "type": "parent", "description": "Courses have multiple offerings across terms" },
          { "target": "Program", "type": "lookup", "description": "Courses belong to academic programs" }
        ]
      },
      {
        "name": "CourseOffering",
        "type": "standard",
        "domain": "academics",
        "description": "A specific instance of a course scheduled for a particular academic term with assigned instructors, meeting times, and enrollment capacity. Course offerings inherit core details from their parent course while adding term-specific scheduling information. Students register for course offerings, not courses directly.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Offering display name including section number" },
          { "name": "SectionNumber", "type": "Text", "description": "Section identifier within the term" },
          { "name": "Capacity", "type": "Number", "description": "Maximum enrollment capacity" },
          { "name": "DeliveryMode", "type": "Picklist", "description": "Instruction mode (in-person, online, hybrid)" },
          { "name": "CourseId", "type": "Lookup", "description": "Reference to the parent course definition" },
          { "name": "AcademicTermId", "type": "Lookup", "description": "The academic term this offering is scheduled in" }
        ],
        "relationships": [
          { "target": "Course", "type": "child", "description": "Each offering belongs to a course" },
          { "target": "AcademicTerm", "type": "lookup", "description": "Offerings are scheduled within academic terms" },
          { "target": "CourseOfferingParticipant", "type": "parent", "description": "Offerings have registered participants" }
        ]
      },
      {
        "name": "AcademicTerm",
        "type": "standard",
        "domain": "academics",
        "description": "Defines a period in the academic calendar during which courses are offered and academic activities occur. Terms establish the registration window, add/drop deadlines, instruction dates, and grade submission periods that structure the rhythm of the academic year.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Term name (e.g., Fall 2026, Spring 2027)" },
          { "name": "StartDate", "type": "Date", "description": "First day of the term" },
          { "name": "EndDate", "type": "Date", "description": "Last day of the term" },
          { "name": "RegistrationStartDate", "type": "Date", "description": "When course registration opens" },
          { "name": "RegistrationEndDate", "type": "Date", "description": "Registration deadline" },
          { "name": "Type", "type": "Picklist", "description": "Term type (fall, spring, summer, winter)" }
        ],
        "relationships": [
          { "target": "CourseOffering", "type": "parent", "description": "Terms contain course offerings" },
          { "target": "AcademicTimePeriod", "type": "parent", "description": "Terms can be subdivided into time periods" }
        ]
      },
      {
        "name": "AcademicTimePeriod",
        "type": "standard",
        "domain": "academics",
        "description": "A subdivision of an academic term for institutions that run multiple sessions within a single term. Time periods enable scheduling of mini-terms, intensive sessions, and summer sub-sessions while maintaining the parent term as the primary organizational unit for enrollment and reporting.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Time period name (e.g., Summer Session A)" },
          { "name": "StartDate", "type": "Date", "description": "Period start date" },
          { "name": "EndDate", "type": "Date", "description": "Period end date" },
          { "name": "AcademicTermId", "type": "Lookup", "description": "Parent academic term" }
        ],
        "relationships": [
          { "target": "AcademicTerm", "type": "child", "description": "Each time period belongs to an academic term" }
        ]
      },
      {
        "name": "LearningObjective",
        "type": "standard",
        "domain": "academics",
        "description": "A measurable learning outcome that describes what a student should know or be able to do upon completing a course or program. Objectives are aligned with accreditation standards and institutional assessment frameworks. They link to competency records for outcome-based education tracking.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Objective title" },
          { "name": "Description", "type": "LongTextArea", "description": "Detailed statement of what the student will achieve" },
          { "name": "AssessmentMethod", "type": "Picklist", "description": "How achievement is measured (exam, project, portfolio)" },
          { "name": "CourseId", "type": "Lookup", "description": "Course this objective belongs to" }
        ],
        "relationships": [
          { "target": "Course", "type": "child", "description": "Objectives are defined within courses" },
          { "target": "PersonCompetency", "type": "lookup", "description": "Objectives map to competency assessments" }
        ]
      },
      {
        "name": "TransferCredit",
        "type": "standard",
        "domain": "academics",
        "description": "Records credits earned at an external institution that have been evaluated and accepted for transfer. Each transfer credit captures the originating institution, original course, credit value, and the equivalent internal course. Transfer credits count toward degree requirements and appear on the student's academic record.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Transfer credit display name" },
          { "name": "OriginatingInstitution", "type": "Text", "description": "Name of the institution where credits were earned" },
          { "name": "OriginalCourseName", "type": "Text", "description": "Course title at the originating institution" },
          { "name": "CreditValue", "type": "Number", "description": "Number of credits transferred" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Transfer credits belong to a student" },
          { "target": "LearningEquivalency", "type": "lookup", "description": "Transfer credits reference equivalency rules for mapping" }
        ]
      },
      {
        "name": "LearningEquivalency",
        "type": "standard",
        "domain": "academics",
        "description": "Defines how courses from external institutions map to equivalent courses in the institutional catalog. Equivalency rules specify the originating institution, external course, and the internal course it satisfies, streamlining the transfer credit evaluation process for commonly received transfer courses.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Equivalency rule name" },
          { "name": "ExternalCourseName", "type": "Text", "description": "Course name at the external institution" },
          { "name": "ExternalInstitution", "type": "Text", "description": "Institution the equivalency applies to" },
          { "name": "InternalCourseId", "type": "Lookup", "description": "The equivalent internal course" },
          { "name": "CreditValue", "type": "Number", "description": "Credits awarded for the equivalency" }
        ],
        "relationships": [
          { "target": "Course", "type": "lookup", "description": "Equivalencies map to internal course definitions" }
        ]
      }
    ]
  },

  "enrollment": {
    "objects": [
      {
        "name": "ProgramEnrollment",
        "type": "standard",
        "domain": "enrollment",
        "description": "Records a student's active participation in a degree program or certificate. Each enrollment tracks the program, start term, expected graduation, academic standing, and cumulative GPA. Enrollment status transitions capture the full lifecycle from admission through graduation or withdrawal.",
        "fields": [
          { "name": "Name", "type": "AutoNumber", "description": "System-generated enrollment identifier" },
          { "name": "EnrollmentStatus", "type": "Picklist", "description": "Current status (active, on hold, leave, withdrawn, graduated)" },
          { "name": "StartDate", "type": "Date", "description": "Enrollment start date" },
          { "name": "ExpectedGraduationDate", "type": "Date", "description": "Projected graduation date" },
          { "name": "CumulativeGPA", "type": "Number", "description": "Running cumulative grade point average" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" },
          { "name": "ProgramId", "type": "Lookup", "description": "Academic program the student is enrolled in" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Each enrollment belongs to a student" },
          { "target": "Program", "type": "lookup", "description": "Enrollment references the academic program" }
        ]
      },
      {
        "name": "CourseOfferingParticipant",
        "type": "standard",
        "domain": "enrollment",
        "description": "Tracks a student's registration in a specific course offering for a given term. Participant records capture the registration status, credit mode, and role (student, teaching assistant, auditor). This is the transactional record that links students to the courses they are taking.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Participant display name" },
          { "name": "ParticipantRole", "type": "Picklist", "description": "Role in the offering (student, TA, auditor)" },
          { "name": "RegistrationStatus", "type": "Picklist", "description": "Status (registered, waitlisted, dropped, completed)" },
          { "name": "CreditMode", "type": "Picklist", "description": "Credit type (credit, audit, pass-fail)" },
          { "name": "CourseOfferingId", "type": "Lookup", "description": "The course offering this participant is registered in" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "CourseOffering", "type": "child", "description": "Participants belong to a course offering" },
          { "target": "Account", "type": "lookup", "description": "Participants reference the student person account" }
        ]
      },
      {
        "name": "LearningAchievement",
        "type": "standard",
        "domain": "enrollment",
        "description": "Records a student's grade, credits earned, and academic milestone for a specific course offering. Achievement records are created when final grades are submitted and accumulate to build the student's academic transcript. Quality points and credit totals feed cumulative GPA calculations.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Achievement display name" },
          { "name": "GradeValue", "type": "Text", "description": "Letter grade or pass/fail designation" },
          { "name": "CreditsEarned", "type": "Number", "description": "Credits awarded for this achievement" },
          { "name": "CreditsAttempted", "type": "Number", "description": "Credits attempted (may differ for withdrawals)" },
          { "name": "QualityPoints", "type": "Number", "description": "Grade points used in GPA calculation" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Achievements belong to a student" },
          { "target": "CourseOffering", "type": "lookup", "description": "Achievements reference the completed course offering" }
        ]
      },
      {
        "name": "LearningPlan",
        "type": "standard",
        "domain": "enrollment",
        "description": "A personalized academic roadmap that sequences courses across terms toward degree completion. Learning plans consider prerequisite chains, course availability, and remaining requirements to create an optimized path. Plans are adjusted collaboratively between advisors and students as circumstances change.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Plan display name" },
          { "name": "Status", "type": "Picklist", "description": "Plan status (draft, active, completed)" },
          { "name": "TargetCompletionDate", "type": "Date", "description": "Projected completion date" },
          { "name": "TotalPlannedCredits", "type": "Number", "description": "Total credits mapped in the plan" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Learning plans belong to a student" },
          { "target": "ProgramEnrollment", "type": "lookup", "description": "Plans are tied to a specific program enrollment" }
        ]
      }
    ]
  },

  "records": {
    "objects": [
      {
        "name": "Account",
        "type": "standard",
        "domain": "records",
        "description": "The core person account record that serves as the unified student identity across all Education Cloud domains. Using Salesforce Person Accounts, the Account combines account and contact functionality into a single entity that stores the student's name, demographics, institutional identifiers, and lifecycle status.",
        "fields": [
          { "name": "FirstName", "type": "Text", "description": "Student's first name" },
          { "name": "LastName", "type": "Text", "description": "Student's last name" },
          { "name": "PersonBirthdate", "type": "Date", "description": "Date of birth" },
          { "name": "StudentId__c", "type": "Text", "description": "Institutional student identifier" },
          { "name": "PersonEmail", "type": "Email", "description": "Primary email address" },
          { "name": "RecordTypeId", "type": "Lookup", "description": "Person account record type" }
        ],
        "relationships": [
          { "target": "ProgramEnrollment", "type": "parent", "description": "Students have program enrollments" },
          { "target": "ContactRelationship", "type": "parent", "description": "Students have relationship records to family members" },
          { "target": "PersonEducation", "type": "parent", "description": "Students have education history records" }
        ]
      },
      {
        "name": "ContactPointAddress",
        "type": "standard",
        "domain": "records",
        "description": "Stores a physical or mailing address associated with a person account. Students can have multiple addresses with different usage types such as home, school, billing, and permanent. Effective dating supports address changes scheduled for future terms.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Address label (home, school, billing)" },
          { "name": "Street", "type": "TextArea", "description": "Street address lines" },
          { "name": "City", "type": "Text", "description": "City name" },
          { "name": "StateCode", "type": "Text", "description": "State or province" },
          { "name": "PostalCode", "type": "Text", "description": "ZIP or postal code" },
          { "name": "Country", "type": "Text", "description": "Country name" },
          { "name": "UsageType", "type": "Picklist", "description": "Address purpose (home, school, billing, permanent)" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Addresses belong to a person account" }
        ]
      },
      {
        "name": "ContactPointPhone",
        "type": "standard",
        "domain": "records",
        "description": "Stores a phone number associated with a person account with usage type designation. Multiple phone records support different contact scenarios like primary, mobile, home, and emergency numbers.",
        "fields": [
          { "name": "TelephoneNumber", "type": "Phone", "description": "Phone number" },
          { "name": "UsageType", "type": "Picklist", "description": "Phone usage type (mobile, home, work)" },
          { "name": "IsPrimary", "type": "Checkbox", "description": "Whether this is the primary phone number" },
          { "name": "ParentId", "type": "Lookup", "description": "Reference to the person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Phone records belong to a person account" }
        ]
      },
      {
        "name": "ContactPointEmail",
        "type": "standard",
        "domain": "records",
        "description": "Stores an email address associated with a person account with usage type and primary designation. Students typically have institutional and personal email addresses managed through contact point records.",
        "fields": [
          { "name": "EmailAddress", "type": "Email", "description": "Email address" },
          { "name": "UsageType", "type": "Picklist", "description": "Email usage type (personal, institutional, work)" },
          { "name": "IsPrimary", "type": "Checkbox", "description": "Whether this is the primary email" },
          { "name": "ParentId", "type": "Lookup", "description": "Reference to the person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Email records belong to a person account" }
        ]
      },
      {
        "name": "ContactRelationship",
        "type": "standard",
        "domain": "records",
        "description": "Defines a relationship between two person accounts such as parent-child, guardian, sibling, or spouse. Relationship records capture the type, primary contact designation, and communication permissions used for family notifications, emergency contacts, and household financial grouping.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Relationship display name" },
          { "name": "Type", "type": "Picklist", "description": "Relationship type (parent, guardian, sibling, spouse, emergency)" },
          { "name": "IsPrimaryContact", "type": "Checkbox", "description": "Whether this is the primary family contact" },
          { "name": "ContactId", "type": "Lookup", "description": "The student in the relationship" },
          { "name": "RelatedContactId", "type": "Lookup", "description": "The related person" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Relationships link two person accounts" }
        ]
      },
      {
        "name": "PersonEducation",
        "type": "standard",
        "domain": "records",
        "description": "Records a student's prior education at another institution, capturing the school name, dates attended, degree earned, GPA, and class rank. Education history records support admissions evaluation and transfer credit assessment by providing context about the student's academic background.",
        "fields": [
          { "name": "InstitutionName", "type": "Text", "description": "Name of the school or institution" },
          { "name": "DegreeEarned", "type": "Text", "description": "Degree or diploma earned" },
          { "name": "GPA", "type": "Number", "description": "Grade point average at the institution" },
          { "name": "StartDate", "type": "Date", "description": "Attendance start date" },
          { "name": "EndDate", "type": "Date", "description": "Attendance end date" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Education history belongs to a student" }
        ]
      },
      {
        "name": "PersonExamination",
        "type": "standard",
        "domain": "records",
        "description": "Records standardized test results including SAT, ACT, GRE, TOEFL, IELTS, and AP examinations. Each record captures the test name, date taken, individual section scores, and composite or total score. Examination records are used in admissions evaluation, placement, and credit-by-examination.",
        "fields": [
          { "name": "ExamName", "type": "Text", "description": "Name of the examination (SAT, ACT, GRE)" },
          { "name": "ExamDate", "type": "Date", "description": "Date the exam was taken" },
          { "name": "TotalScore", "type": "Number", "description": "Composite or total score" },
          { "name": "SectionScores", "type": "LongTextArea", "description": "Individual section scores" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Examination records belong to a student" }
        ]
      },
      {
        "name": "PersonLanguage",
        "type": "standard",
        "domain": "records",
        "description": "Records language proficiency information for a student including reading, writing, speaking, and listening skill levels. Language records support international student services, ESL placement, and institutional compliance reporting.",
        "fields": [
          { "name": "Language", "type": "Picklist", "description": "Language name" },
          { "name": "ProficiencyLevel", "type": "Picklist", "description": "Overall proficiency (beginner, intermediate, advanced, native)" },
          { "name": "IsPrimary", "type": "Checkbox", "description": "Whether this is the student's primary language" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Language records belong to a student" }
        ]
      },
      {
        "name": "PersonEmployment",
        "type": "standard",
        "domain": "records",
        "description": "Tracks a student's employment history including work-study positions, internships, and post-graduation jobs. Employment records capture the employer, job title, dates, and employment type. Post-graduation employment data feeds institutional career outcome reporting.",
        "fields": [
          { "name": "EmployerName", "type": "Text", "description": "Name of the employer" },
          { "name": "JobTitle", "type": "Text", "description": "Position title" },
          { "name": "StartDate", "type": "Date", "description": "Employment start date" },
          { "name": "EndDate", "type": "Date", "description": "Employment end date (null if current)" },
          { "name": "EmploymentType", "type": "Picklist", "description": "Type (full-time, part-time, internship, work-study)" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Employment records belong to a student" }
        ]
      }
    ]
  },

  "success": {
    "objects": [
      {
        "name": "PersonCompetency",
        "type": "standard",
        "domain": "success",
        "description": "Records a student's proficiency in a specific skill or competency area. Competency records capture the skill name, current proficiency level, assessment method, and evidence of achievement. Competencies link to learning objectives and are used for outcome-based education tracking.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Competency name" },
          { "name": "ProficiencyLevel", "type": "Picklist", "description": "Current proficiency (developing, proficient, advanced, expert)" },
          { "name": "AssessmentDate", "type": "Date", "description": "Date the competency was last assessed" },
          { "name": "AssessmentMethod", "type": "Picklist", "description": "How proficiency was measured (exam, project, observation)" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Competencies belong to a student" },
          { "target": "LearningObjective", "type": "lookup", "description": "Competencies map to learning objectives" }
        ]
      },
      {
        "name": "PersonTrait",
        "type": "standard",
        "domain": "success",
        "description": "Captures observable behavioral strengths and characteristics identified through assessments or advisor observations. Traits describe personal qualities like leadership, collaboration, analytical thinking, and creativity that inform personalized advising and opportunity matching.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Trait name" },
          { "name": "Category", "type": "Picklist", "description": "Trait category (academic, interpersonal, leadership)" },
          { "name": "Strength", "type": "Picklist", "description": "Strength level (emerging, developing, strong)" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Traits belong to a student" }
        ]
      },
      {
        "name": "PersonAffinity",
        "type": "standard",
        "domain": "success",
        "description": "Records a student's academic subject interests, career aspirations, and extracurricular preferences. Affinity data helps match students with mentoring opportunities, student organizations, research projects, and career pathways that align with their interests.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Affinity name" },
          { "name": "Type", "type": "Picklist", "description": "Affinity type (academic interest, career aspiration, extracurricular)" },
          { "name": "InterestLevel", "type": "Picklist", "description": "Degree of interest (casual, moderate, strong)" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Affinities belong to a student" }
        ]
      },
      {
        "name": "CareCoordinator",
        "type": "standard",
        "domain": "success",
        "description": "Assigns an advisor or support staff member to a student for academic guidance, mentoring coordination, or crisis support. Care coordinator records define the support role, assignment dates, and caseload management. Multiple coordinators can be assigned to a single student for different support areas.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Coordinator assignment name" },
          { "name": "Role", "type": "Picklist", "description": "Support role (academic advisor, career counselor, student affairs)" },
          { "name": "StartDate", "type": "Date", "description": "Assignment start date" },
          { "name": "EndDate", "type": "Date", "description": "Assignment end date (null if current)" },
          { "name": "AccountId", "type": "Lookup", "description": "Student being supported" },
          { "name": "CoordinatorId", "type": "Lookup", "description": "Staff member providing support" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Care coordinators are assigned to students" }
        ]
      },
      {
        "name": "CareRole",
        "type": "standard",
        "domain": "success",
        "description": "Defines the types of support roles available for care coordinator assignments. Care roles specify the scope of responsibility, required qualifications, and maximum caseload for each type of advisor or support staff position.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Role title" },
          { "name": "Description", "type": "TextArea", "description": "Role scope and responsibilities" },
          { "name": "MaxCaseload", "type": "Number", "description": "Maximum number of students per coordinator" },
          { "name": "IsActive", "type": "Checkbox", "description": "Whether this role is currently available for assignment" }
        ],
        "relationships": [
          { "target": "CareCoordinator", "type": "parent", "description": "Roles are assigned to care coordinator records" }
        ]
      },
      {
        "name": "Case",
        "type": "standard",
        "domain": "success",
        "description": "Used as an academic alert or support case when a student shows signs of difficulty. Cases can represent early warning alerts for low GPA, attendance issues, or engagement decline. Each case is routed to the appropriate advisor with recommended interventions.",
        "fields": [
          { "name": "Subject", "type": "Text", "description": "Alert or case subject" },
          { "name": "Status", "type": "Picklist", "description": "Case status (new, in progress, resolved, closed)" },
          { "name": "Priority", "type": "Picklist", "description": "Urgency level (low, medium, high, critical)" },
          { "name": "Type", "type": "Picklist", "description": "Case type (academic alert, conduct, financial hold, general)" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" },
          { "name": "Description", "type": "LongTextArea", "description": "Detailed description of the alert or issue" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Cases are filed for a student" }
        ]
      }
    ],
    "metadata": [
      {
        "type": "AlertThreshold__mdt",
        "name": "Alert Thresholds",
        "fields": { "MetricName__c": "Text", "WarningThreshold__c": "Number", "CriticalThreshold__c": "Number", "AutoCreateCase__c": "Checkbox" },
        "description": "Configures the thresholds at which academic alerts are triggered, such as minimum GPA levels, attendance rates, and assignment completion percentages that generate early warning cases."
      }
    ]
  },

  "financials": {
    "objects": [
      {
        "name": "Product2",
        "type": "standard",
        "domain": "financials",
        "description": "Represents a fee type in the institution's financial structure such as tuition per credit hour, technology fees, lab fees, or meal plans. Products define the fee attributes that drive pricing rules, supporting variations based on student residency, program level, and enrollment intensity.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Fee product name (e.g., In-State Tuition Per Credit)" },
          { "name": "ProductCode", "type": "Text", "description": "Unique fee code" },
          { "name": "Family", "type": "Picklist", "description": "Fee family (tuition, fees, housing, meal plans)" },
          { "name": "IsActive", "type": "Checkbox", "description": "Whether this fee is currently applicable" },
          { "name": "Description", "type": "TextArea", "description": "Fee description" }
        ],
        "relationships": [
          { "target": "PricebookEntry", "type": "parent", "description": "Products have price book entries for term-specific pricing" }
        ]
      },
      {
        "name": "Pricebook2",
        "type": "standard",
        "domain": "financials",
        "description": "A collection of fee amounts effective for a specific academic term or student population. Price books establish the monetary values for each fee product, enabling different pricing for in-state versus out-of-state students, undergraduate versus graduate programs, and term-over-term rate adjustments.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Price book name (e.g., Fall 2026 Undergraduate)" },
          { "name": "IsActive", "type": "Checkbox", "description": "Whether this price book is active" },
          { "name": "Description", "type": "TextArea", "description": "Price book description and applicability" }
        ],
        "relationships": [
          { "target": "PricebookEntry", "type": "parent", "description": "Price books contain price book entries" }
        ]
      },
      {
        "name": "PricebookEntry",
        "type": "standard",
        "domain": "financials",
        "description": "Links a fee product to a specific price book with the monetary amount for that combination. Each entry defines the unit price of a fee product within a particular pricing context, such as the per-credit tuition rate for in-state undergraduate students during the fall term.",
        "fields": [
          { "name": "UnitPrice", "type": "Currency", "description": "Fee amount" },
          { "name": "IsActive", "type": "Checkbox", "description": "Whether this entry is active" },
          { "name": "Product2Id", "type": "Lookup", "description": "Reference to the fee product" },
          { "name": "Pricebook2Id", "type": "Lookup", "description": "Reference to the price book" }
        ],
        "relationships": [
          { "target": "Product2", "type": "child", "description": "Entries belong to a product" },
          { "target": "Pricebook2", "type": "child", "description": "Entries belong to a price book" }
        ]
      },
      {
        "name": "AcademicOrder",
        "type": "standard",
        "domain": "financials",
        "description": "A student financial order that aggregates all charges for a specific term into a single record. Academic orders are generated automatically based on a student's enrollment, attributes, and applicable fee rules. Each order contains line items for every fee assessed and serves as the basis for billing and payment tracking.",
        "fields": [
          { "name": "Name", "type": "AutoNumber", "description": "Order identifier" },
          { "name": "Status", "type": "Picklist", "description": "Order status (draft, activated, paid, past due)" },
          { "name": "TotalAmount", "type": "Currency", "description": "Total charges on the order" },
          { "name": "TermId", "type": "Lookup", "description": "Academic term this order covers" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" },
          { "name": "EffectiveDate", "type": "Date", "description": "Date the order becomes effective" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Orders belong to a student" },
          { "target": "OrderProduct", "type": "parent", "description": "Orders contain line items" },
          { "target": "AcademicTerm", "type": "lookup", "description": "Orders reference the academic term" }
        ]
      },
      {
        "name": "OrderProduct",
        "type": "standard",
        "domain": "financials",
        "description": "An individual line item on an academic order representing a specific fee charge. Each order product references a fee product and captures the quantity, unit price, and total amount. Line items provide the detailed breakdown of charges on a student's account statement.",
        "fields": [
          { "name": "Quantity", "type": "Number", "description": "Number of units (e.g., credit hours)" },
          { "name": "UnitPrice", "type": "Currency", "description": "Price per unit" },
          { "name": "TotalPrice", "type": "Currency", "description": "Line item total (quantity x unit price)" },
          { "name": "OrderId", "type": "Lookup", "description": "Parent academic order" },
          { "name": "Product2Id", "type": "Lookup", "description": "Fee product being charged" }
        ],
        "relationships": [
          { "target": "AcademicOrder", "type": "child", "description": "Line items belong to an order" },
          { "target": "Product2", "type": "lookup", "description": "Line items reference a fee product" }
        ]
      }
    ],
    "metadata": [
      {
        "type": "FinancialAidRule__mdt",
        "name": "Financial Aid Rules",
        "fields": { "AidType__c": "Picklist", "EligibilityCriteria__c": "LongTextArea", "MaxAwardAmount__c": "Currency", "StackingAllowed__c": "Checkbox" },
        "description": "Configures financial aid packaging rules including eligibility criteria, maximum award amounts, and whether multiple aid types can be combined for the same student."
      },
      {
        "type": "FeeCalculationRule__mdt",
        "name": "Fee Calculation Rules",
        "fields": { "FeeProductId__c": "Text", "StudentAttribute__c": "Text", "Condition__c": "Text", "Multiplier__c": "Number" },
        "description": "Defines rules for calculating student fees based on attributes like residency status, enrollment intensity, and program level. Rules specify conditions and multipliers applied during academic order generation."
      }
    ]
  },

  "mentoring": {
    "objects": [
      {
        "name": "MentoringProgram",
        "type": "standard",
        "domain": "mentoring",
        "description": "Defines a structured mentoring initiative with goals, eligibility criteria, duration, and available benefits. Each program specifies the type of mentoring (peer, career, academic) and configures the matching criteria used to pair mentors with mentees.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Program name" },
          { "name": "ProgramType", "type": "Picklist", "description": "Type of mentoring (peer, career, academic, alumni)" },
          { "name": "Status", "type": "Picklist", "description": "Program status (planned, active, completed)" },
          { "name": "StartDate", "type": "Date", "description": "Program start date" },
          { "name": "EndDate", "type": "Date", "description": "Program end date" },
          { "name": "MaxParticipants", "type": "Number", "description": "Maximum mentee capacity" }
        ],
        "relationships": [
          { "target": "MentoringProfile", "type": "parent", "description": "Programs have mentor and mentee profiles" },
          { "target": "MentoringBenefit", "type": "parent", "description": "Programs define available benefits" }
        ]
      },
      {
        "name": "MentoringProfile",
        "type": "standard",
        "domain": "mentoring",
        "description": "Captures detailed information about a mentor or mentee for profile-based matching. Profile fields include skills, experience areas, availability, communication preferences, and goals. The AI matching engine compares profiles to suggest optimal mentor-mentee pairings.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Profile display name" },
          { "name": "Role", "type": "Picklist", "description": "Participant role (mentor, mentee)" },
          { "name": "Skills", "type": "LongTextArea", "description": "Skills and areas of expertise" },
          { "name": "Goals", "type": "LongTextArea", "description": "Mentoring goals and expectations" },
          { "name": "Availability", "type": "Picklist", "description": "Availability level (weekly, biweekly, monthly)" },
          { "name": "ProgramId", "type": "Lookup", "description": "Mentoring program this profile belongs to" },
          { "name": "AccountId", "type": "Lookup", "description": "Person account of the participant" }
        ],
        "relationships": [
          { "target": "MentoringProgram", "type": "child", "description": "Profiles belong to a mentoring program" },
          { "target": "Account", "type": "lookup", "description": "Profiles reference a person account" }
        ]
      },
      {
        "name": "MentoringBenefit",
        "type": "standard",
        "domain": "mentoring",
        "description": "Defines a type of support available within a mentoring program such as tutoring, career advice, networking introductions, or skill workshops. Benefits establish the scope and frequency of support that mentees can receive from their assigned mentors.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Benefit name" },
          { "name": "Type", "type": "Picklist", "description": "Benefit type (tutoring, coaching, networking, workshop)" },
          { "name": "Description", "type": "TextArea", "description": "What this benefit provides" },
          { "name": "Frequency", "type": "Picklist", "description": "Expected delivery frequency (weekly, monthly, as needed)" },
          { "name": "ProgramId", "type": "Lookup", "description": "Program this benefit belongs to" }
        ],
        "relationships": [
          { "target": "MentoringProgram", "type": "child", "description": "Benefits belong to a mentoring program" },
          { "target": "MentoringBenefitAssignment", "type": "parent", "description": "Benefits are assigned through assignment records" }
        ]
      },
      {
        "name": "MentoringBenefitAssignment",
        "type": "standard",
        "domain": "mentoring",
        "description": "Records the assignment of a specific mentoring benefit to a mentee by their mentor. Assignment records track delivery dates, completion status, and outcomes for each benefit provided during the mentoring relationship.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Assignment display name" },
          { "name": "Status", "type": "Picklist", "description": "Assignment status (assigned, in progress, completed)" },
          { "name": "AssignedDate", "type": "Date", "description": "Date the benefit was assigned" },
          { "name": "CompletedDate", "type": "Date", "description": "Date the benefit was delivered" },
          { "name": "BenefitId", "type": "Lookup", "description": "Reference to the mentoring benefit" },
          { "name": "MentorProfileId", "type": "Lookup", "description": "Reference to the mentor's profile" },
          { "name": "MenteeProfileId", "type": "Lookup", "description": "Reference to the mentee's profile" }
        ],
        "relationships": [
          { "target": "MentoringBenefit", "type": "child", "description": "Assignments reference a benefit type" },
          { "target": "MentoringProfile", "type": "lookup", "description": "Assignments link mentor and mentee profiles" }
        ]
      }
    ],
    "metadata": [
      {
        "type": "MentoringMatchCriteria__mdt",
        "name": "Mentoring Match Criteria",
        "fields": { "FieldName__c": "Text", "Weight__c": "Number", "MatchType__c": "Picklist", "IsRequired__c": "Checkbox" },
        "description": "Configures which profile fields are used for AI-powered mentor-mentee matching and their relative importance weights. Match types include exact match, similarity scoring, and range matching."
      }
    ]
  },

  "alumni": {
    "objects": [
      {
        "name": "GiftTransaction",
        "type": "standard",
        "domain": "alumni",
        "description": "Records a charitable donation made by an alumni or supporter. Each transaction captures the donor, gift amount, designation, payment method, and acknowledgment status. Gift transactions are the core record for tracking philanthropic giving to the institution.",
        "fields": [
          { "name": "Name", "type": "AutoNumber", "description": "Transaction identifier" },
          { "name": "Amount", "type": "Currency", "description": "Gift amount" },
          { "name": "GiftDate", "type": "Date", "description": "Date the gift was made" },
          { "name": "Designation", "type": "Picklist", "description": "Fund designation (unrestricted, scholarship, building, endowment)" },
          { "name": "PaymentMethod", "type": "Picklist", "description": "How the gift was made (check, credit card, wire, securities)" },
          { "name": "AcknowledgmentStatus", "type": "Picklist", "description": "Status of the tax acknowledgment letter" },
          { "name": "DonorId", "type": "Lookup", "description": "Person account of the donor" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Gift transactions belong to a donor" },
          { "target": "GiftCommitment", "type": "lookup", "description": "Transactions may fulfill a pledge commitment" }
        ]
      },
      {
        "name": "GiftCommitment",
        "type": "standard",
        "domain": "alumni",
        "description": "Represents a donor's multi-year pledge or recurring giving commitment. Commitment records track the total amount promised, payment schedule, amount received to date, and outstanding balance. Pledge fulfillment workflows generate reminders and track payment progress.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Commitment display name" },
          { "name": "TotalAmount", "type": "Currency", "description": "Total pledged amount" },
          { "name": "AmountReceived", "type": "Currency", "description": "Amount paid to date" },
          { "name": "PaymentSchedule", "type": "Picklist", "description": "Payment frequency (monthly, quarterly, annually)" },
          { "name": "StartDate", "type": "Date", "description": "Pledge start date" },
          { "name": "EndDate", "type": "Date", "description": "Pledge end date" },
          { "name": "DonorId", "type": "Lookup", "description": "Person account of the pledging donor" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Commitments belong to a donor" },
          { "target": "GiftTransaction", "type": "parent", "description": "Commitments are fulfilled by gift transactions" }
        ]
      },
      {
        "name": "VolunteerActivity",
        "type": "standard",
        "domain": "alumni",
        "description": "Records an alumni volunteer's participation in an institutional activity such as mentoring, advisory board service, career panels, or campus events. Volunteer records track hours contributed, activity type, and impact metrics for recognition and engagement scoring.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Activity name" },
          { "name": "ActivityType", "type": "Picklist", "description": "Type of volunteer activity (mentoring, board service, event, career panel)" },
          { "name": "HoursContributed", "type": "Number", "description": "Hours spent on the activity" },
          { "name": "ActivityDate", "type": "Date", "description": "Date of the activity" },
          { "name": "VolunteerId", "type": "Lookup", "description": "Person account of the volunteer" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Volunteer activities belong to an alumni" }
        ]
      }
    ]
  },

  "appointments": {
    "objects": [
      {
        "name": "ServiceAppointment",
        "type": "standard",
        "domain": "appointments",
        "description": "Represents a scheduled or walk-in appointment between a student and a staff member. Service appointments capture the appointment type, scheduled time, duration, status, and associated service territory. Appointments support in-person, virtual, and phone meeting channels.",
        "fields": [
          { "name": "Subject", "type": "Text", "description": "Appointment subject or topic" },
          { "name": "Status", "type": "Picklist", "description": "Appointment status (scheduled, checked in, completed, no show)" },
          { "name": "SchedStartTime", "type": "DateTime", "description": "Scheduled start time" },
          { "name": "SchedEndTime", "type": "DateTime", "description": "Scheduled end time" },
          { "name": "AppointmentType", "type": "Picklist", "description": "Meeting type (advising, tutoring, financial aid, administrative)" },
          { "name": "ServiceTerritoryId", "type": "Lookup", "description": "Department or location for the appointment" },
          { "name": "AccountId", "type": "Lookup", "description": "Student person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "child", "description": "Appointments are booked for students" },
          { "target": "ServiceTerritory", "type": "lookup", "description": "Appointments are assigned to a service territory" },
          { "target": "ServiceResource", "type": "lookup", "description": "Appointments are assigned to a staff member" }
        ]
      },
      {
        "name": "ServiceResource",
        "type": "standard",
        "domain": "appointments",
        "description": "Represents a staff member who is available for student appointments. Each service resource has defined working hours, skills, and service territory assignments that determine which appointment types they can fulfill and when they are available.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Staff member name" },
          { "name": "ResourceType", "type": "Picklist", "description": "Resource type (advisor, tutor, counselor, administrator)" },
          { "name": "IsActive", "type": "Checkbox", "description": "Whether this resource is currently available" },
          { "name": "RelatedRecordId", "type": "Lookup", "description": "Reference to the staff user record" }
        ],
        "relationships": [
          { "target": "ServiceTerritory", "type": "lookup", "description": "Resources are assigned to service territories" },
          { "target": "ServiceAppointment", "type": "parent", "description": "Resources receive appointment assignments" }
        ]
      },
      {
        "name": "ServiceTerritory",
        "type": "standard",
        "domain": "appointments",
        "description": "Defines a department, office, or location where appointments are offered. Service territories organize staff resources and appointment availability by functional area such as academic advising, financial aid, registrar, and student health services.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Territory name (e.g., Academic Advising Center)" },
          { "name": "Description", "type": "TextArea", "description": "Territory description and services offered" },
          { "name": "IsActive", "type": "Checkbox", "description": "Whether this territory is currently active" },
          { "name": "OperatingHoursId", "type": "Lookup", "description": "Operating hours configuration" }
        ],
        "relationships": [
          { "target": "ServiceResource", "type": "parent", "description": "Territories have assigned service resources" },
          { "target": "ServiceAppointment", "type": "parent", "description": "Appointments are booked within territories" }
        ]
      }
    ]
  },

  "data360": {
    "objects": [
      {
        "name": "DataStream",
        "type": "standard",
        "domain": "data360",
        "description": "Defines a data ingestion connection from a legacy source system into Education Cloud. Each data stream specifies the source system, extraction schedule, field mappings, and transformation rules that convert external data into the Education Cloud schema.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Data stream name" },
          { "name": "SourceSystem", "type": "Text", "description": "Name of the external source system" },
          { "name": "Status", "type": "Picklist", "description": "Stream status (active, paused, error)" },
          { "name": "Schedule", "type": "Text", "description": "Extraction schedule (daily, hourly, real-time)" },
          { "name": "LastRunDate", "type": "DateTime", "description": "Timestamp of the last successful extraction" }
        ],
        "relationships": [
          { "target": "IdentityResolutionRuleset", "type": "lookup", "description": "Data streams feed into identity resolution rulesets" }
        ]
      },
      {
        "name": "IdentityResolutionRuleset",
        "type": "standard",
        "domain": "data360",
        "description": "A collection of matching rules used to detect and resolve duplicate student records across source systems. Each ruleset defines the combination of fields used for comparison and the confidence thresholds for automatic versus manual merge decisions.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Ruleset name" },
          { "name": "Status", "type": "Picklist", "description": "Ruleset status (active, draft, disabled)" },
          { "name": "AutoMergeThreshold", "type": "Percent", "description": "Confidence score above which records merge automatically" },
          { "name": "ReviewThreshold", "type": "Percent", "description": "Confidence score above which records are flagged for manual review" }
        ],
        "relationships": [
          { "target": "MatchRule", "type": "parent", "description": "Rulesets contain matching rules" }
        ]
      },
      {
        "name": "MatchRule",
        "type": "standard",
        "domain": "data360",
        "description": "An individual matching criterion within an identity resolution ruleset. Each match rule specifies a field comparison, such as exact match on email or fuzzy match on name, along with a weight that determines its contribution to the overall confidence score.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Rule name" },
          { "name": "MatchField", "type": "Text", "description": "The field being compared (email, name, date of birth)" },
          { "name": "MatchType", "type": "Picklist", "description": "Comparison method (exact, fuzzy, phonetic)" },
          { "name": "Weight", "type": "Number", "description": "Importance weight for scoring (1-100)" },
          { "name": "RulesetId", "type": "Lookup", "description": "Parent identity resolution ruleset" }
        ],
        "relationships": [
          { "target": "IdentityResolutionRuleset", "type": "child", "description": "Match rules belong to a ruleset" }
        ]
      },
      {
        "name": "UnifiedIndividual",
        "type": "standard",
        "domain": "data360",
        "description": "The result of identity resolution, representing a single authoritative record for an individual created by merging data from multiple source systems. Survivorship rules determine which source provides the best value for each field, producing a comprehensive 360-degree view of the learner.",
        "fields": [
          { "name": "Name", "type": "Text", "description": "Unified record display name" },
          { "name": "SourceCount", "type": "Number", "description": "Number of source records that were merged" },
          { "name": "ConfidenceScore", "type": "Percent", "description": "Overall confidence in the identity match" },
          { "name": "LastResolvedDate", "type": "DateTime", "description": "Timestamp of the last resolution run" },
          { "name": "AccountId", "type": "Lookup", "description": "Reference to the resulting person account" }
        ],
        "relationships": [
          { "target": "Account", "type": "lookup", "description": "Unified individuals map to person accounts" }
        ]
      }
    ]
  }

};
